src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Check_Address__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Check Address</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Address__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Billing_Preferences</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Address_Barangay__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Barangay</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Reference__c.Field__c</field>
                <operation>equals</operation>
                <value>Barangay</value>
            </filterItems>
            <filterItems>
                <field>Reference__c.Parent__c</field>
                <operation>equals</operation>
                <valueField>$Source.Address_City_Municipality__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Reference__c</referenceTo>
        <relationshipLabel>Addresses (Barangay)</relationshipLabel>
        <relationshipName>Addresses2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Address_City_Municipality__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>City / Municipality</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Reference__c.Field__c</field>
                <operation>equals</operation>
                <value>City</value>
            </filterItems>
            <filterItems>
                <field>Reference__c.Parent__c</field>
                <operation>equals</operation>
                <valueField>$Source.Address_Province__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Reference__c</referenceTo>
        <relationshipLabel>Addresses (City / Municipality)</relationshipLabel>
        <relationshipName>Addresses1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Address_Province__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Province</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Reference__c.Field__c</field>
                <operation>equals</operation>
                <value>Province</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Reference__c</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>Addresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Address_Street_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Street Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Reference__c.Field__c</field>
                <operation>equals</operation>
                <value>Street</value>
            </filterItems>
            <filterItems>
                <field>Reference__c.Parent__c</field>
                <operation>equals</operation>
                <valueField>$Source.Address_Subdivision__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Reference__c</referenceTo>
        <relationshipLabel>Addresses (Street Name)</relationshipLabel>
        <relationshipName>Addresses4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Address_Street_No__c</fullName>
        <label>Street #</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address_Subdivision__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subdivision / Bldg</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Reference__c.Field__c</field>
                <operation>equals</operation>
                <value>Subdivision</value>
            </filterItems>
            <filterItems>
                <field>Reference__c.Parent__c</field>
                <operation>equals</operation>
                <valueField>$Source.Address_Barangay__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Reference__c</referenceTo>
        <relationshipLabel>Addresses (Subdivision)</relationshipLabel>
        <relationshipName>Addresses3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Address_Unit_No__c</fullName>
        <label>Unit #</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address__c</fullName>
        <formula>Address_Unit_No__c &amp; &quot; &quot; &amp;  Address_Street_No__c &amp; &quot; &quot; &amp; Address_Street_Name__r.Name &amp; &quot;, &quot; &amp; Address_Subdivision__r.Name &amp; &quot; &quot; &amp;  Address_Barangay__r.Name &amp; &quot;, &quot; &amp; Address_City_Municipality__r.Name &amp; &quot;, &quot; &amp;  Address_Province__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Address</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Premise_Type__c</fullName>
        <label>Premises Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Billboard</fullName>
                </value>
                <value>
                    <fullName>Cemetery</fullName>
                </value>
                <value>
                    <fullName>Commercial Building</fullName>
                </value>
                <value>
                    <fullName>Compound Residential</fullName>
                </value>
                <value>
                    <fullName>Government Building</fullName>
                </value>
                <value>
                    <fullName>Groups of Industry</fullName>
                </value>
                <value>
                    <fullName>High-rise Building</fullName>
                </value>
                <value>
                    <fullName>Meralco Use Substation</fullName>
                </value>
                <value>
                    <fullName>Offices</fullName>
                </value>
                <value>
                    <fullName>Others</fullName>
                </value>
                <value>
                    <fullName>Pole</fullName>
                </value>
                <value>
                    <fullName>Single Commercial</fullName>
                </value>
                <value>
                    <fullName>Single-Detached Residential</fullName>
                </value>
                <value>
                    <fullName>Single Industry</fullName>
                </value>
                <value>
                    <fullName>Streetlights</fullName>
                </value>
                <value>
                    <fullName>Telecom Cabinet</fullName>
                </value>
                <value>
                    <fullName>Traffic Lights</fullName>
                </value>
                <value>
                    <fullName>Condominium</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Service</fullName>
                </value>
                <value>
                    <fullName>Billing</fullName>
                </value>
                <value>
                    <fullName>Customer</fullName>
                </value>
                <value>
                    <fullName>Meter</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Address</label>
    <nameField>
        <displayFormat>ADD-{000000}</displayFormat>
        <label>Address Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Barangay__c</fullName>
        <label>Barangay</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Check_Address__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Check Address</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>City_Municipality__c</fullName>
        <label>City / Municipality</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Province__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>City_Municipality</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Province__c</fullName>
        <label>Province</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Province</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Street_Name__c</fullName>
        <label>Street Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street_No__c</fullName>
        <label>House #</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subdivision__c</fullName>
        <label>Subdivision / Bldg Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unit_No__c</fullName>
        <label>Unit #</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Reference__c.object
<CustomObject>
    <description>This contain Address, Geo Code, Picklist Value, Picklist Code</description>
    <fields>
        <fullName>Field__c</fullName>
        <externalId>true</externalId>
        <label>Field</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent</label>
        <referenceTo>Reference__c</referenceTo>
        <relationshipName>Picklist_Codes_Transformation</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Geo</fullName>
                </value>
                <value>
                    <fullName>Picklist</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Reference</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>References</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TriggerControl__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Enables/disables an object trigger based on setting value</description>
    <fields>
        <fullName>Account__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Account</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Address__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Address</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Lead</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Reference__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Reference</label>
        <type>Checkbox</type>
    </fields>
    <label>Trigger Control</label>
</CustomObject>

src/globalValueSets/City_Municipality.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>ALAMINOS</fullName>
    </customValue>
    <customValue>
        <fullName>ALFONSO</fullName>
    </customValue>
    <customValue>
        <fullName>AMADEO</fullName>
    </customValue>
    <customValue>
        <fullName>ANGAT</fullName>
    </customValue>
    <customValue>
        <fullName>ANGONO</fullName>
    </customValue>
    <customValue>
        <fullName>ANTIPOLO</fullName>
    </customValue>
    <customValue>
        <fullName>APALIT</fullName>
    </customValue>
    <customValue>
        <fullName>BACOOR</fullName>
    </customValue>
    <customValue>
        <fullName>BALAGTAS</fullName>
    </customValue>
    <customValue>
        <fullName>BALIUAG</fullName>
    </customValue>
    <customValue>
        <fullName>BARAS</fullName>
    </customValue>
    <customValue>
        <fullName>BATANGAS CITY</fullName>
    </customValue>
    <customValue>
        <fullName>BAY</fullName>
    </customValue>
    <customValue>
        <fullName>BINAN</fullName>
    </customValue>
    <customValue>
        <fullName>BINANGONAN</fullName>
    </customValue>
    <customValue>
        <fullName>BOCAUE</fullName>
    </customValue>
    <customValue>
        <fullName>BULACAN</fullName>
    </customValue>
    <customValue>
        <fullName>BUSTOS</fullName>
    </customValue>
    <customValue>
        <fullName>CABUYAO</fullName>
    </customValue>
    <customValue>
        <fullName>CAINTA</fullName>
    </customValue>
    <customValue>
        <fullName>CALAMBA</fullName>
    </customValue>
    <customValue>
        <fullName>CALAUAN</fullName>
    </customValue>
    <customValue>
        <fullName>CALOOCAN CITY</fullName>
    </customValue>
    <customValue>
        <fullName>CALUMPIT</fullName>
    </customValue>
    <customValue>
        <fullName>CANDABA</fullName>
    </customValue>
    <customValue>
        <fullName>CANDELARIA</fullName>
    </customValue>
    <customValue>
        <fullName>CARDONA</fullName>
    </customValue>
    <customValue>
        <fullName>CARMONA</fullName>
    </customValue>
    <customValue>
        <fullName>CAVITE CITY</fullName>
    </customValue>
    <customValue>
        <fullName>DASMARINAS CITY</fullName>
    </customValue>
    <masterLabel>City/ Municipality</masterLabel>
</GlobalValueSet>

src/globalValueSets/Province.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>BATANGAS</fullName>
    </customValue>
    <customValue>
        <fullName>BULACAN</fullName>
    </customValue>
    <customValue>
        <fullName>METRO MANILA</fullName>
    </customValue>
    <customValue>
        <fullName>CAVITE</fullName>
    </customValue>
    <customValue>
        <fullName>LAGUNA</fullName>
    </customValue>
    <customValue>
        <fullName>RIZAL</fullName>
    </customValue>
    <customValue>
        <fullName>QUEZON</fullName>
    </customValue>
    <customValue>
        <fullName>PAMPANGA</fullName>
    </customValue>
    <customValue>
        <fullName>NUEVA ECIJA</fullName>
    </customValue>
    <customValue>
        <fullName>FLAT STREETLIGHT</fullName>
    </customValue>
    <masterLabel>Province</masterLabel>
</GlobalValueSet>

src/classes/LeadTriggerHandler.cls
/* 
 * Description: Handles the logic for Lead Trigger
 * Author: Jerson Poblete (Accenture)
 * Date Created: MAR-14-17
 */ 
 public with sharing class LeadTriggerHandler implements TriggerInterface {
    //Checks to see if the trigger has been disabled either by custom setting or by running code
    public Boolean IsDisabled() {
        //Added trigger control from heirarchy custom setting
        TriggerControl__c triggerControl = TriggerControl__c.getInstance();
        return triggerControl.Lead__c;
    }

    public void BeforeInsert(List<SObject> newList) {} 
    
    public void BeforeUpdate(Map<Id, SObject> newMap, Map<Id, SObject> oldMap) {}
    
    public void BeforeDelete(Map<Id, SObject> oldMap){}

    public void AfterInsert(Map<Id, SObject> newMap){}

    public void AfterUpdate(Map<Id, SObject> newMap, Map<Id, SObject> oldMap) {
    	createAddressForConvertedAccounts(newMap.values()); // CSM-1904, CSM-2029
    }
    
    public void AfterDelete(Map<Id, SObject> oldMap){}

    public void AfterUndelete(Map<Id, SObject> oldMap){}

	/* 
	 * Description: CSM-1904: Validate the Lead's address before converting to Account 
	 * Parameters: List of Lead
	 * Returns: N/A
	 * Author: Jerome To
	 * Date Created: MAR-19-17
	 *				 MAR-28-17	Jerome To 		CSM-2029: Added map for each geo field and update on converted account
	 */  
	private void createAddressForConvertedAccounts(List<Lead> newList) {
		List<String> fieldList = new List<String> { CXE_Constants.REFERENCE_FIELD_STREET, CXE_Constants.REFERENCE_FIELD_SUBDIVISION,
												 CXE_Constants.REFERENCE_FIELD_BARANGAY, CXE_Constants.REFERENCE_FIELD_CITY,
												 CXE_Constants.REFERENCE_FIELD_PROVINCE };
		Set<String> addressNames = new Set<String>();
		List<Address__c> addressList = new List<Address__c>();

		Set<Id> convertedLeadsWithInvalidAddress = new Set<Id>();

		//Map<String, List<Reference__c>> referenceMap = new Map<String, List<Reference__c>>();
		Set<Id> leadsToCheck = new Set<Id>();

		for (Lead leadRec : newList) {
			if(leadRec.IsConverted && String.isNotBlank(leadRec.Street_Name__c) &&
			   String.isNotBlank(leadRec.Subdivision__c) && String.isNotBlank(leadRec.Barangay__c) && 
			   String.isNotBlank(leadRec.City_Municipality__c) && String.isNotBlank(leadRec.Province__c)) {					
				addressNames.add(leadRec.Street_Name__c.toUpperCase());
				addressNames.add(leadRec.Subdivision__c.toUpperCase());
				addressNames.add(leadRec.Barangay__c.toUpperCase());
				addressNames.add(leadRec.City_Municipality__c.toUpperCase());
				addressNames.add(leadRec.Province__c.toUpperCase());
				leadsToCheck.add(leadRec.Id);
			}
		}

		if(!leadsToCheck.isEmpty()) {

			Map<String, List<Reference__c>> referenceMapStreet = new Map<String, List<Reference__c>>();
			Map<String, List<Reference__c>> referenceMapSubdivision = new Map<String, List<Reference__c>>();
			Map<String, List<Reference__c>> referenceMapBarangay = new Map<String, List<Reference__c>>();
			Map<String, List<Reference__c>> referenceMapCity = new Map<String, List<Reference__c>>();
			Map<String, List<Reference__c>> referenceMapProvince = new Map<String, List<Reference__c>>();

			for (Reference__c referenceRec : [SELECT Id, Name, Parent__c, Parent__r.Name, Field__c 
					                          FROM Reference__c 
					                          WHERE Type__c = :CXE_Constants.REFERENCE_TYPE_GEO
					                          AND Field__c IN :fieldList
					                          AND Name IN :addressNames]) {

				if(referenceRec.Field__c == CXE_Constants.REFERENCE_FIELD_STREET) {
					if(referenceMapStreet.containsKey(referenceRec.Name.toUpperCase())) {
						List<Reference__c> refList = referenceMapStreet.get(referenceRec.Name.toUpperCase());
						refList.add(referenceRec);
						referenceMapStreet.put(referenceRec.Name.toUpperCase(), refList);
					} else {
						referenceMapStreet.put(referenceRec.Name.toUpperCase(), new List<Reference__c> { referenceRec });
					}
				}

				if(referenceRec.Field__c == CXE_Constants.REFERENCE_FIELD_SUBDIVISION) {
					if(referenceMapSubdivision.containsKey(referenceRec.Name.toUpperCase())) {
						List<Reference__c> refList = referenceMapSubdivision.get(referenceRec.Name.toUpperCase());
						refList.add(referenceRec);
						referenceMapSubdivision.put(referenceRec.Name.toUpperCase(), refList);
					} else {
						referenceMapSubdivision.put(referenceRec.Name.toUpperCase(), new List<Reference__c> { referenceRec });
					}
				}

				if(referenceRec.Field__c == CXE_Constants.REFERENCE_FIELD_BARANGAY) {
					if(referenceMapBarangay.containsKey(referenceRec.Name.toUpperCase())) {
						List<Reference__c> refList = referenceMapBarangay.get(referenceRec.Name.toUpperCase());
						refList.add(referenceRec);
						referenceMapBarangay.put(referenceRec.Name.toUpperCase(), refList);
					} else {
						referenceMapBarangay.put(referenceRec.Name.toUpperCase(), new List<Reference__c> { referenceRec });
					}
				}

				if(referenceRec.Field__c == CXE_Constants.REFERENCE_FIELD_CITY) {
					if(referenceMapCity.containsKey(referenceRec.Name.toUpperCase())) {
						List<Reference__c> refList = referenceMapCity.get(referenceRec.Name.toUpperCase());
						refList.add(referenceRec);
						referenceMapCity.put(referenceRec.Name.toUpperCase(), refList);
					} else {
						referenceMapCity.put(referenceRec.Name.toUpperCase(), new List<Reference__c> { referenceRec });
					}
				}

				if(referenceRec.Field__c == CXE_Constants.REFERENCE_FIELD_PROVINCE) {
					if(referenceMapProvince.containsKey(referenceRec.Name.toUpperCase())) {
						List<Reference__c> refList = referenceMapProvince.get(referenceRec.Name.toUpperCase());
						refList.add(referenceRec);
						referenceMapProvince.put(referenceRec.Name.toUpperCase(), refList);
					} else {
						referenceMapProvince.put(referenceRec.Name.toUpperCase(), new List<Reference__c> { referenceRec });
					}
				}
			}

			for (Lead leadRec : newList) {
				if(leadRec.IsConverted) {
					if(leadsToCheck.contains(leadRec.Id)) {

					    Address__c addressRec = new Address__c();	
						Boolean isValidStreet = false;
						Boolean isValidSubdivision = false;
						Boolean isValidBarangay = false;
						Boolean isValidCity = false;
						Boolean isValidProvince = false;

						if(referenceMapStreet.containsKey(leadRec.Street_Name__c.toUpperCase())) {
							for(Reference__c ref : referenceMapStreet.get(leadRec.Street_Name__c.toUpperCase())) {
								if(leadRec.Subdivision__c == ref.Parent__r.Name) {
									isValidStreet = true;
									addressRec.Address_Street_Name__c = ref.Id;
								}
							}
						}

						if(isValidStreet && referenceMapSubdivision.containsKey(leadRec.Subdivision__c.toUpperCase())) {
							for(Reference__c ref : referenceMapSubdivision.get(leadRec.Subdivision__c.toUpperCase())) {
								if(leadRec.Barangay__c == ref.Parent__r.Name) {
									isValidSubdivision = true;
									addressRec.Address_Subdivision__c = ref.Id;
								}
							}						
						} else{
							//leadRec.addError(CXE_Constants.LEAD_CHECK_ADDRESS);
							continue;
						}

						if(isValidSubdivision && referenceMapBarangay.containsKey(leadRec.Barangay__c.toUpperCase())) {
							for(Reference__c ref : referenceMapBarangay.get(leadRec.Barangay__c.toUpperCase())) {
								if(leadRec.City_Municipality__c == ref.Parent__r.Name) {
									isValidBarangay = true;
									addressRec.Address_Barangay__c = ref.Id;
								}
							}						
						} else{
							//leadRec.addError(CXE_Constants.LEAD_CHECK_ADDRESS);
							continue;
						}

						if(isValidBarangay && referenceMapCity.containsKey(leadRec.City_Municipality__c.toUpperCase())) {
							for(Reference__c ref : referenceMapCity.get(leadRec.City_Municipality__c.toUpperCase())) {
								if(leadRec.Province__c == ref.Parent__r.Name) {
									isValidCity = true;
									isValidProvince = true;
									addressRec.Address_City_Municipality__c = ref.Id;
									addressRec.Address_Province__c = ref.Parent__c;
								}
							}						
						} else{
							//leadRec.addError(CXE_Constants.LEAD_CHECK_ADDRESS);
							continue;
						}

						if( isValidCity && isValidProvince ) {
							addressRec.Address_Unit_No__c = leadRec.Unit_No__c;
							addressRec.Address_Street_No__c = leadRec.Street_No__c;
							addressRec.Premise_Type__c = CXE_Constants.ADDRESS_PREMISE_TYPE_OTHERS;
							addressRec.Account__c =  leadRec.ConvertedAccountId;
							addressList.add(addressRec);
						} else{
							//leadRec.addError(CXE_Constants.LEAD_CHECK_ADDRESS);
							continue;
						}

					} 
				}
			} 

			// Start CSM-2029		Jerome To 		MAR-28-2017
			if(!addressList.isEmpty()) {
				Set<Id> validAddressIds = new Set<Id>();
				List<Database.SaveResult> srList = Database.insert(addressList, false);
				for (Database.SaveResult sr : srList) {
				    if (sr.isSuccess()) {
				    	validAddressIds.add(sr.getId());
				    }
				}
				if(!validAddressIds.isEmpty()) {
					Set<Id> accountIds = new Set<Id>();
					for(Address__c addressRec : [SELECT Account__c FROM Address__c WHERE Id IN:validAddressIds]){
						accountIds.add(addressRec.Account__c);
					}
					if(!accountIds.isEmpty()) {
						updateAccountCheckAddress(accountIds);
					}
				}
			}
			// End CSM-2029		Jerome To 		MAR-28-2017
		}
	}

	/* 
	 * Description: CSM-2029
	 * Parameters: List of Lead
	 * Returns: N/A
	 * Author: Jerome To
	 * Date Created: MAR-28-17
	 */ 
	private void updateAccountCheckAddress(Set<Id> accountIds){
		if(!accountIds.isEmpty()) {
			List<Account> accountList = [SELECT Check_Address__c FROM Account WHERE Id IN:accountIds];
			if(!accountList.isEmpty()) {
				for(Account acct : accountList) {
					acct.Check_Address__c = true;
				}

				//update accountList;
				List<Database.SaveResult> srList = Database.update(accountList, false);
				for (Database.SaveResult sr : srList) {
				    if (!sr.isSuccess()) {
				    	String errors = '';		    	
				    	List<String> errorList = new List<String>();
				    	errorList.add(CXE_Constants.CASE_APPLICATION_ERROR_MESSAGE_STRING1);
				        for(Database.Error err : sr.getErrors()) {
				            //errors += err.getStatusCode() + ': ' + err.getMessage();
				            errorList.add(err.getMessage());
				            //errors += CXE_Constants.CASE_APPLICATION_ERROR_MESSAGE_STRING2 + err.getFields();
				        }
				        errors += String.join(errorList, '');
				        System.debug('------- Error has occured in updating Account ------' + errors);
				    }
				}
			}
		}
	}
}