src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Tax_Identification_No__c</fullName>
        <label>Tax Identification Number</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Address__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Billing_Preferences</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Address__c</fullName>
        <formula>Address_Unit_No__c &amp; &quot; &quot; &amp;  Address_Street_No__c &amp; &quot; &quot; &amp; Address_Street_Name__r.Name &amp; &quot;, &quot; &amp; Address_Subdivision__r.Name &amp; &quot; &quot; &amp;  Address_Barangay__r.Name &amp; &quot;, &quot; &amp; Address_City_Municipality__r.Name &amp; &quot;, &quot; &amp;  Address_Province__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Address</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipName>Billing_Preferences</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipName>Billing_Preferences</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Service</fullName>
                </value>
                <value>
                    <fullName>Billing</fullName>
                </value>
                <value>
                    <fullName>Customer</fullName>
                </value>
                <value>
                    <fullName>Meter</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Address</label>
    <nameField>
        <displayFormat>ADD-{000000}</displayFormat>
        <label>Address Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Agreement__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Agreements</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Advance_Frequency_months__c</fullName>
        <description>Advanced frequency</description>
        <label>Advance Frequency (months)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Advance_amount__c</fullName>
        <description>Current advanced amount</description>
        <label>Advance Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Agreement_Duration_Months__c</fullName>
        <defaultValue>36</defaultValue>
        <label>Agreement Term (months)</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Agreement_End_Date__c</fullName>
        <description>Agreement End Date</description>
        <inlineHelpText>End Date of the agreement</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Agreement_Start_Date__c</fullName>
        <description>Agreement Start Date</description>
        <inlineHelpText>Start Date of the agreement</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipName>Agreements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Charges_for_breach_of_contract__c</fullName>
        <formula>Commercial_Product__r.Charges_for_breach_of_contract__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Charges for Breach of Contract</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Commercial_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Commercial Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipName>Agreements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contract__c</fullName>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipName>Agreements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PSIC__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>PSIC</label>
        <referenceTo>PSIC__c</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Service</label>
    <nameField>
        <displayFormat>SERV-{00000000}</displayFormat>
        <label>Service ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Date_of_Birth__c</fullName>
        <label>Date of Birth</label>
        <type>Date</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Advance_amount__c</fullName>
        <label>Advance amount</label>
        <summarizedField>Agreement__c.Advance_amount__c</summarizedField>
        <summaryFilterItems>
            <field>Agreement__c.Active_Agreement__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryForeignKey>Agreement__c.Contract__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Regular</fullName>
                </value>
                <value>
                    <fullName>Prepaid</fullName>
                </value>
                <value>
                    <fullName>SOLR</fullName>
                </value>
                <value>
                    <fullName>Retailer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Master_Product__c.object
<CustomObject>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Electricity</fullName>
                </value>
                <value>
                    <fullName>Non-commodity</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Master Product</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Master Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Case.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Charges_for_breach_of_contract__c</fullName>
        <label>Charges for Breach of Contract</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Master_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Master Product</label>
        <referenceTo>Master_Product__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Utility_Type__c</fullName>
        <label>Utility Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Green</fullName>
                </value>
                <value>
                    <fullName>Grey</fullName>
                </value>
                <value>
                    <fullName>Grey / Green</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Commercial_Product</fullName>
        <active>true</active>
        <label>Commercial Product</label>
    </recordTypes>
</CustomObject>

src/objects/Product_Item__c.object
<CustomObject>
    <fields>
        <fullName>Field__c</fullName>
        <label>Field</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>EAV</fullName>
                </value>
                <value>
                    <fullName>EAV High (Day)</fullName>
                </value>
                <value>
                    <fullName>EAV Low (Night)</fullName>
                </value>
                <value>
                    <fullName>EAV (Exclusive Night)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Master_Product__c</fullName>
        <label>Master Product</label>
        <referenceTo>Master_Product__c</referenceTo>
        <relationshipLabel>Product Items</relationshipLabel>
        <relationshipName>Product_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Product Item</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/PSIC__c.object
<CustomObject>
    <description>PSIC</description>
    <label>PSIC</label>
    <nameField>
        <label>PSIC Description</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PSICs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Reference__c.object
<CustomObject>
    <description>This contain Address, Geo Code, Picklist Value, Picklist Code</description>
    <fields>
        <fullName>Field__c</fullName>
        <externalId>true</externalId>
        <label>Field</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Name_Code__c</fullName>
        <externalId>true</externalId>
        <label>Name Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent</label>
        <referenceTo>Reference__c</referenceTo>
        <relationshipName>Picklist_Codes_Transformation</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Geo</fullName>
                </value>
                <value>
                    <fullName>Picklist</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Reference</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>References</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Schedule__c.object
<CustomObject>
    <label>Deposit Schedule</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deposit Schedule</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MoveHomeOpportunityTest.cls
/**
  * @author       : Sanchayeeta
  * @date         : 05/11/2015
  * @description  : Test Class for MoveHomeOpportunity class 
  */  
@isTest
public class MoveHomeOpportunityTest{
     
    //@testSetup static void setUp() {
    //    // create References
    //    List<Reference__c> addressRefList = CXE_TestDataFactory.createSampleReferenceListForAddress();
    //    insert addressRefList;
    //    for(Integer i=0 ; i<addressRefList.size() ; i++) {
    //        if(i>0){
    //            addressRefList.get(i).Parent__c = addressRefList.get(i-1).Id;
    //        }
    //    }
    //    update addressRefList;      
    //}

    //private static testMethod void TestMet(){
            
    //    //inserting Account
    //    Account acc=new Account();
    //    acc.LastName = 'SanTestSan';
    //    acc.Phone = '55555555';
    //    insert acc;
        
    //    /*RecordType rtype = [SELECT id FROM RecordType WHERE sObjectType='Case' and isActive=true AND Recordtype.Developername='New_Service_Application'];
    //    //Inserting Case Record
    //    Case caseTest=new Case();
    //    caseTest.RecordtypeId=rtype.Id;
    //    caseTest.Origin='Phone';
    //caseTest.NEW_Bank_Name__c = 'Yes Bank';
    //caseTest.NEW_Terms_of_Payment__c ='30d end of month';
    //caseTest.New_Payment_Day__c='1st of month';
    //caseTest.NEW_IBAN__c ='Test';
    //    caseTest.Subject='Test Subject';
    //    caseTest.AccountId=acc.Id;
    //    insert caseTest;*/

    //    Id servRecTypeId = Schema.Sobjecttype.Case.getRecordTypeInfosByName().get(CXE_Constants.CASE_NEW_SERVICE_APPLICATION).getRecordTypeId();
        
    //    List<Schedule__c> scheduleRecord = CXE_TestDataFactory.createSchedule(5);
    //    insert scheduleRecord;
        
    //    Contact contactRecord = CXE_TestDataFactory.createContact(1)[0];
    //    insert contactRecord;
        
    //    PSIC__c psicRecord = CXE_TestDataFactory.createPSIC(1)[0];
    //    insert psicRecord;
        
    //    Case caseTest = CXE_TestDataFactory.createCase(1, 'New Electric Service,', 'Single Meter', CXE_Constants.CASE_APPLICATION_RECEIVED, 'Private')[0];
    //    caseTest.AccountId=acc.Id;
    //    caseTest.RecordTypeID = servRecTypeId;
    //    caseTest.ContactId = contactRecord.id;
    //    caseTest.Individual_Business_Tag__c = 'No';
    //    caseTest.Residential_Non_Residential_Tag__c = 'Yes';
    //    caseTest.PSIC__c = psicRecord.id;
    //    caseTest.Initial_Responsible_Office__c = 'RO1';
    //    caseTest.Date_of_Birth__c = date.newInstance(1995, 1, 1);
    //    caseTest.Tax_Identification_No__c = '123';
                
    //    insert caseTest;
        
    
    
    //    // inserting opportunity
    //    Opportunity opp=TestDataFactoryTest.createOpportunity();
    
    
    //    Map<String, Reference__c> addressReference = new Map<String, Reference__c>();
    //    for(Reference__c addRef : [SELECT Id, Field__c, Name_Code__c FROM Reference__c]) {
    //        addressReference.put(addRef.Field__c, addRef);
    //    }  

    //      // inserting contract
    //    Contract contract = new Contract ();
    //    contract.Accountid = acc.id;
    //    contract.Name= 'TestContract';
    //    insert contract;

    //    system.Test.startTest();
    //    Address__c addressRec = CXE_TestDataFactory.createAddress(addressReference, true);
    //    addressRec.Case__c = caseTest.Id;
    //    addressRec.Contract__c = contract.Id;
    //    addressRec.Type__c = 'Billing';
    //    insert addressRec;

        
    //    //Creating Master Product
    //    RecordType rec=[select id from recordtype where sObjectType='Product2' AND Recordtype.developername='Commercial_Product'];
    //    Master_Product__c masterProduct=TestDataFactoryTest.createMasterProduct('Test Master','Electricity');
    //    Product_Item__c Proditem=TestDataFactoryTest.createProductItem('test prodItem','Rate',masterProduct.id,True);
    //    Product2 Prod = TestDataFactoryTest.createProduct('test prod',masterProduct.id,rec.id,'Fixed');
    //    Prod.isActive=True;
    //    prod.Utility_type__c='Electricity';
    //    update Prod;
        
    //    //Query Product
    //    //Product2 prod = [select id from Product2 where isActive = true limit 1];
        
    //    //inserting Agreement
    //    agreement__C agreemt= new agreement__C();
    //    agreemt.Account__c = acc.id;
    //    //agreemt.name ='TestAgree';
    //    agreemt.Commercial_Product__c = prod.id;
    //    agreemt.Contract__c = contract.id;
    //    agreemt.Agreement_Duration_Months__c=36;
    //    agreemt.Agreement_Start_Date__c = System.today();
    //    agreemt.Agreement_End_Date__c = System.today()+1;
    //    agreemt.Advance_Frequency_months__c=20;
    //    agreemt.Advance_amount__c =100;
    //    agreemt.Case__c =caseTest.id;
    //    //agreemt.Charges_for_breach_of_contract__c=400;
    //    insert agreemt;
        
        
    //    list<agreement__c> a = [select Id from agreement__c];
    //    system.assertNotequals(a, null); 
    //    //system.assertequals(1, 2);
      
        
       
    //    //System.Test.setCurrentPageReference(new PageReference('Page.MoveHomeOpportunity'));
    //    Test.setCurrentPage(new PageReference('Page.MoveHomeOpportunity'));
    //    ApexPages.currentPage().getParameters().put('caseid', caseTest.id);                
    //    ApexPages.StandardController sc = new ApexPages.StandardController(opp);
    //    MoveHomeOpportunity oMoveHome= new MoveHomeOpportunity(sc);
    //    //PageReference pageRef = Page.MoveHomeOpportunity;       
        
    
    //    //oMoveHome.SaveOpportunity();
    //    system.Test.stopTest();
           
    
    //}
   
}