src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Billing_Address_City_Municipal__c</fullName>
        <description>Billing address city / municipal</description>
        <inlineHelpText>Billing address city / municipal</inlineHelpText>
        <label>City / Municipality</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cainta</fullName>
                </value>
                <value>
                    <fullName>Makati City</fullName>
                </value>
                <value>
                    <fullName>Mandaluyong</fullName>
                </value>
                <value>
                    <fullName>Manila City</fullName>
                </value>
                <value>
                    <fullName>Pasig City</fullName>
                </value>
                <value>
                    <fullName>Pateros</fullName>
                </value>
                <value>
                    <fullName>Q. C.-Kaunlaran Dist 4</fullName>
                </value>
                <value>
                    <fullName>San Juan</fullName>
                </value>
                <value>
                    <fullName>Taguig City</fullName>
                </value>
                <value>
                    <fullName>Taytay</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Billing_Address_Province__c</fullName>
        <description>Billing address province</description>
        <inlineHelpText>Billing address province</inlineHelpText>
        <label>Province</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Metro Manila</fullName>
                    <default>true</default>
                    <label>Metro Manila</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Primary Email</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mobile_Phone__c</fullName>
        <inlineHelpText>Mobile Phone should start with +63 then followed by 10-digit number (Ex. +639178851234).</inlineHelpText>
        <label>Primary Mobile</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Office__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Office</label>
        <referenceTo>Office__c</referenceTo>
        <relationshipLabel>Executing Personnels</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Address_Province__c</fullName>
        <description>Service address province</description>
        <inlineHelpText>Service address province</inlineHelpText>
        <label>Service Address Province</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Metro Manila</fullName>
                    <default>true</default>
                    <label>Metro Manila</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Tax_Identification_No__c</fullName>
        <label>Tax Identification Number</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Address__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Billing_Preferences</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Address_Street_No__c</fullName>
        <label>Street #</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address__c</fullName>
        <formula>Address_Unit_No__c &amp; &quot; &quot; &amp;  Address_Street_No__c &amp; &quot; &quot; &amp; Address_Street_Name__r.Name &amp; &quot;, &quot; &amp; Address_Subdivision__r.Name &amp; &quot; &quot; &amp;  Address_Barangay__r.Name &amp; &quot;, &quot; &amp; Address_City_Municipality__r.Name &amp; &quot;, &quot; &amp;  Address_Province__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Address</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipName>Billing_Preferences</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipName>Billing_Preferences</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Service</fullName>
                </value>
                <value>
                    <fullName>Billing</fullName>
                </value>
                <value>
                    <fullName>Customer</fullName>
                </value>
                <value>
                    <fullName>Meter</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Address</label>
    <nameField>
        <displayFormat>ADD-{000000}</displayFormat>
        <label>Address Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Agreement__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Agreements</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipName>Agreements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contract__c</fullName>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipName>Agreements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PSIC__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>PSIC</label>
        <referenceTo>PSIC__c</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Payor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Payor Contract of this Service</description>
        <label>Payor</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Services (Payor)</relationshipLabel>
        <relationshipName>Services_Payor</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SIN__c</fullName>
        <externalId>true</externalId>
        <label>SIN</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>V10_Account_No__c</fullName>
        <label>V10 Account #</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Service</label>
    <nameField>
        <displayFormat>SERV-{00000000}</displayFormat>
        <label>Service ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>CXE_isPortalContact__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isPortalContact</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Account_No__c</fullName>
        <formula>Account.Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Salesforce Account ID of the Account related to Contract</inlineHelpText>
        <label>Account #</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Regular</fullName>
                </value>
                <value>
                    <fullName>Prepaid</fullName>
                </value>
                <value>
                    <fullName>SOLR</fullName>
                </value>
                <value>
                    <fullName>Retailer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>V10_Account_No__c</fullName>
        <externalId>true</externalId>
        <label>Legacy Account Number</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Reference__c.object
<CustomObject>
    <description>This contain Address, Geo Code, Picklist Value, Picklist Code</description>
    <fields>
        <fullName>Field__c</fullName>
        <externalId>true</externalId>
        <label>Field</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Geo</fullName>
                </value>
                <value>
                    <fullName>Picklist</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Reference</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>References</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CXE_ServiceApplication_Test.cls
@isTest
private Class CXE_ServiceApplication_Test{
    @testSetup
    static void createTestReqs(){
        
        User adminUser = CXE_TestDataFactory.createAdminUser();
        insert adminUser;
        
		User  userSysAd =[SELECT ID FROM USER WHERE EMAIL ='bruce.wayne@wayneenterprises.com' ];
        System.runAs ( userSysAd ) {
            Account account1 = new Account(
                Name = 'TestAccount',
                OwnerId = userSysAd.Id,
                Phone = '+63021234567',
                Tax_Identification_No__c = '123456789012',
                Mobile_Phone__c = '+630000000000',
                Email__c = 'test@test.com'
            );
            Database.insert(account1);
            
            Contact contact1 = new Contact(
                FirstName = 'Test',
                Lastname = 'McTesty',
                AccountId = account1.Id,
                Email = System.now().millisecond() + 'test@test.com',
                CXE_isPortalContact__c =False
            );
            Database.insert(contact1);
            
            //CREATE PORTAL USER ACCOUNT
            Profile portalProfile = [SELECT Id FROM Profile Limit 1];
            User pAccountPortalUser = new User(
                Username = System.now().millisecond() + 'test12345@test.com',
                ContactId = contact1.Id,
                ProfileId = portalProfile.Id,
                Alias = 'test123',
                Email = 'test12345@test.com',
                EmailEncodingKey = 'UTF-8',
                LastName = 'McTesty',
                CommunityNickname = 'test12345',
                TimeZoneSidKey = 'America/Los_Angeles',
                LocaleSidKey = 'en_US',
                LanguageLocaleKey = 'en_US'
            );
            Database.insert(pAccountPortalUser);
        }
    }
    @isTest
    static void MethodTest(){
        Test.startTest();
        CXE_ServiceApplication.getServiceModifications();
        CXE_ServiceApplication.getContractModifications();
        CXE_ServiceApplication.newPortalCase();
        CXE_ServiceApplication.getPersona();
        Case inistNewCase = CXE_ServiceApplication.initNewCase();
        Test.stopTest();
    }
    
    @isTest
    static void createPortalUser(){
        
        UserRole portalRole = [Select Id From UserRole Where PortalType = 'None' Limit 1];
        system.debug('portalRole is ' + portalRole);
        
        Profile profile1 = [Select Id from Profile where name = 'System Administrator'];
        User portalAccountOwner1 = new User(
            UserRoleId = portalRole.Id,
            ProfileId = profile1.Id,
            Username = System.now().millisecond() + 'test2@test.com',
            Alias = 'batman',
            Email='bruce.wayne@wayneenterprises.com',
            EmailEncodingKey='UTF-8',
            Firstname='Bruce',
            Lastname='Wayne',
            LanguageLocaleKey='en_US',
            LocaleSidKey='en_US',
            TimeZoneSidKey='America/Chicago'
            
        );
        Database.insert(portalAccountOwner1);
        
    }
   
    @isTest
    static void SubmitServiceApplication(){
       
		//CREATE ACCOUNT
        List<Account> testAccountList = CXE_TestDataFactory.createBusinessAccount(1);
        Account testAccount = testAccountList.get(0);
        insert testAccount;
        
        //CREATE CONTACT
        List<Contact> testContact = CXE_TestDataFactory.createContact(1);
        insert testContact;
        
        //CREATE PSIC
        List<PSIC__c> testPsic = CXE_TestDataFactory.createPSIC(1);
        insert testPsic;
        
        //CREATE CASE CASE_SERVICE_APPLICATION
       	List<Case> CaseList = new List<Case>();
        Id newServiceApplicationRecordTypeId1 = Schema.Sobjecttype.Case.getRecordTypeInfosByName().get(CXE_Constants.CASE_NEW_SERVICE_APPLICATION).getRecordTypeId();
        Id newServiceApplicationRecordTypeId2 = Schema.Sobjecttype.Case.getRecordTypeInfosByName().get(CXE_Constants.CASE_PAPERLESS_BILLING).getRecordTypeId();
        List<Case> testCaseList = CXE_TestDataFactory.createCase(1, 'New Electric Service,', 'Single Meter', 'Application Received', 'Private');
     	Case testCase = testCaseList.get(0);
        testCase.RecordTypeId = newServiceApplicationRecordTypeId1;  
        testCase.Tax_Identification_No__c = '1111111';
        testCase.AccountId = testAccount.Id;
        testCase.Relationship__c = '--- None ---';
        testCase.Service_Address_Province__c = '--- None ---';
        testCase.Service_Address_City_Municiple__c = '--- None ---';
        testCase.Billing_Address_Province__c = '--- None ---';
        testCase.Billing_Address_City_Municipal__c = '--- None ---';
     	CaseList.add(testCase);
        
        Case testCase1 = new Case();
        testCase1.RecordTypeId = newServiceApplicationRecordTypeId2;  
        testCase.Tax_Identification_No__c = '1111111';
        testCase1.AccountId = testAccount.Id;
        testCase1.Account_No__c = '123456789123';
        testCase1.Relationship__c = '--- None ---';
        CaseList.add(testCase1);
        
        Case testCase2 = new Case();
        testCase2.RecordTypeId = newServiceApplicationRecordTypeId2;  
        testCase2.Tax_Identification_No__c = '1111111';
        testCase2.AccountId = testAccount.Id;
        testCase2.Relationship__c = '--- None ---';
       	insert testCase2;
        
        String myJSON = JSON.serialize(CaseList.get(0));
        String myJSON1 = JSON.serialize(CaseList.get(1));
        String myJSON2 = JSON.serialize(testCase2);
    	//get recordType
        RecordType recType = [SELECT Id, DeveloperName FROM RecordType WHERE id =:newServiceApplicationRecordTypeId1];
        RecordType recType1 = [SELECT Id, DeveloperName FROM RecordType WHERE id =:newServiceApplicationRecordTypeId2];
        //CREATE CONTRACT       
        List<Contract> testContract = CXE_TestDataFactory.createContract(1, testAccount.Id, testCase2.Id);
        testContract[0].V10_Account_No__c = '12345678';
        testContract[0].Type__c = 'Regular';
        insert testContract;
        
        //CREATE ADDRESS
        Address__c testAddress = new Address__c(Type__c = 'Billing', Account__c = testAccount.Id, Contract__c = testContract[0].Id, Case__c = testCase2.Id,  Address_Street_No__c = '1');
        insert testAddress;
        
        //CREATE SERVICE
        List<Agreement__c> service = CXE_TestDataFactory.createService(1,testAccount.Id, testCase2.Id, testContract[0].Id, testPsic[0].Id);
        service[0].Payor__c= testContract[0].Id;
        service[0].SIN__c = '123456789123';
        insert service;
        
        List<Agreement__c> service1 = CXE_TestDataFactory.createService(1,testAccount.Id, testCase2.Id, testContract[0].Id, testPsic[0].Id);
        service1[0].Payor__c= testContract[0].Id;
        service1[0].SIN__c = '5352345';
        insert service1;
            
        test.startTest();    
        User  userPortalUser =[SELECT Id FROM USER WHERE EMAIL ='test12345@test.com'];
        System.runAs(userPortalUser){

        try{
            CXE_CP_PortalUtility.getCurrentUserContacId();     
            
            CXE_ServiceApplication.submitServiceApplication(myJSON, recType.DeveloperName);
            CXE_ServiceApplication.submitServiceApplication(myJSON1, recType1.DeveloperName);
            CXE_ServiceApplication.submitServiceApplication(myJSON2, recType1.DeveloperName);
            test.stopTest();
        }
        catch(Exception e){
            System.assertEquals(null, e.getMessage());
	        }
        }
    }
   
    @isTest
    static void trackApplication(){
        List<Account> testAccountList = CXE_TestDataFactory.createBusinessAccount(1);
        Account testAccount = testAccountList.get(0);
        insert testAccount;
        
        //CREATE CONTACT
        List<Contact> testContact = CXE_TestDataFactory.createContact(1);
        insert testContact;
        
        //CREATE PSIC
        List<PSIC__c> testPsic = CXE_TestDataFactory.createPSIC(1);
        insert testPsic;
        
        //CREATE CASE CASE_SERVICE_APPLICATION
       
        Id newServiceApplicationRecordTypeId = Schema.Sobjecttype.Case.getRecordTypeInfosByName().get(CXE_Constants.CASE_NEW_SERVICE_APPLICATION).getRecordTypeId();
        List<Case> testCaseList = CXE_TestDataFactory.createCase(1, 'New Electric Service,', 'Single Meter', 'Application Received', 'Private');
     	Case testCase = testCaseList.get(0);
        testCase.RecordTypeId = newServiceApplicationRecordTypeId;  
        testCase.Tax_Identification_No__c = '1111111';
        testCase.AccountId = testAccount.Id;
        testCase.Last_Name__c = 'LastName';
        insert testCase;    
        List<Case> checkCase = [select id, CaseNumber, Last_Name__c from Case];
       
        test.startTest();    
        
        CXE_ServiceApplication.trackApplication(checkCase[0].CaseNumber, checkCase[0].Last_Name__c);
        CXE_ServiceApplication.trackApplication(null, null);
        
        test.stopTest();
    }
    
    @isTest
    static void getRelationToCustomer(){
        test.startTest();    
        CXE_ServiceApplication.getRelationToCustomer('Contractor');
         CXE_ServiceApplication.getRelationToCustomer('Spouse');
        test.stopTest();
    }
    
     @isTest
    static void getInitialResponsibleOffice(){
        //CREATE ACCOUNT
        List<Account> testAccountList = CXE_TestDataFactory.createBusinessAccount(1);
        Account testAccount = testAccountList.get(0);
        insert testAccount;
        
        //CREATE CONTACT
        List<Contact> testContact = CXE_TestDataFactory.createContact(1);
        insert testContact;
        
         //CREATE CASE CASE_SERVICE_APPLICATION
       	List<Case> CaseList = new List<Case>();
        Id newServiceApplicationRecordTypeId1 = Schema.Sobjecttype.Case.getRecordTypeInfosByName().get(CXE_Constants.CASE_NEW_SERVICE_APPLICATION).getRecordTypeId();
        Id newServiceApplicationRecordTypeId2 = Schema.Sobjecttype.Case.getRecordTypeInfosByName().get(CXE_Constants.CASE_PAPERLESS_BILLING).getRecordTypeId();
        List<Case> testCaseList = CXE_TestDataFactory.createCase(1, 'New Electric Service,', 'Single Meter', 'Application Received', 'Private');
     	Case testCase = testCaseList.get(0);
        testCase.RecordTypeId = newServiceApplicationRecordTypeId1;  
        testCase.Tax_Identification_No__c = '1111111';
        testCase.AccountId = testAccount.Id;
        testCase.Relationship__c = '--- None ---';
        testCase.Service_Address_City_Municiple__c = 'Bacoor';
     	//insert testCase;
        
        String myJSON = JSON.serialize(testCase);
        
         //Create Reference
        List<Reference__c> reference = CXE_TestDataFactory.createSampleReferenceListForAddress();
        reference[0].Name='Bacoor';
        reference[0].Field__c = 'City';
        insert reference;
        //Create Office
        List<Office__c> office = CXE_TestDataFactory.createOffice(1);
        insert office;
        
        //get recordType
        RecordType recType = [SELECT Id, DeveloperName FROM RecordType WHERE id =:newServiceApplicationRecordTypeId1];
        CXE_ServiceApplication.submitServiceApplication(myJSON, recType.DeveloperName);
    }
    
    
}