src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Conglomerate__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Conglomerate</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>CXE_Auto_Enrolled_Services__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This checkbox indicates if there are related services auto enrolled when the user registers on the portal using a SIN related to other services under one account.</description>
        <label>Auto Enrolled Services</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/CXE_CP_ConglomerateDashboardCtlr.cls
public without sharing class CXE_CP_ConglomerateDashboardCtlr {
    //10-12-17 for conglomerate -SHAYNE 

    @AuraEnabled
    public static String getAccountIDofCurrentUser(){
        String ret = null;
        System.debug('CXE_CP_ConglomerateDashboardCtlr getAccountIDofCurrentUser START');
       	User userData = [SELECT LastLoginDate,FirstName,CXE_Auto_Enrolled_Services__c, AccountId, Account.Conglomerate__c, Account.Name
                                                    FROM User WHERE Id =:UserInfo.getUserId()];
       
        System.debug('getAccountIDofCurrentUser: UserId '+UserInfo.getUserId()+' :AccountId '+userData.AccountId+' :Conglomerate__c '+userData.Account.Conglomerate__c);
        if(userData.Account.Conglomerate__c) ret = userData.AccountId;
        return ret; 
    }
    
    //START R2C CSM-14832 Shayne 12/07/2017
    @AuraEnabled
    public static String getProfInfoModal(){
        return CXE_CP_Dashboard.getProfInfoModal();
    }
    //END R2C CSM-14832 Shayne 12/07/2017
    
}