src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Tax_Identification_No__c</fullName>
        <label>Tax Identification Number</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Address__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Billing_Preferences</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Address_Street_No__c</fullName>
        <label>Street #</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address__c</fullName>
        <formula>Address_Unit_No__c &amp; &quot; &quot; &amp;  Address_Street_No__c &amp; &quot; &quot; &amp; Address_Street_Name__r.Name &amp; &quot;, &quot; &amp; Address_Subdivision__r.Name &amp; &quot; &quot; &amp;  Address_Barangay__r.Name &amp; &quot;, &quot; &amp; Address_City_Municipality__r.Name &amp; &quot;, &quot; &amp;  Address_Province__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Address</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipName>Billing_Preferences</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipName>Billing_Preferences</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Service</fullName>
                </value>
                <value>
                    <fullName>Billing</fullName>
                </value>
                <value>
                    <fullName>Customer</fullName>
                </value>
                <value>
                    <fullName>Meter</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Address</label>
    <nameField>
        <displayFormat>ADD-{000000}</displayFormat>
        <label>Address Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Agreement__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Agreements</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Active_Agreement__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Active Agreement</description>
        <label>Active Agreement</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Advance_Frequency_months__c</fullName>
        <description>Advanced frequency</description>
        <label>Advance Frequency (months)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Advance_amount__c</fullName>
        <description>Current advanced amount</description>
        <label>Advance Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Agreement_Duration_Months__c</fullName>
        <defaultValue>36</defaultValue>
        <label>Agreement Term (months)</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Agreement_End_Date__c</fullName>
        <description>Agreement End Date</description>
        <inlineHelpText>End Date of the agreement</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Agreement_Start_Date__c</fullName>
        <description>Agreement Start Date</description>
        <inlineHelpText>Start Date of the agreement</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipName>Agreements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Charges_for_breach_of_contract__c</fullName>
        <formula>Commercial_Product__r.Charges_for_breach_of_contract__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Charges for Breach of Contract</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Commercial_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Commercial Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipName>Agreements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contract__c</fullName>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipName>Agreements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Service</label>
    <nameField>
        <displayFormat>SERV-{00000000}</displayFormat>
        <label>Service ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Advance_amount__c</fullName>
        <label>Advance amount</label>
        <summarizedField>Agreement__c.Advance_amount__c</summarizedField>
        <summaryFilterItems>
            <field>Agreement__c.Active_Agreement__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryForeignKey>Agreement__c.Contract__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Method_of_Payment__c</fullName>
        <label>Method of Payment</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ADA (Bank)</fullName>
                </value>
                <value>
                    <fullName>ADA (Credit Card)</fullName>
                </value>
                <value>
                    <fullName>Over the Counter</fullName>
                </value>
                <value>
                    <fullName>Company Expenses</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Regular</fullName>
                </value>
                <value>
                    <fullName>Prepaid</fullName>
                </value>
                <value>
                    <fullName>SOLR</fullName>
                </value>
                <value>
                    <fullName>Retailer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Case.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Method_of_Payment__c</fullName>
        <label>Method of Payment</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cash</fullName>
                </value>
                <value>
                    <fullName>Cheque</fullName>
                    <default>true</default>
                    <label>Cheque</label>
                </value>
                <value>
                    <fullName>Credit card</fullName>
                </value>
                <value>
                    <fullName>Direct Debit</fullName>
                </value>
                <value>
                    <fullName>Transfer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Charges_for_breach_of_contract__c</fullName>
        <label>Charges for Breach of Contract</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
</CustomObject>

src/classes/MovingHomeControllerTest.cls
/**
  * @author       : Sanchayeeta
  * @date         : 05/11/2015
  * @description  : Test Class for MovingHomeController class 
  */  
@isTest
//(SeeallData=true)
public class MovingHomeControllerTest{
     
    //private static testMethod void TestMet(){
      /*      
        //inserting Account
        //Account acc=new Account();
        List<Account> testAccountList = CXE_TestDataFactory.createBusinessAccount(1);
        Account acc = testAccountList.get(0);
        //acc.LastName = 'SanTestSan';
        acc.Phone = '55555555';
        insert acc;
        
        //RecordType rtype = [SELECT id FROM RecordType WHERE sObjectType='Case' and isActive=true AND Recordtype.Developername='Handle_a_Contract_Termination'];
        //Inserting Case Record
        List<Case> testCaseList = CXE_TestDataFactory.createCase(1, 'New Electric Service,', 'Single Meter', 'Application Received', 'Private');
        Case caseTest = testCaseList.get(0);
        //Case caseTest=new Case();
        //caseTest.RecordtypeId=rtype.Id;
        caseTest.Origin='Phone';
        caseTest.NEW_Bank_Name__c = 'Yes Bank';
        caseTest.NEW_Terms_of_Payment__c ='30d end of month';
        caseTest.New_Payment_Day__c='1st of month';
        caseTest.NEW_IBAN__c ='Test';
        caseTest.Subject='Test Subject';
        caseTest.AccountId=acc.Id;
        insert caseTest;
        
    
    
    // inserting opportunity
    Opportunity opp=TestDataFactoryTest.createOpportunity();
    
    
          // inserting contract
    Contract contract = new Contract ();
    contract.Case__c = caseTest.Id;
    contract.Method_of_Payment__c = 'ADA (Bank)';
    contract.Type__c = 'Regular';
    contract.Accountid = acc.id;
    contract.Name= 'TestContract';
    insert contract;


        Address__c testAddress = CXE_TestDataFactory.createAddressWithoutReference('Billing', caseTest.Id, acc.Id, contract.Id, null, null, null);
        insert testAddress;
        
    //Query Product
    //Product2 prod = [select id from Product2 where isActive = true limit 1];
        
        //inserting Agreement
        agreement__C agreemt= new agreement__C();
        agreemt.Account__c = acc.id;
        //agreemt.name ='TestAgree';
        //agreemt.Commercial_Product__c = prod.id;
        agreemt.Contract__c = contract.id;
        agreemt.Agreement_Duration_Months__c=36;
        agreemt.Agreement_Start_Date__c = System.today();
        agreemt.Agreement_End_Date__c = System.today()+1;
        agreemt.Advance_Frequency_months__c=20;
        agreemt.Advance_amount__c =100;
        agreemt.Case__c =caseTest.id;
        agreemt.Active_Agreement__c=true;
        //agreemt.Charges_for_breach_of_contract__c=400;
        insert agreemt;
     */

    // List<Account> testAccountList = CXE_TestDataFactory.createBusinessAccount(1);
    //    Account testAccount = testAccountList.get(0);
    //    insert testAccount;

    //    Id newServiceApplicationRecordTypeId = Schema.Sobjecttype.Case.getRecordTypeInfosByName().get(CXE_Constants.CASE_NEW_SERVICE_APPLICATION).getRecordTypeId();

    //    List<Case> testCaseList = CXE_TestDataFactory.createCase(1, 'New Electric Service,', 'Single Meter', 'Application Received', 'Private');
    //    Case caseTest = testCaseList.get(0);
    //    caseTest.RecordTypeId = newServiceApplicationRecordTypeId;
    //    caseTest.Tax_Identification_No__c = '1111111';
    //    caseTest.AccountId = testAccount.Id;
    //    insert caseTest;

    //    Contract testContract = new Contract(AccountId = testAccount.Id,
    //                                         Case__c = caseTest.Id,
    //                                         Method_of_Payment__c = 'ADA (Bank)',
    //                                         Type__c = 'Regular');
    //    insert testContract;
                                               
    //    Address__c testAddress = new Address__c(Type__c = 'Billing', 
    //                                            Account__c = testAccount.Id,
    //                                            Case__c = caseTest.Id,
    //                                            Contract__c = testContract.Id,
    //                                            Address_Street_No__c = '1');
    //    insert testAddress;

    //    List<Agreement__c> serviceList = CXE_TestDataFactory.createService(1, null,null,testContract.Id, null);
    //    Agreement__c agreemt = serviceList.get(0);
    //    insert agreemt;   
        
      
        
    //   system.Test.startTest();
    //System.Test.setCurrentPageReference(new PageReference('Page.MovingHomePage'));
    ////System.currentPageReference().getParameters().put('caseid', caseTest.id);                
    //    ApexPages.StandardController sc = new ApexPages.StandardController(caseTest);
    //    MovingHomeController oMoveHome= new MovingHomeController(sc);
    //    //PageReference pageRef = Page.MoveHomeOpportunity;       
    //    oMoveHome.ThisCase = caseTest;
    //    //MovingHomeController.AgreementWrapper agWrap = new MovingHomeController.AgreementWrapper();
    //    //agWrap.agreement = agreemt;
    //    //agWrap.Sel = true;
    //    //oMoveHome.agreementWrap.add(agWrap);
    //    List<MovingHomeController.AgreementWrapper> lstAgWrap = new List<MovingHomeController.AgreementWrapper>();
    //    for(MovingHomeController.AgreementWrapper agw : oMoveHome.agreementWrap){
    //        if(agw.Sel == null){
    //            agw.Sel  = false;
    //        }
    //        lstAgWrap.add(agw);
    //    }
    //    oMoveHome.agreementWrap = lstAgWrap;
    //    //system.assertEquals(null,oMoveHome.agreementWrap);
        
    //    oMoveHome.save();
        
    //    oMoveHome.updategraph();
    //    oMoveHome.meterReadsAsGoogleChartsJson(testAccount.id);
    //    oMoveHome.cancel();
        
    //    MovingHomeController.Prevmeterresponse oPrev = new MovingHomeController.Prevmeterresponse();
    //    oPrev.ReadingDateTime1= 'Test';
    //    oPrev.ReadingDateTime2 =System.today();
    //    oPrev.ReadingOrigin1 = 'Test';
    //    oPrev.UsageCode1 = 'Test';
    //    oPrev.Value1 =2.0;
    //    oPrev.utiltarriflabel1 = 'Test';
    //    oPrev.unitofmeasure1 = 'Test';
    //    //oPrev.compareTo(caseTest);
    //    MovingHomeController.MeterRead oMtrRrd = new MovingHomeController.MeterRead(System.today(),8.0);
    //    oMtrRrd.meterReadDate= System.today();
    //    oMtrRrd.meterReadValue = 2.0;
    //    List<MovingHomeController.Prevmeterresponse> oPrevlist=new List<MovingHomeController.Prevmeterresponse>();
    //    oPrevlist.add(oPrev);
    //    oMoveHome.resp= oPrevlist;
    //    oMoveHome.fetchmeterreads();
    //    system.Test.stopTest();
           
    
    //}
   
}