src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Primary Email</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Office__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Office</label>
        <referenceTo>Office__c</referenceTo>
        <relationshipLabel>Executing Personnels</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Address__c.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipName>Billing_Preferences</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Address</label>
    <nameField>
        <displayFormat>ADD-{000000}</displayFormat>
        <label>Address Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Field_Order__c.object
<CustomObject>
    <fields>
        <fullName>Account_Name__c</fullName>
        <formula>IF(Case__r.Application_for_Business_Customer__c = TRUE, Case__r.Account.Name, Case__r.First_Name__c + &quot; &quot; +  Case__r.Middle_Name__c + &quot; &quot; +  Case__r.Last_Name__c)</formula>
        <label>Account Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Field Orders</relationshipLabel>
        <relationshipName>Field_Orders</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Contact_Name__c</fullName>
        <formula>Case__r.First_Name__c + &quot; &quot; +  Case__r.Middle_Name__c + &quot; &quot; +  Case__r.Last_Name__c</formula>
        <label>Contact Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <formula>Case__r.Email_Address__c</formula>
        <label>Primary Email</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Executing_Personnel_FO__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Executing Personnel</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Office__c</field>
                <operation>equals</operation>
                <valueField>$Source.Office__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Field Orders</relationshipLabel>
        <relationshipName>Field_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Inspection_Instructions__c</fullName>
        <description>Instructions for inspection</description>
        <inlineHelpText>Instructions for inspection</inlineHelpText>
        <label>Inspection Instructions</label>
        <length>300</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Inspection_Result__c</fullName>
        <description>Result of inspection</description>
        <inlineHelpText>Result of inspection</inlineHelpText>
        <label>Inspection Result</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Disapproved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Material__c</fullName>
        <label>Service Wire Material</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Aluminum</fullName>
                </value>
                <value>
                    <fullName>Copper</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Metering_Scheme__c</fullName>
        <label>Metering Scheme</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>NORMAL</fullName>
                </value>
                <value>
                    <fullName>EMC</fullName>
                </value>
                <value>
                    <fullName>MULTI-METERING CENTER</fullName>
                </value>
                <value>
                    <fullName>ICP</fullName>
                </value>
                <value>
                    <fullName>MULTI-METERING PER FLOOR</fullName>
                </value>
                <value>
                    <fullName>SUBSTATION</fullName>
                </value>
                <value>
                    <fullName>PRIMARY METERING</fullName>
                </value>
                <value>
                    <fullName>20 KV</fullName>
                </value>
                <value>
                    <fullName>AMI-NORMAL</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Mobile_No__c</fullName>
        <formula>Case__r.Mobile_No__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Primary Mobile</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mode_of_Retrieval__c</fullName>
        <label>Mode of Retrieval</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>REMOTE</fullName>
                </value>
                <value>
                    <fullName>ONSITE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Office__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Office</label>
        <referenceTo>Office__c</referenceTo>
        <relationshipLabel>Field Orders</relationshipLabel>
        <relationshipName>Field_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Pole_Code__c</fullName>
        <label>Service Wire Pole #</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Resolution_Date__c</fullName>
        <description>Date when pre-survey is resolved</description>
        <inlineHelpText>Date when pre-survey is resolved</inlineHelpText>
        <label>Resolution Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Resolution_Remarks__c</fullName>
        <description>Resolution remark</description>
        <inlineHelpText>Resolution remark</inlineHelpText>
        <label>Resolution Remarks</label>
        <length>300</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Schedule_Date__c</fullName>
        <label>Schedule Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Service_Wire_Length__c</fullName>
        <label>Service Wire Length</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Service_Wire_Size__c</fullName>
        <label>Service Wire Size</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>#1/0</fullName>
                </value>
                <value>
                    <fullName>#2</fullName>
                </value>
                <value>
                    <fullName>#3/0</fullName>
                </value>
                <value>
                    <fullName>#4</fullName>
                </value>
                <value>
                    <fullName>#4/0</fullName>
                </value>
                <value>
                    <fullName>#6</fullName>
                </value>
                <value>
                    <fullName>#8</fullName>
                </value>
                <value>
                    <fullName>1000 MCM</fullName>
                </value>
                <value>
                    <fullName>500 MCM</fullName>
                </value>
                <value>
                    <fullName>500 MCM &amp; #4/0</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Service_Wire_Type__c</fullName>
        <label>Service Wire Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Aerial Alum.,Bundled</fullName>
                </value>
                <value>
                    <fullName>Aerial Alum.,Open</fullName>
                </value>
                <value>
                    <fullName>Aerial CU.,Bundled</fullName>
                </value>
                <value>
                    <fullName>Aerial Coppen,Open</fullName>
                </value>
                <value>
                    <fullName>Under Alum.,Lateral</fullName>
                </value>
                <value>
                    <fullName>Under Copper,Lateral</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Generated</fullName>
                    <default>true</default>
                    <label>Generated</label>
                </value>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>In Execution</fullName>
                </value>
                <value>
                    <fullName>Executed</fullName>
                </value>
                <value>
                    <fullName>Not Required</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TLN__c</fullName>
        <label>Service Wire TLN</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Telephone_No__c</fullName>
        <formula>Case__r.Telephone_No__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Primary Telephone</label>
        <type>Text</type>
    </fields>
    <label>Field Order</label>
    <nameField>
        <displayFormat>FO-{00000000}</displayFormat>
        <label>Field Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Field Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Office__c</fullName>
        <description>Office which Meralco employee is attached to</description>
        <inlineHelpText>Office which Meralco employee is attached to</inlineHelpText>
        <label>Office</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>BIZ - Alabang + Cavite + Taguig Zone</fullName>
                </value>
                <value>
                    <fullName>BIZ - Bulacan + Camanava Zone</fullName>
                </value>
                <value>
                    <fullName>BIZ - Laguna + Batangas + Quezon Zone</fullName>
                </value>
                <value>
                    <fullName>BIZ - Makati + Pasig + Rizal Zone</fullName>
                </value>
                <value>
                    <fullName>BIZ - Pasay + Manda + Manila Zone</fullName>
                </value>
                <value>
                    <fullName>BIZ - Quezon City Zone</fullName>
                </value>
                <value>
                    <fullName>Bulacan-Caloocan-Malabon-Navotas-Valenzuela Zone</fullName>
                </value>
                <value>
                    <fullName>CBG - East TS Team</fullName>
                </value>
                <value>
                    <fullName>CBG - North TS Team</fullName>
                </value>
                <value>
                    <fullName>CBG - South TS Team</fullName>
                </value>
                <value>
                    <fullName>CBG - West TS Team</fullName>
                </value>
                <value>
                    <fullName>East Technical Services Team</fullName>
                </value>
                <value>
                    <fullName>HMB - Alabang BC (CC)</fullName>
                </value>
                <value>
                    <fullName>HMB - Angono BC (CC)</fullName>
                </value>
                <value>
                    <fullName>HMB - Bacoor BC (CC)</fullName>
                </value>
                <value>
                    <fullName>HMB - Balagtas BC (CC)</fullName>
                </value>
                <value>
                    <fullName>HMB - Balintawak BC (CC)</fullName>
                </value>
                <value>
                    <fullName>HMB - Baliwag BC (CC)</fullName>
                </value>
                <value>
                    <fullName>HMB - Batangas BC (CC)</fullName>
                </value>
                <value>
                    <fullName>HMB - Cainta BC (CC)</fullName>
                </value>
                <value>
                    <fullName>HMB - Calamba BC (CC)</fullName>
                </value>
                <value>
                    <fullName>HMB - Camarin AUX (CC)</fullName>
                </value>
                <value>
                    <fullName>HMB - Commonwealth BC (CC)</fullName>
                </value>
                <value>
                    <fullName>HMB - Dasmariñas BC (CC)</fullName>
                </value>
                <value>
                    <fullName>HMB - España BC (CC)</fullName>
                </value>
                <value>
                    <fullName>HMB - Kalookan AUX (CC)</fullName>
                </value>
                <value>
                    <fullName>HMB - Kamuning BC (CC)</fullName>
                </value>
                <value>
                    <fullName>HMB - Las Piñas BC (CC)</fullName>
                </value>
                <value>
                    <fullName>HMB - Lucena BC (CC)</fullName>
                </value>
                <value>
                    <fullName>HMB - Makati BC (CC)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/CXE_FOListView_CC.cls
public class CXE_FOListView_CC {
    public class Response {
        @AuraEnabled
        public String message;

        @AuraEnabled
        public String status;

        @AuraEnabled
        public List<FieldOrder> fieldOrderList;

        public Response(){
            this.message = '';
            this.status = 'SUCCESS';
            this.fieldOrderList = new List<FieldOrder>();
        }
    }

    public class FieldOrder {
        @AuraEnabled
        public Boolean isCheck;
        @AuraEnabled
        public Id fieldOrderId;
        @AuraEnabled
        public String fieldOrderName;
        @AuraEnabled
        public String caseId;
        @AuraEnabled
        public String caseNumber;
        @AuraEnabled
        public Date scheduleDate;
        @AuraEnabled
        public String status;
        @AuraEnabled
        public String address;
        @AuraEnabled
        public String landmark;
        @AuraEnabled
        public Date createdDate;
        @AuraEnabled
        public String recordTypeName;
        @AuraEnabled
        public List<FieldValues> fieldValues;
    }
    
    public class FieldValues {
        @AuraEnabled
        public String fieldName;
        @AuraEnabled
        public String fieldValue;
        @AuraEnabled
        public String section;
    }

    @AuraEnabled
    public static Response getFieldOrders(){        
        User currentUser;        
        FieldOrder fieldOrderTemp;
        Response res = new Response();
        Set<String> validRecordTypeSet;
        Set<String> validStatusSet = new Set<String>();     
        List<Field_Order__c> fieldOrderList = new List<Field_Order__c>();

        Map<String, List<String>> fieldsInspectionFOLayout = new Map<String, List<String>>{
            'Inspection'=>new List<String>{'Case__r.CaseNumber', 'Telephone_No__c', 'Status__c', 'Account_Name__c', 'Mobile_No__c', 'CreatedDate', 'Contact_Name__c', 'Email__c', 'Schedule_Date__c', 'Office__r.Name', 'Executing_Personnel_FO__c', 'Resolution_Date__c'}, 
                    'Instructions/Remarks' => new List<String>{'Inspection_Instructions__c'}, 
                        'Additional Information'=> new List<String>{'TLN__c', 'Pole_Code__c', 'Material__c', 'Metering_Scheme__c', 'Mode_of_Retrieval__c', 'Service_Wire_Size__c', 'Service_Wire_Length__c', 'Service_Wire_Type__c'}, 
                            'Resolution Details' => new List<String>{'Resolution_Remarks__c', 'Inspection_Result__c', 'Ready_for_Connection__c', 'SE_Not_Compliant__c', 'SE_Not_Installed_Yet__c', 'Wrong_SE_Location__c'}
        };
        Map<String, List<String>> fieldsMeterSocketFOLayout = new Map<String, List<String>>{
            'Meter Socket Delivery'=>new List<String>{'Case__r.CaseNumber', 'Telephone_No__c', 'Status__c', 'Account_Name__c', 'Mobile_No__c', 'CreatedDate', 'Contact_Name__c', 'Email__c', 'Schedule_Date__c', 'Office__r.Name', 'Executing_Personnel_FO__c', 'Resolution_Date__c'}, 
                'Instructions/Remarks' => new List<String>{'Meter_Socket_Delivery_Instructions__c'}, 
                    'Resolution Details' => new List<String>{'Resolution_Remarks__c', 'Meter_Socket_Delivery__c', 'SE_Completion_Target_Negotiated__c', 'Delivery_for_Reschedule__c', 'Contact_Person_Unreachable__c', 'For_BC_Pickup__c'}
        };
        Map<String, List<String>> fieldsReInspectionFOLayout = new Map<String, List<String>>{
            'Re-Inspection'=>new List<String>{'Case__r.CaseNumber', 'Telephone_No__c', 'Status__c', 'Account_Name__c', 'Mobile_No__c', 'CreatedDate', 'Contact_Name__c', 'Email__c', 'Schedule_Date__c', 'Office__r.Name', 'Executing_Personnel_FO__c', 'Resolution_Date__c'}, 
                'Additional Information'=> new List<String>{'TLN__c', 'Pole_Code__c', 'Material__c', 'Metering_Scheme__c', 'Mode_of_Retrieval__c', 'Service_Wire_Size__c', 'Service_Wire_Length__c', 'Service_Wire_Type__c'}, 
                    'Instructions/Remarks' => new List<String>{'Re_inspection_Instructions__c', 'Resolution_Remarks__c', 'Re_Inspection_Result__c', 'Ready_for_Connection__c', 'SE_Not_Compliant__c', 'SE_Not_Installed_Yet__c', 'Wrong_SE_Location__c'}
        };
        Map<String, List<String>> fieldsSurveyFOLayout = new Map<String, List<String>>{
            'Pre-Survey'=>new List<String>{'Case__r.CaseNumber', 'Telephone_No__c', 'Status__c', 'Account_Name__c', 'Mobile_No__c', 'CreatedDate', 'Contact_Name__c', 'Email__c', 'Schedule_Date__c', 'Office__r.Name', 'Executing_Personnel_FO__c', 'Resolution_Date__c'}, 
                'Instructions/Remarks' => new List<String>{'Survey_Instructions__c', 'Pick_Up_Document__c', 'Deliver_Document__c', 'Additional_Documents_for_Evaluation_Requ__c'},
                    'Resolution Details' => new List<String>{'Resolution_Remarks__c', 'Pre_Survey_Result__c', 'Inconsistent_SA_Data_Required__c', 'ROW_Grant_for_SE_Required__c', 'Extensive_modifications_to_premises_requ__c', 'Unable_to_Locate_Given_Address__c', 'Add_Distribution_Facilities_Required__c'}
        };

        validRecordTypeSet = new Set<String>{
            'Energization FO',
            'Inspection FO',
            'Meter Socket Delivery',
            'Re-Inspection FO',
            'Survey FO'
        };

        for(String status : Label.FO_Status_Filter.trim().split(';')){
            validStatusSet.add(status.trim());
        }

        try{
            currentUser = [SELECT Id, Name, Office__c, ProfileId, Profile.Name
                           FROM User 
                           WHERE Id =: UserInfo.getUserId()];
        } catch(Exception e){
            res.status = 'FAILED';
            res.message = e.getMessage();
        }

        try{
            if(res.status != 'FAILED'){
                if(currentUser.Office__c != null){
                    fieldOrderList = [SELECT Id, Name, Case__c, Case__r.CaseNumber, Mobile_No__c, Email__c, Address__c, Landmarks__c, Status__c, Schedule_Date__c, CreatedDate, Meter_Socket_Delivery_Instructions__c,
                                      RecordType.Name, Account_Name__c, Contact_Name__c, Telephone_No__c, Resolution_Date__c, Office__r.Name, Executing_Personnel_FO__r.Name, Inspection_Instructions__c, 
                                      TLN__c, Pole_Code__c, Material__c, Metering_Scheme__c, Mode_of_Retrieval__c, Service_Wire_Size__c, Service_Wire_Length__c, Service_Wire_Type__c, Resolution_Remarks__c, 
                                      Inspection_Result__c, Ready_for_Connection__c, SE_Not_Compliant__c, SE_Not_Installed_Yet__c, Wrong_SE_Location__c, Meter_Socket_Delivery__c, SE_Completion_Target_Negotiated__c,
                                      Delivery_for_Reschedule__c, Contact_Person_Unreachable__c, For_BC_Pickup__c, Re_inspection_Instructions__c, Re_Inspection_Result__c, Survey_Instructions__c, Pick_Up_Document__c, 
                                      Deliver_Document__c, Additional_Documents_for_Evaluation_Requ__c, Pre_Survey_Result__c, Inconsistent_SA_Data_Required__c, ROW_Grant_for_SE_Required__c, Extensive_modifications_to_premises_requ__c,
                                      Unable_to_Locate_Given_Address__c, Add_Distribution_Facilities_Required__c
                                      FROM Field_Order__c
                                      WHERE Status__c IN: validStatusSet
                                        AND RecordType.Name IN: validRecordTypeSet
                                        AND Office__r.Name =: currentUser.Office__c
                                      ORDER BY Name];
                } else if(currentUser.Profile.Name.equalsIgnoreCase('System Administrator')){
                    fieldOrderList = [SELECT Id, Name, Case__c, Case__r.CaseNumber, Mobile_No__c, Email__c, Address__c, Landmarks__c, Status__c, Schedule_Date__c, CreatedDate, Meter_Socket_Delivery_Instructions__c,
                                      RecordType.Name, Account_Name__c, Contact_Name__c, Telephone_No__c, Resolution_Date__c, Office__r.Name, Executing_Personnel_FO__r.Name, Inspection_Instructions__c, 
                                      TLN__c, Pole_Code__c, Material__c, Metering_Scheme__c, Mode_of_Retrieval__c, Service_Wire_Size__c, Service_Wire_Length__c, Service_Wire_Type__c, Resolution_Remarks__c, 
                                      Inspection_Result__c, Ready_for_Connection__c, SE_Not_Compliant__c, SE_Not_Installed_Yet__c, Wrong_SE_Location__c, Meter_Socket_Delivery__c, SE_Completion_Target_Negotiated__c,
                                      Delivery_for_Reschedule__c, Contact_Person_Unreachable__c, For_BC_Pickup__c, Re_inspection_Instructions__c, Re_Inspection_Result__c, Survey_Instructions__c, Pick_Up_Document__c, 
                                      Deliver_Document__c, Additional_Documents_for_Evaluation_Requ__c, Pre_Survey_Result__c, Inconsistent_SA_Data_Required__c, ROW_Grant_for_SE_Required__c, Extensive_modifications_to_premises_requ__c,
                                      Unable_to_Locate_Given_Address__c, Add_Distribution_Facilities_Required__c
                                      FROM Field_Order__c
                                      WHERE Status__c IN: validStatusSet
                                        AND RecordType.Name IN: validRecordTypeSet
                                      ORDER BY Name];
                } else {
                    res.status = 'NO RECORDS';
                    res.message = 'No records available';
                }

                for(Field_Order__c fieldOrder : fieldOrderList){
                    fieldOrderTemp = new FieldOrder();

                    fieldOrderTemp.isCheck = false;
                    fieldOrderTemp.fieldOrderId = fieldOrder.Id;
                    fieldOrderTemp.fieldOrderName = fieldOrder.Name;
                    fieldOrderTemp.caseId = fieldOrder.Case__c;
                    fieldOrderTemp.caseNumber = fieldOrder.Case__r.CaseNumber;
                    fieldOrderTemp.scheduleDate = fieldOrder.Schedule_Date__c;
                    fieldOrderTemp.status = fieldOrder.Status__c;
                    fieldOrderTemp.createdDate = fieldOrder.CreatedDate.date();
                    fieldOrderTemp.recordTypeName = fieldOrder.RecordType.Name;
                    fieldOrderTemp.address = fieldOrder.Address__c <> null ? fieldOrder.Address__c : '';
                    fieldOrderTemp.landmark = fieldOrder.Landmarks__c <> null ? fieldOrder.Landmarks__c : '';
                    fieldOrderTemp.fieldValues = new List<FieldValues>();
                    
                    Map<String, Schema.SObjectField> fieldMap = Schema.getGlobalDescribe().get('Field_Order__c').getDescribe().fields.getMap();
                    Map<String, List<String>> fieldSets = new Map<String, List<String>>();
                    
                    if(fieldOrder.RecordType.Name == 'Inspection FO'){
                        fieldSets = fieldsInspectionFOLayout;
                    }else if(fieldOrder.RecordType.Name == 'Meter Socket Delivery'){
                        fieldSets = fieldsMeterSocketFOLayout;
                    }else if(fieldOrder.RecordType.Name == 'Re-Inspection FO'){
                        fieldSets = fieldsReInspectionFOLayout;
                    }else if(fieldOrder.RecordType.Name == 'Survey FO'){
                        fieldSets = fieldsSurveyFOLayout;
                    }
                    
                    for(String section : fieldSets.keySet()){
                        for(String fieldName: fieldSets.get(section)){
                            FieldValues fv = new FieldValues();
                            fv.section = section;
                            
                            if(fieldName.split('\\.').size() == 2){
                                String name = fieldName.split('\\.')[0].replace('__r', '__c');
                                fv.fieldName = String.valueOf(fieldMap.get(name).getDescribe().getLabel());
                            }else{
                                fv.fieldName = String.valueOf(fieldMap.get(fieldName).getDescribe().getLabel());
                            }
                            
                            if(fieldName <> 'Executing_Personnel_FO__c'){
                                if(fieldName.split('\\.').size() == 2 && fieldOrder.getSobject(fieldName.split('\\.')[0]) <> null){
                                    fv.fieldValue = fieldOrder.getSobject(fieldName.split('\\.')[0]).get(fieldName.split('\\.')[1]) <> null ? String.valueOf(fieldOrder.getSobject(fieldName.split('\\.')[0]).get(fieldName.split('\\.')[1])) : '';
                                }else if(fieldName.split('\\.').size() == 2 && fieldOrder.getSobject(fieldName.split('\\.')[0]) == null){
                                    fv.fieldValue = '';
                                }else{
                                    fv.fieldValue = fieldOrder.get(fieldName) <> null ? String.valueOf(fieldOrder.get(fieldName)) : '';
                                }
                            }else{
                                fv.fieldValue = fieldOrder.Executing_Personnel_FO__r.Name != null ? fieldOrder.Executing_Personnel_FO__r.Name : '';
                            }
                            
                            fieldOrderTemp.fieldValues.add(fv);
                        }
                    }
                    
                    res.fieldOrderList.add(fieldOrderTemp);
                }
            }
        } catch(Exception e){
            res.status = 'FAILED';
            res.message = e.getMessage() + '>>' + e.getStackTraceString();
        }

        return res;
    }
}