src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Tax_Identification_No__c</fullName>
        <label>Tax Identification Number</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Address__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Billing_Preferences</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Address_Street_No__c</fullName>
        <label>Street #</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address__c</fullName>
        <formula>Address_Unit_No__c &amp; &quot; &quot; &amp;  Address_Street_No__c &amp; &quot; &quot; &amp; Address_Street_Name__r.Name &amp; &quot;, &quot; &amp; Address_Subdivision__r.Name &amp; &quot; &quot; &amp;  Address_Barangay__r.Name &amp; &quot;, &quot; &amp; Address_City_Municipality__r.Name &amp; &quot;, &quot; &amp;  Address_Province__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Address</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipName>Billing_Preferences</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipName>Billing_Preferences</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Service</fullName>
                </value>
                <value>
                    <fullName>Billing</fullName>
                </value>
                <value>
                    <fullName>Customer</fullName>
                </value>
                <value>
                    <fullName>Meter</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Address</label>
    <nameField>
        <displayFormat>ADD-{000000}</displayFormat>
        <label>Address Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Method_of_Payment__c</fullName>
        <label>Method of Payment</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ADA (Bank)</fullName>
                </value>
                <value>
                    <fullName>ADA (Credit Card)</fullName>
                </value>
                <value>
                    <fullName>Over the Counter</fullName>
                </value>
                <value>
                    <fullName>Company Expenses</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Regular</fullName>
                </value>
                <value>
                    <fullName>Prepaid</fullName>
                </value>
                <value>
                    <fullName>SOLR</fullName>
                </value>
                <value>
                    <fullName>Retailer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/CXE_CreateContract_CC_Test.cls
/* Description: CXE_CreateContract_CC test class
 * Author: Michael Lasala
 * Date Created: MAR-10-17
 */
@isTest
 public class CXE_CreateContract_CC_Test {
    
    //Get contract picklist values
    static testMethod void picklistValuesTest(){
        
        Test.StartTest();
            Map<String, List<String>> testPicklistValues = CXE_CreateContract_CC.getContractPicklistValues();
        Test.StopTest();
        
        //-1 for actual results (--None-- value)
        System.assertEquals(Contract.Status.getDescribe().getPicklistValues().size(), testPicklistValues.get('Status').size()-1);
        System.assertEquals(Contract.Type__c.getDescribe().getPicklistValues().size(), testPicklistValues.get('Type__c').size()-1);
        System.assertEquals(Contract.Method_of_Payment__c.getDescribe().getPicklistValues().size(), testPicklistValues.get('Method_of_Payment__c').size()-1);
    }
         
    //Get case details
    static testMethod void caseTest(){
        Id newServiceApplicationRecordTypeId = Schema.Sobjecttype.Case.getRecordTypeInfosByName().get(CXE_Constants.CASE_NEW_SERVICE_APPLICATION).getRecordTypeId();

        List<Case> testCaseList = CXE_TestDataFactory.createCase(1, 'New Electric Service,', 'Single Meter', 'Application Received', 'Private');
        Case testCase = testCaseList.get(0);
        testCase.RecordTypeId = newServiceApplicationRecordTypeId;
        insert testCase;
        
        Test.StartTest();
            Case contractCase = CXE_CreateContract_CC.getCase(testCase.Id);
        Test.StopTest();

        System.assertEquals(testCase.Id, contractCase.Id);
    }
    
    //Get user details
    static testMethod void userTest(){
        String userFullName = UserInfo.getFirstName()+' '+UserInfo.getLastName();
        
        Test.StartTest();
            String contractUserFullName = CXE_CreateContract_CC.getUser();
        Test.StopTest();

        System.assertEquals(userFullName, contractUserFullName);
    }
    
    //Save contract
    /*
    static testMethod void saveTest(){
        List<Account> testAccountList = CXE_TestDataFactory.createBusinessAccount(1);
        Account testAccount = testAccountList.get(0);
        insert testAccount;
        
        Contract testContract = new Contract(AccountId = testAccount.Id,
                                             Method_of_Payment__c = 'ADA (Bank)',
                                             Type__c = 'Regular',
                                             Status = 'Draft');
        
        Test.StartTest();
            Account acc = CXE_CreateContract_CC.getAccount(testAccount.Id);
            String contract = CXE_CreateContract_CC.saveContract(testContract);
        Test.StopTest();

        System.assertEquals(testAccount.Id, acc.Id);
        System.assertEquals('Success', contract);
    }
     */
    //Save multimeter case contract
    static testMethod void saveMultimeterTest(){
        List<Account> testAccountList = CXE_TestDataFactory.createBusinessAccount(1);
        Account testAccount = testAccountList.get(0);
        insert testAccount;
        
        Id newServiceApplicationRecordTypeId = Schema.Sobjecttype.Case.getRecordTypeInfosByName().get(CXE_Constants.CASE_NEW_SERVICE_APPLICATION).getRecordTypeId();

        List<Case> testCaseList = CXE_TestDataFactory.createCase(1, 'New Electric Service,', 'Single Meter', 'Application Received', 'Private');
        Case testCase = testCaseList.get(0);
        testCase.RecordTypeId = newServiceApplicationRecordTypeId;
        testCase.Tax_Identification_No__c = '1111111';
        testCase.Multimetering__c = true;
        insert testCase;

        Contract testContract = new Contract(AccountId = testAccount.Id,
                                             Method_of_Payment__c = 'ADA (Bank)',
                                             Type__c = 'Regular', 
                                             Case__c = testCase.Id);
        
        Test.StartTest();
            String contract = CXE_CreateContract_CC.saveContract(testContract);
        Test.StopTest();

        System.assertEquals('Success', contract);
    }
    
    //relate address to contract
    static testMethod void relateBillingAddressToContractTest(){
        List<Account> testAccountList = CXE_TestDataFactory.createBusinessAccount(1);
        Account testAccount = testAccountList.get(0);
        insert testAccount;

        Id newServiceApplicationRecordTypeId = Schema.Sobjecttype.Case.getRecordTypeInfosByName().get(CXE_Constants.CASE_NEW_SERVICE_APPLICATION).getRecordTypeId();

        List<Case> testCaseList = CXE_TestDataFactory.createCase(1, 'New Electric Service,', 'Single Meter', 'Application Received', 'Private');
        Case testCase = testCaseList.get(0);
        testCase.RecordTypeId = newServiceApplicationRecordTypeId;
        testCase.Tax_Identification_No__c = '1111111';
        testCase.AccountId = testAccount.Id;
        insert testCase;

        /*Address__c testAddress = new Address__c(Type__c = 'Billing', 
                                                Account__c = testAccount.Id,
                                                Case__c = testCase.Id, 
                                                Address_Street_No__c = '1');*/
        Address__c testAddress = CXE_TestDataFactory.createAddressWithoutReference('Billing', testCase.Id, testAccount.Id, null, null, null, null); 

        insert testAddress;
        
        Contract testContract = new Contract(AccountId = testAccount.Id,
                                             Case__c = testCase.Id,
                                             Method_of_Payment__c = 'ADA (Bank)',
                                             Type__c = 'Regular');
        insert testContract;
        
        Test.StartTest();
            CXE_CreateContract_CC.relateBillingAddressToContract(testContract.Id);
            Integer addressCount = [SELECT COUNT() FROM Address__c 
                WHERE Account__r.Id =: testAccount.Id AND Case__r.Id =: testCase.Id AND Contract__r.Id =: testContract.Id AND Type__c = 'Billing'];
        Test.StopTest();
        
        System.assert(addressCount > 0);
    }
    

    //Validate contract
    static testMethod void validationTest(){
        List<Account> testAccountList = CXE_TestDataFactory.createBusinessAccount(1);
        Account testAccount = testAccountList.get(0);
        insert testAccount;
        
        Id newServiceApplicationRecordTypeId = Schema.Sobjecttype.Case.getRecordTypeInfosByName().get(CXE_Constants.CASE_NEW_SERVICE_APPLICATION).getRecordTypeId();

        List<Case> testCaseList = CXE_TestDataFactory.createCase(1, 'New Electric Service,', 'Single Meter', 'Application Received', 'Private');
        Case testCase = testCaseList.get(0);
        testCase.RecordTypeId = newServiceApplicationRecordTypeId;
        testCase.Tax_Identification_No__c = '1111111';
        insert testCase;

        /*Address__c testAddress = new Address__c(Type__c = 'Billing', 
                                                Account__c = testAccount.Id,
                                                Case__c = testCase.Id,
                                                Address_Street_No__c = '1');*/
        Address__c testAddress = CXE_TestDataFactory.createAddressWithoutReference('Billing', testCase.Id, testAccount.Id, null, null, null, null); 

        insert testAddress;
        
        List<Contract> testContract = CXE_TestDataFactory.createContract(1, testAccount.Id, testCase.Id);
        insert testContract;

        Test.StartTest();
            Boolean isAccountAddressValid = CXE_CreateContract_CC.validateIfAccountHasBillingAddress(testAccount.Id);
            Boolean isCaseAddressValid = CXE_CreateContract_CC.validateIfCaseHasBillingAddress(testCase.Id);
            String isCreateContractValid = CXE_CreateContract_CC.isValidToCreateContract(testCase.Id, testCase.Status, false);
        Test.StopTest();

        System.assertEquals(true, isAccountAddressValid);
        System.assertEquals(true, isCaseAddressValid);
        System.assertEquals(CXE_Constants.CREATE_CONTRACT_ERROR_MESSAGE_SINGLE_METERED_VALIDATION, isCreateContractValid);
    }

    //Validate multimeter case contract
    static testMethod void validateMultimeterTest(){
        List<Account> testAccountList = CXE_TestDataFactory.createBusinessAccount(1);
        Account testAccount = testAccountList.get(0);
        insert testAccount;
        
        Id newServiceApplicationRecordTypeId = Schema.Sobjecttype.Case.getRecordTypeInfosByName().get(CXE_Constants.CASE_NEW_SERVICE_APPLICATION).getRecordTypeId();

        List<Case> testCaseList = CXE_TestDataFactory.createCase(1, 'New Electric Service,', 'Single Meter', 'Application Received', 'Private');
        Case testCase = testCaseList.get(0);
        testCase.RecordTypeId = newServiceApplicationRecordTypeId;
        testCase.Tax_Identification_No__c = '1111111';
        insert testCase;
        
        List<Contract> testContract = CXE_TestDataFactory.createContract(1, testAccount.Id, testCase.Id);
        insert testContract;

        Test.StartTest();
            String isCreateContractValid = CXE_CreateContract_CC.isValidToCreateContract(testCase.Id, testCase.Status, true);
        Test.StopTest();

        System.assertEquals(CXE_Constants.CREATE_CONTRACT_ERROR_MESSAGE_MULTI_METERED_VALIDATION, isCreateContractValid);
    }

    //Validate invalid case status
    static testMethod void validateInvalidCaseTest(){
        List<Account> testAccountList = CXE_TestDataFactory.createBusinessAccount(1);
        Account testAccount = testAccountList.get(0);
        insert testAccount;
        
        Id newServiceApplicationRecordTypeId = Schema.Sobjecttype.Case.getRecordTypeInfosByName().get(CXE_Constants.CASE_NEW_SERVICE_APPLICATION).getRecordTypeId();

        List<Case> testCaseList = CXE_TestDataFactory.createCase(1, 'New Electric Service,', 'Single Meter', 'Application Received', 'Private');
        Case testCase = testCaseList.get(0);
        testCase.RecordTypeId = newServiceApplicationRecordTypeId;
        testCase.Tax_Identification_No__c = '1111111';
        insert testCase;
        
        testCase.Status = 'Application with insufficient data';
        update testCase;

        List<Contract> testContract = CXE_TestDataFactory.createContract(1, testAccount.Id, testCase.Id);
        insert testContract;

        Test.StartTest();
            String isCreateContractValid = CXE_CreateContract_CC.isValidToCreateContract(testCase.Id, testCase.Status, true);
        Test.StopTest();

        System.assertEquals(CXE_Constants.CREATE_CONTRACT_ERROR_MESSAGE_INVALID_CASE_STATUS, isCreateContractValid);
    }
}