src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Conglomerate__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Conglomerate</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Address__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Billing_Preferences</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Address__c</fullName>
        <formula>Address_Unit_No__c &amp; &quot; &quot; &amp;  Address_Street_No__c &amp; &quot; &quot; &amp; Address_Street_Name__r.Name &amp; &quot;, &quot; &amp; Address_Subdivision__r.Name &amp; &quot; &quot; &amp;  Address_Barangay__r.Name &amp; &quot;, &quot; &amp; Address_City_Municipality__r.Name &amp; &quot;, &quot; &amp;  Address_Province__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Address</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipName>Billing_Preferences</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service</label>
        <referenceTo>Agreement__c</referenceTo>
        <relationshipName>Billing_Preferences</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Service</fullName>
                </value>
                <value>
                    <fullName>Billing</fullName>
                </value>
                <value>
                    <fullName>Customer</fullName>
                </value>
                <value>
                    <fullName>Meter</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Address</label>
    <nameField>
        <displayFormat>ADD-{000000}</displayFormat>
        <label>Address Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Agreement__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Agreements</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Contract__c</fullName>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipName>Agreements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Payor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Payor Contract of this Service</description>
        <label>Payor</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Services (Payor)</relationshipLabel>
        <relationshipName>Services_Payor</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SIN__c</fullName>
        <externalId>true</externalId>
        <label>SIN</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Service_Status__c</fullName>
        <label>Service Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Pending to Terminate</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Drop with service providing</fullName>
                </value>
                <value>
                    <fullName>Sleep</fullName>
                </value>
                <value>
                    <fullName>Active - Disconnected</fullName>
                </value>
                <value>
                    <fullName>Active - Pending to Disconnect</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>V10_Account_No__c</fullName>
        <label>V10 Account #</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Service</label>
    <nameField>
        <displayFormat>SERV-{00000000}</displayFormat>
        <label>Service ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Email_2__c</fullName>
        <label>Secondary Email</label>
        <type>Email</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Bill_Print_Mode__c</fullName>
        <label>Bill Print Mode</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>BILPRNT001</fullName>
                    <default>true</default>
                    <label>Paper</label>
                </value>
                <value>
                    <fullName>BILPRNT003</fullName>
                    <label>Paperless</label>
                </value>
                <value>
                    <fullName>BILPRNT002</fullName>
                    <label>Paperplus</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Form_of_Payment__c</fullName>
        <label>Payment Mode</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Cash</fullName>
                </value>
                <value>
                    <fullName>Check</fullName>
                </value>
                <value>
                    <fullName>Certificate of Tax Withheld at Source (BIR Forms)</fullName>
                </value>
                <value>
                    <fullName>Fund Transfer</fullName>
                </value>
                <value>
                    <fullName>Meralco Internal</fullName>
                </value>
                <value>
                    <fullName>Credit card</fullName>
                </value>
                <value>
                    <fullName>Debit card</fullName>
                </value>
                <value>
                    <fullName>E-wallet</fullName>
                </value>
                <value>
                    <fullName>Prepaid Card</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Method_of_Payment__c</fullName>
        <label>Method of Payment</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ADA (Bank)</fullName>
                </value>
                <value>
                    <fullName>ADA (Credit Card)</fullName>
                </value>
                <value>
                    <fullName>Over the Counter</fullName>
                </value>
                <value>
                    <fullName>Company Expenses</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Regular</fullName>
                </value>
                <value>
                    <fullName>Prepaid</fullName>
                </value>
                <value>
                    <fullName>SOLR</fullName>
                </value>
                <value>
                    <fullName>Retailer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>V10_Account_No__c</fullName>
        <externalId>true</externalId>
        <label>Legacy Account Number</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/CXE_Service_Enrollment__c.object
<CustomObject>
    <description>Logs customer portal registrations</description>
    <fields>
        <fullName>CXE_Alias__c</fullName>
        <label>Alias</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CXE_ServiceId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service</label>
        <referenceTo>Agreement__c</referenceTo>
        <relationshipLabel>Service Enrollments</relationshipLabel>
        <relationshipName>Service_Enrollments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CXE_Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Payor</fullName>
                </value>
                <value>
                    <fullName>Non-Payor</fullName>
                </value>
                <value>
                    <fullName>Tenant</fullName>
                    <isActive>false</isActive>
                    <label>Tenant</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CXE_UserId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Portal User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Service_Enrollments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Service Enrollment</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Enrollments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OrganizationSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>All Organization Settings</description>
    <fields>
        <fullName>ImageInPaperlessBilling__c</fullName>
        <label>ImageInPaperlessBilling</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Paperless_Billing_Download_Form__c</fullName>
        <defaultValue>&quot;http://www.meralco.com.ph/paperlessbilling&quot;</defaultValue>
        <label>Paperless Billing Download Form</label>
        <type>Url</type>
    </fields>
    <label>Organization Settings</label>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>CXE_Auto_Enrolled_Services__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This checkbox indicates if there are related services auto enrolled when the user registers on the portal using a SIN related to other services under one account.</description>
        <label>Auto Enrolled Services</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/CXE_CP_PaperlessBillingSubscribe.cls
public without sharing  class CXE_CP_PaperlessBillingSubscribe { //CSM-12485 GGrandea 09.08.2017 - changed to "without sharing"
    public class returnEmails{
        @AuraEnabled
        public String firstEmail;
        
        @AuraEnabled
        public String secondEmail;
    }
    
    @AuraEnabled	
    public static returnEmails firstEmail(string accountid){
        List<User> returnEmails = [SELECT LastLoginDate,FirstName,Email FROM User WHERE Id =:UserInfo.getUserId()]; 
        
        List<CXE_Service_Enrollment__c> listofEnrollments = [Select Id, CXE_ServiceId__c, CXE_Alias__c  
                                                             , CXE_ServiceId__r.Account__c, CXE_ServiceId__r.SIN__c
                                                             , CXE_ServiceId__r.Payor__c
                                                             From CXE_Service_Enrollment__c Where CXE_UserId__c=:UserInfo.getUserId()];
        
        
        Set<string> ContractIds = new Set<string>();
        for(CXE_Service_Enrollment__c agreement : listofEnrollments){
            if(agreement.CXE_ServiceId__r.Payor__c!=null){
                ContractIds.add(agreement.CXE_ServiceId__r.Payor__c);
            }
        }
        
       //CSM-12411 START EMandolado 09.04.2017
        List<Contract> listofContract = [Select Id,V10_Account_No__c,TYPE__c,Form_of_Payment__c,
                                         Method_of_Payment__c,AccountId, 
                                         Account.IsPersonAccount, Account.PersonContactId, Account.Email_2__pc
                                         from Contract where Id in:ContractIds and V10_Account_No__c =: accountid];
        
        returnEmails myReturn = new returnEmails();
        if(listofContract.size() > 0){
            if(listofContract[0].Account.IsPersonAccount){ //if person account
                 //Start CSM-12551 Emandolado 9/18/2017
                if(listofContract[0].Account.Email_2__pc != null){
                    myReturn.secondEmail = listofContract[0].Account.Email_2__pc;
                }else{
                    myReturn.secondEmail = '';
                }
                 //End CSM-12551 Emandolado 9/18/2017
            }else{
                Contact[] contacts = [SELECT Id,Email_2__c FROM Contact WHERE AccountId =: listofContract[0].AccountId]; 
                //GVG check if okay to use first if query returned multiple
                if(contacts.size()>0){
                    //Start CSM-12551 Emandolado 9/18/2017
                    if(listofContract[0].Account.Email_2__pc != null){
                        myReturn.secondEmail = contacts[0].Email_2__c;
                    }else{
                        myReturn.secondEmail = '';
                    }
                     //End CSM-12551 Emandolado 9/18/2017
                }
            }
        }
        //CSM-12411 END EMandolado 09.04.2017
        if(returnEmails.size() > 0){
            myReturn.firstEmail = returnEmails[0].Email;
        }
        return myReturn;
    }
    
    @AuraEnabled
    public static List<Contract> loadAccounts(){
        
        List<CXE_Service_Enrollment__c> listofEnrollments = [Select Id, CXE_ServiceId__c
                                                             , CXE_Alias__c
                                                             ,CXE_Type__c
                                                             , CXE_ServiceId__r.Account__c 
                                                             , CXE_ServiceId__r.SIN__c
                                                             From CXE_Service_Enrollment__c Where CXE_UserId__c=:UserInfo.getUserId() and CXE_Type__c = 'Payor'];
        
        Set<Id> accountIds = new Set<Id>();
        Set<Id> sinIds = new Set<Id>();
        for(CXE_Service_Enrollment__c enroll : listofEnrollments){
            if(enroll.CXE_ServiceId__r.Account__c!=null){
                accountIds.add(enroll.CXE_ServiceId__r.Account__c);
                sinIds.add(enroll.CXE_ServiceId__c);
            }
        }
        
        List<Agreement__c> service = [Select ID ,payor__r.Bill_Print_Mode__c,Payor__c,Payor__r.V10_Account_No__c, SIN__c,Account__c,Service_Status__c
                                      ,(Select Address__c from Billing_Preferences__r) 
                                      from Agreement__c 
                                      where Account__c In: accountIds 
                                      AND Id in: sinIds];
        
        set<String> listofContract = new Set<String>();
        for(Agreement__c enroll : service){
            if(enroll.Payor__r.V10_Account_No__c!=null){
                listofContract.add(enroll.Payor__c);
            }
        }
        
       //Start of CSM-13893 Corbes Melvin
        for(Case caseRec : [SELECT Id,
                            Contract__r.id,
                            Contract__r.V10_Account_No__c
                            FROM Case
                            WHERE RecordType.Name =: CXE_Constants.CASE_PAPERLESS_BILLING
                            AND Contract__c IN: listofContract
                            AND Application_Type_Subtype__c =: CXE_Constants.CASE_PAPERLESSBILLING_TYPE_SUB
                            AND Status =: CXE_Constants.CASE_STATUS_OPEN ]) {
                                
                            listofContract.remove(caseRec.Contract__r.id);  
                                
        }
        
        //End of CSM-13893 Corbes Melvin 
                                
        List<Contract> contract = [Select ID,V10_Account_No__c,Bill_Print_Mode__c from Contract where Id In: listofContract and Bill_Print_Mode__c = 'BILPRNT002'];
        
        
        
        
        
        
        /* set<String> accountIdsFinal = new Set<String>();
for(Agreement__c enroll : service){
if(enroll.Payor__r.V10_Account_No__c!=null){
accountIdsFinal.add(enroll.Payor__r.V10_Account_No__c);
}
}
List<string> acctHolder = new List<string>();
acctHolder.addAll(accountIdsFinal); */
        
        
        return contract;
    }
    
    //START R2C CSM-13274 Shayne 10/13/2017
     @AuraEnabled
        public static boolean retrieveCheckConglomerate(){
        System.debug('retrieveCheckConglomerate');
        boolean ret = false;
        User userData = [SELECT LastLoginDate,FirstName,CXE_Auto_Enrolled_Services__c, AccountId FROM User WHERE Id =:UserInfo.getUserId()]; 
        System.debug('retrieveCheckConglomerate uid '+userData.id+' :AccountID '+userData.AccountId);
        
         try{
              Account accountConglomerate = [SELECT id,Conglomerate__c,Name from Account where id=:userData.AccountId and Conglomerate__c=true];
                 ret = true;
            }catch(Exception e){
                System.debug('retrieveCheckConglomerate error '+e );
            }
        return ret;
    }
    //END R2C CSM-13274 Shayne 10/13/2017
    
    //Start CSM-14653 Mike Verdad 11/29/2017
    @AuraEnabled
    public static String RedirectToMeralcoWebsite() {
        System.debug('RedirectToMeralcoWebsite');
        return OrganizationSettings__c.getOrgDefaults().Paperless_Billing_Download_Form__c;
    }
    //End CSM-14653 Mike Verdad 11/29/2017
    
    // start of CSM-14772 Corbes Melvin 12/5/2017
    @AuraEnabled
    public static String ImageInPaperlessBilling() {
        return OrganizationSettings__c.getOrgDefaults().ImageInPaperlessBilling__c;
    }
    // end of CSM-14772 Corbes Melvin 12/5/2017



    
}