src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Primary Email</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Address__c.object
<CustomObject>
    <fields>
        <fullName>Address__c</fullName>
        <formula>Address_Unit_No__c &amp; &quot; &quot; &amp;  Address_Street_No__c &amp; &quot; &quot; &amp; Address_Street_Name__r.Name &amp; &quot;, &quot; &amp; Address_Subdivision__r.Name &amp; &quot; &quot; &amp;  Address_Barangay__r.Name &amp; &quot;, &quot; &amp; Address_City_Municipality__r.Name &amp; &quot;, &quot; &amp;  Address_Province__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Address</label>
        <type>Text</type>
    </fields>
    <label>Address</label>
    <nameField>
        <displayFormat>ADD-{000000}</displayFormat>
        <label>Address Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Agreement__c.object
<CustomObject>
    <fields>
        <fullName>Applied_Load__c</fullName>
        <label>Applied Load</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Demand_Factor__c</fullName>
        <label>Demand Factor</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Load_Factor__c</fullName>
        <label>Load Factor</label>
        <precision>3</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PSIC__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>PSIC</label>
        <referenceTo>PSIC__c</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Payor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Payor Contract of this Service</description>
        <label>Payor</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Services (Payor)</relationshipLabel>
        <relationshipName>Services_Payor</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Phase__c</fullName>
        <label>Phase</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Single Phase (1Ø), Network</fullName>
                </value>
                <value>
                    <fullName>Single Phase (1Ø), Three (3)-Wire</fullName>
                </value>
                <value>
                    <fullName>Single Phase (1Ø), Two (2)-Wire</fullName>
                </value>
                <value>
                    <fullName>Three Phase (3Ø), Four (4)-Wire (Delta)</fullName>
                </value>
                <value>
                    <fullName>Three Phase (3Ø), Four (4)-Wire (Grounded Wye)</fullName>
                </value>
                <value>
                    <fullName>Three Phase (3Ø), Four (4)-Wire (Grounded Wye/Delta)</fullName>
                </value>
                <value>
                    <fullName>Three Phase (3Ø), Three (3)-Wire (Delta)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SIN__c</fullName>
        <externalId>true</externalId>
        <label>SIN</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Service_Supply_Type__c</fullName>
        <label>Service Supply Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Normal with meter</fullName>
                </value>
                <value>
                    <fullName>Streetlight with meter</fullName>
                </value>
                <value>
                    <fullName>Normal without meter</fullName>
                </value>
                <value>
                    <fullName>Temporary with meter</fullName>
                </value>
                <value>
                    <fullName>Streetlight without meter</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Service_Wire_Length__c</fullName>
        <label>Service Wire Length</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Service_Wire_Type__c</fullName>
        <label>Service Wire Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Aerial Alum.,Bundled</fullName>
                </value>
                <value>
                    <fullName>Aerial Alum.,Open</fullName>
                </value>
                <value>
                    <fullName>Aerial CU.,Bundled</fullName>
                </value>
                <value>
                    <fullName>Aerial Coppen,Open</fullName>
                </value>
                <value>
                    <fullName>Under Alum.,Lateral</fullName>
                </value>
                <value>
                    <fullName>Under Copper,Lateral</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>V10_Account_No__c</fullName>
        <label>V10 Account #</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Service</label>
    <nameField>
        <displayFormat>SERV-{00000000}</displayFormat>
        <label>Service ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Bill_Print_Mode__c</fullName>
        <label>Bill Print Mode</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>BILPRNT001</fullName>
                    <default>true</default>
                    <label>Paper</label>
                </value>
                <value>
                    <fullName>BILPRNT003</fullName>
                    <label>Paperless</label>
                </value>
                <value>
                    <fullName>BILPRNT002</fullName>
                    <label>Paperplus</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contract_External_ID__c</fullName>
        <externalId>true</externalId>
        <label>Contract External ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>V10_Account_No__c</fullName>
        <externalId>true</externalId>
        <label>Legacy Account Number</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Exception_Log__c.object
<CustomObject>
    <description>This object will record all exceptions that will occur within the system</description>
    <fields>
        <fullName>Class_Name__c</fullName>
        <description>Identifies which class caused the exception</description>
        <label>Class Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Exception__c</fullName>
        <description>Logs the exception message generated by the system</description>
        <label>Exception</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Method_Name__c</fullName>
        <description>Identifies which method in the class caused the exception</description>
        <label>Method Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Exception Log</label>
    <nameField>
        <displayFormat>E-{0000000}</displayFormat>
        <label>Exception Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exception Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Integration_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Custom settings which store integration settings</description>
    <label>Integration Settings</label>
</CustomObject>

src/objects/PSIC__c.object
<CustomObject>
    <description>PSIC</description>
    <fields>
        <fullName>Demand_Factor__c</fullName>
        <description>Recommended demand factor by PSIC</description>
        <inlineHelpText>Recommended demand factor by PSIC</inlineHelpText>
        <label>Demand Factor</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Load_Factor__c</fullName>
        <description>Suggested Load Factor by PSIC</description>
        <inlineHelpText>Suggested Load Factor by PSIC</inlineHelpText>
        <label>Load Factor</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PSIC_Code__c</fullName>
        <description>PSIC code (referenced for CMSv10)</description>
        <externalId>true</externalId>
        <inlineHelpText>PSIC code (referenced for CMSv10)</inlineHelpText>
        <label>PSIC Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>PSIC</label>
    <nameField>
        <label>PSIC Description</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PSICs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/CXE_CP_BPModeIntegrationUtility_Test.cls
@isTest
public class CXE_CP_BPModeIntegrationUtility_Test {


    @testSetup static void setup() {

        Test.startTest();

        CXE_TestDataFactory.setOrgSettings();
        List<Integration_Settings__c> lstIntegSettings = CXE_TestDataFactory.createIntegrationSettings();
            insert lstIntegSettings;

        //Create PSIC
        List<PSIC__c> psicLst = CXE_TestDataFactory.createPSIC(1);
        psicLst[0].Name = 'Non-Residential';
        psicLst[0].Demand_Factor__c = .80;
        psicLst[0].PSIC_Code__c = '77770';
        insert psicLst;
        system.assertEquals(true, psicLst[0].Id!=null );

        List<Account> acctList = CXE_TestDataFactory.createPersonAccount(1);
            acctList[0].FirstName = 'first';
            acctList[0].MiddleName = 'middle';
            acctList[0].LastName = 'last';
            acctList[0].Email__c = 'first_last_name@yopmail.com';
        insert acctList;
        system.assertEquals(true, acctList[0].Id!=null );

        Account acct = [Select Id, PersonContactId From Account 
                        Where Id =: acctList[0].Id ];
        system.assertEquals(true, acct.PersonContactId!=null );

         //Create Case
        Id newServiceApplicationRecordTypeId = Schema.Sobjecttype.Case.getRecordTypeInfosByName().get(CXE_Constants.CASE_NEW_SERVICE_APPLICATION).getRecordTypeId();  
        List<Case> createCase = CXE_TestDataFactory.createCase(1, 'New Electric Service,', 'Single Meter', 'Application Received', 'Private');
        createCase[0].RecordTypeId = newServiceApplicationRecordTypeId;
        createCase[0].PSIC__c = psicLst[0].id;
        createCase[0].ContactId = acct.PersonContactId;
        createCase[0].AccountId = acct.Id;
        createCase[0].Applied_Load__c = 6;
        createCase[0].Demand_Factor__c = 0.50;
        createCase[0].Load_Factor__c = 0.25;
        createCase[0].Phase__c = 'Single Phase (1Ø), Network';
        createCase[0].Service_Supply_Type__c = 'Normal with meter';
        createCase[0].Service_Wire_Length__c = 1;
        createCase[0].Material__c = 'Copper';
        createCase[0].Pole_Code__c = '1';
        createCase[0].Wire_Size__c = '#1/0';
        createCase[0].Service_Wire_Type__c = 'Under Copper,Lateral';
        createCase[0].Voltage__c = '2.0 kV';
        createCase[0].Application_for_Business_Customer__c = false;
        createCase[0].Application_for_Residential_Customer__c = true;
        
        insert createCase;
        system.assertEquals(true, createCase[0].Id!=null );

        
        //Create Contract
        List<Contract> createContract = CXE_TestDataFactory.createContract(1,acct.id,createCase[0].id);
        createContract[0].V10_Account_No__c = '584950609109';
        createContract[0].Contract_External_ID__c = '584950609109';
        createContract[0].Bill_Print_Mode__c = CXE_Constants.BPM_PAPER;
        insert createContract;
        system.assertEquals(true, createContract[0].Id!=null );

        //Create Address
        Address__c createAddress = CXE_TestDataFactory.createAddress(acct.id,createCase[0].id,createContract[0].id);
        insert createAddress;
        system.assertEquals(true, createAddress.Id!=null );
        
        //Create Service
        //Modified by Rom - changed method call from createService() to createServiceWithLessDetails()
        List<Agreement__c> createService = CXE_TestDataFactory.createServiceWithLessDetails(1,acct.id,createCase[0].id,
                                                                createContract[0].id,psicLst[0].id);
        createService[0].Payor__c = createContract[0].id;
        insert createService;
        createService[0].SIN__c = '293028374839';
        update createService;
        system.assertEquals(true, createService[0].Id!=null );

        Test.stopTest();
    }


    @isTest
    static void test_BPMode_SingleSuccessReason(){        
        List<Contract> contractList = [SELECT Id FROM Contract WHERE V10_Account_No__c = '584950609109'];

        Test.startTest();

            Set<Id> bpContractIds = new Set<Id>{contractList[0].Id};
            Map<String, String> bpmMap = new Map<String, String>();
                                bpmMap.put(contractList[0].Id, CXE_Constants.BPM_PAPERPLUS);
            Map<Id, String> bpReasonMap = new Map<Id, String>();
                            bpReasonMap.put(contractList[0].Id, 'Reason');

            Test.setMock(HttpCalloutMock.class, new MockBillPrintModeService(false, '584950609109', 'S', 200, 'OK','2017-10-24') );
            CXE_CP_BillPrintModeIntegrationUtility.relateServiceAddress(bpContractIds, bpmMap, bpReasonMap);
        
        Test.stopTest();

        contractList = [SELECT Id, Bill_Print_Mode__c FROM Contract WHERE V10_Account_No__c = '584950609109'];
        System.assertEquals(CXE_Constants.BPM_PAPERPLUS, contractList[0].Bill_Print_Mode__c );
    }


    @isTest
    static void test_BPMode_SingleSuccess(){        
        List<Contract> contractList = [SELECT Id FROM Contract WHERE V10_Account_No__c = '584950609109'];

        Test.startTest();

            Set<Id> bpContractIds = new Set<Id>{contractList[0].Id};
            Map<String, String> bpmMap = new Map<String, String>();

            Test.setMock(HttpCalloutMock.class, new MockBillPrintModeService(false, '584950609109', 'S', 200, 'OK','2017-10-24') );

            bpmMap.put(contractList[0].Id, CXE_Constants.BPM_PAPERPLUS);
            CXE_CP_BillPrintModeIntegrationUtility.relateServiceAddress(bpContractIds, bpmMap);

            bpmMap.put(contractList[0].Id, CXE_Constants.BPM_PAPERLESS);
            CXE_CP_BillPrintModeIntegrationUtility.relateServiceAddress(bpContractIds, bpmMap);

            bpmMap.put(contractList[0].Id, CXE_Constants.BPM_PAPERPLUS);
            CXE_CP_BillPrintModeIntegrationUtility.relateServiceAddress(bpContractIds, bpmMap);

            bpmMap.put(contractList[0].Id, CXE_Constants.BPM_PAPERLESS);
            CXE_CP_BillPrintModeIntegrationUtility.relateServiceAddress(bpContractIds, bpmMap);

            bpmMap.put(contractList[0].Id, CXE_Constants.BPM_PAPERPLUS);
            CXE_CP_BillPrintModeIntegrationUtility.relateServiceAddress(bpContractIds, bpmMap);

            bpmMap.put(contractList[0].Id, CXE_Constants.BPM_PAPER);
            CXE_CP_BillPrintModeIntegrationUtility.relateServiceAddress(bpContractIds, bpmMap);
        
        Test.stopTest();

        contractList = [SELECT Id, Bill_Print_Mode__c FROM Contract WHERE V10_Account_No__c = '584950609109'];
        System.assertEquals(CXE_Constants.BPM_PAPER, contractList[0].Bill_Print_Mode__c );
    }


    @isTest
    static void test_BPMode_SingleFailed(){        
        List<Contract> contractList = [SELECT Id FROM Contract WHERE V10_Account_No__c = '584950609109'];

        Test.startTest();

            Set<Id> bpContractIds = new Set<Id>{contractList[0].Id};
            Map<String, String> bpmMap = new Map<String, String>();
            bpmMap.put(contractList[0].Id, CXE_Constants.BPM_PAPERPLUS);

            Test.setMock(HttpCalloutMock.class, new MockBillPrintModeService(false, '584950609109', 'F', 200, 'OK','Error: Invalid ID payment form.') );
            CXE_CP_BillPrintModeIntegrationUtility.relateServiceAddress(bpContractIds, bpmMap);
        
        Test.stopTest();

        List<Exception_Log__c> logList = [SELECT Id, Exception__c,Class_Name__c, Method_Name__c FROM Exception_Log__c];
        System.assertEquals(2, logList.size() );
    }


    /*@isTest
    static void test_BPMode_MultiSuccess(){      
        List<Contract> contractList = [SELECT Id FROM Contract WHERE V10_Account_No__c = '584950609109'];

        Test.startTest();

            Set<Id> bpContractIds = new Set<Id>{contractList[0].Id};
            Map<String, String> bpmMap = new Map<String, String>();
            bpmMap.put(contractList[0].Id, CXE_Constants.BPM_PAPERPLUS);

            Test.setMock(HttpCalloutMock.class, new MockBillPrintModeService(true, '584950609109', 'S', 200, 'OK','2017-10-24') );
            CXE_CP_BillPrintModeIntegrationUtility.relateServiceAddress(bpContractIds, bpmMap);
        
        Test.stopTest();

        List<Exception_Log__c> logList = [SELECT Id, Exception__c,Class_Name__c, Method_Name__c FROM Exception_Log__c];
        if(logList.size()>0){
            System.assertEquals(1, logList.size() );
            System.assertEquals('test', logList[0].Class_Name__c + ' ' + logList[0].Method_Name__c + ' ' + logList[0].Exception__c );
        }

        contractList = [SELECT Id, Bill_Print_Mode__c FROM Contract WHERE V10_Account_No__c = '584950609109'];
        System.assertEquals(CXE_Constants.BPM_PAPERPLUS, contractList[0].Bill_Print_Mode__c );
    }*/


    @isTest
    static void test_BPMode_MultiFailed(){        
        List<Contract> contractList = [SELECT Id FROM Contract WHERE V10_Account_No__c = '584950609109'];

        Test.startTest();

            Set<Id> bpContractIds = new Set<Id>{contractList[0].Id};
            Map<String, String> bpmMap = new Map<String, String>();
            bpmMap.put(contractList[0].Id, CXE_Constants.BPM_PAPERPLUS);

            Test.setMock(HttpCalloutMock.class, new MockBillPrintModeService(true, '584950609109', 'F', 200, 'OK','Error: Invalid ID payment form.') );
            CXE_CP_BillPrintModeIntegrationUtility.relateServiceAddress(bpContractIds, bpmMap);
        
        Test.stopTest();

        List<Exception_Log__c> logList = [SELECT Id, Exception__c,Class_Name__c, Method_Name__c FROM Exception_Log__c];
        System.assertEquals(2, logList.size() );
    }


}