src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Customer_Accepted__c</fullName>
        <description>This field indicates whether a customer is accepted or not.</description>
        <label>Customer Acceptance</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Accepted under Conditions</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Tax_Identification_No__c</fullName>
        <label>Tax Identification Number</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>V10_Customer_No__c</fullName>
        <externalId>true</externalId>
        <label>Legacy Customer #</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Bundle__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bundle</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Product2.RecordTypeId</field>
                <operation>equals</operation>
                <value>Bundle</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Closed_Lost_Reason__c</fullName>
        <description>Specify a reason why the Opportunity was Lost. Cannot be empty if Opportunity Stage is set to &quot;Closed Lost&quot;</description>
        <label>Closed Lost Remarks</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/AccountTriggerClassTest.cls
/**
  * @author       : Sanchayeeta
  * @date         : 05/11/2015
  * @description  : Test Class for AccountTriggerClass class 
  */  
@isTest()
public class AccountTriggerClassTest{
     
    private static testMethod void TestMet(){
            
       
       //Account Acc =TestDataFactoryTest.createAccount();
       //Opportunity opp=TestDataFactoryTest.createOpportunity();
           Account acc= new Account();
           acc.name='Test Acc';
           acc.Customer_Accepted__c = 'Rejected';
           acc.Tax_Identification_No__c = '1231'; //CXE PDC 3-28-2017 addition account validation
           //START RReyes JUL-07-17 - R2 - added field values for validations
           acc.Phone = '+6300000000';
           acc.V10_Customer_No__c = '3242527182';
           //END RReyes JUL-07-17 - R2 - added field values for validations
           insert acc;
           
          opportunity opp=new opportunity();
          opp.accountid= acc.id;
          opp.name= 'TestSAN';
          opp.closedate=System.today();
          opp.stagename = 'Pending Security Deposit';
          opp.Closed_Lost_Reason__c = 'close reason';//CXE PDC 3-28-2017 addition account validation
          //opp.pricebook2id= PricebookId;
          //opp.Bundle__C=BundleProductID;
          insert opp;
       
       
       List<Account> listAcc = new List<Account>();
        listAcc.add(Acc);
    
        
       system.Test.startTest();
        AccountTriggerClass oAccountTrigger = new AccountTriggerClass();
        oAccountTrigger.accountAcceptance(listAcc);        
        system.Test.stopTest();
           
    
    }
   
}