src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Primary Email</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Office__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Office</label>
        <referenceTo>Office__c</referenceTo>
        <relationshipLabel>Executing Personnels</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Address__c.object
<CustomObject>
    <fields>
        <fullName>Address__c</fullName>
        <formula>Address_Unit_No__c &amp; &quot; &quot; &amp;  Address_Street_No__c &amp; &quot; &quot; &amp; Address_Street_Name__r.Name &amp; &quot;, &quot; &amp; Address_Subdivision__r.Name &amp; &quot; &quot; &amp;  Address_Barangay__r.Name &amp; &quot;, &quot; &amp; Address_City_Municipality__r.Name &amp; &quot;, &quot; &amp;  Address_Province__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Address</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipName>Billing_Preferences</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Address</label>
    <nameField>
        <displayFormat>ADD-{000000}</displayFormat>
        <label>Address Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Field_Order__c.object
<CustomObject>
    <fields>
        <fullName>Account_Name__c</fullName>
        <formula>IF(Case__r.Application_for_Business_Customer__c = TRUE, Case__r.Account.Name, Case__r.First_Name__c + &quot; &quot; +  Case__r.Middle_Name__c + &quot; &quot; +  Case__r.Last_Name__c)</formula>
        <label>Account Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address__c</fullName>
        <description>Address</description>
        <formula>Case__r.CXE_Service_Address__c</formula>
        <inlineHelpText>Address</inlineHelpText>
        <label>Address</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Field Orders</relationshipLabel>
        <relationshipName>Field_Orders</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Contact_Name__c</fullName>
        <formula>Case__r.First_Name__c + &quot; &quot; +  Case__r.Middle_Name__c + &quot; &quot; +  Case__r.Last_Name__c</formula>
        <label>Contact Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <formula>Case__r.Email_Address__c</formula>
        <label>Primary Email</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Executing_Personnel_FO__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Executing Personnel</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Office__c</field>
                <operation>equals</operation>
                <valueField>$Source.Office__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Field Orders</relationshipLabel>
        <relationshipName>Field_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Inspection_Instructions__c</fullName>
        <description>Instructions for inspection</description>
        <inlineHelpText>Instructions for inspection</inlineHelpText>
        <label>Inspection Instructions</label>
        <length>300</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Inspection_Result__c</fullName>
        <description>Result of inspection</description>
        <inlineHelpText>Result of inspection</inlineHelpText>
        <label>Inspection Result</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Disapproved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Landmarks__c</fullName>
        <formula>Case__r.Service_Address_Landmarks_Directions__c</formula>
        <label>Landmarks</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Material__c</fullName>
        <label>Service Wire Material</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Aluminum</fullName>
                </value>
                <value>
                    <fullName>Copper</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Meter_Socket_Delivery_Instructions__c</fullName>
        <description>Instruction for meter socket delivery</description>
        <inlineHelpText>Instruction for meter socket delivery</inlineHelpText>
        <label>Meter Socket Delivery Instructions</label>
        <length>300</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Meter_Socket_Delivery__c</fullName>
        <description>Result of meter socket delivery</description>
        <inlineHelpText>Result of meter socket delivery</inlineHelpText>
        <label>Meter Socket Delivery Result</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Delivered</fullName>
                </value>
                <value>
                    <fullName>Not Delivered</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Metering_Scheme__c</fullName>
        <label>Metering Scheme</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>NORMAL</fullName>
                </value>
                <value>
                    <fullName>EMC</fullName>
                </value>
                <value>
                    <fullName>MULTI-METERING CENTER</fullName>
                </value>
                <value>
                    <fullName>ICP</fullName>
                </value>
                <value>
                    <fullName>MULTI-METERING PER FLOOR</fullName>
                </value>
                <value>
                    <fullName>SUBSTATION</fullName>
                </value>
                <value>
                    <fullName>PRIMARY METERING</fullName>
                </value>
                <value>
                    <fullName>20 KV</fullName>
                </value>
                <value>
                    <fullName>AMI-NORMAL</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Mobile_No__c</fullName>
        <formula>Case__r.Mobile_No__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Primary Mobile</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mode_of_Retrieval__c</fullName>
        <label>Mode of Retrieval</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>REMOTE</fullName>
                </value>
                <value>
                    <fullName>ONSITE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Office__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Office</label>
        <referenceTo>Office__c</referenceTo>
        <relationshipLabel>Field Orders</relationshipLabel>
        <relationshipName>Field_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Pole_Code__c</fullName>
        <label>Service Wire Pole #</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ready_for_Connection__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Ready for connection</description>
        <inlineHelpText>Ready for connection</inlineHelpText>
        <label>Ready for Connection</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Resolution_Date__c</fullName>
        <description>Date when pre-survey is resolved</description>
        <inlineHelpText>Date when pre-survey is resolved</inlineHelpText>
        <label>Resolution Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Resolution_Remarks__c</fullName>
        <description>Resolution remark</description>
        <inlineHelpText>Resolution remark</inlineHelpText>
        <label>Resolution Remarks</label>
        <length>300</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>SE_Completion_Target_Negotiated__c</fullName>
        <defaultValue>false</defaultValue>
        <description>SE Completion target negotiated</description>
        <inlineHelpText>SE Completion target negotiated</inlineHelpText>
        <label>SE Completion Target Negotiated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SE_Not_Compliant__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Service entrance needs correction</description>
        <inlineHelpText>Service entrance needs correction</inlineHelpText>
        <label>Service entrance needs correction</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SE_Not_Installed_Yet__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Found no service entrance on site</description>
        <inlineHelpText>Found no service entrance on site</inlineHelpText>
        <label>Found no service entrance on site</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Schedule_Date__c</fullName>
        <label>Schedule Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Service_Wire_Length__c</fullName>
        <label>Service Wire Length</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Service_Wire_Size__c</fullName>
        <label>Service Wire Size</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>#1/0</fullName>
                </value>
                <value>
                    <fullName>#2</fullName>
                </value>
                <value>
                    <fullName>#3/0</fullName>
                </value>
                <value>
                    <fullName>#4</fullName>
                </value>
                <value>
                    <fullName>#4/0</fullName>
                </value>
                <value>
                    <fullName>#6</fullName>
                </value>
                <value>
                    <fullName>#8</fullName>
                </value>
                <value>
                    <fullName>1000 MCM</fullName>
                </value>
                <value>
                    <fullName>500 MCM</fullName>
                </value>
                <value>
                    <fullName>500 MCM &amp; #4/0</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Service_Wire_Type__c</fullName>
        <label>Service Wire Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Aerial Alum.,Bundled</fullName>
                </value>
                <value>
                    <fullName>Aerial Alum.,Open</fullName>
                </value>
                <value>
                    <fullName>Aerial CU.,Bundled</fullName>
                </value>
                <value>
                    <fullName>Aerial Coppen,Open</fullName>
                </value>
                <value>
                    <fullName>Under Alum.,Lateral</fullName>
                </value>
                <value>
                    <fullName>Under Copper,Lateral</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Generated</fullName>
                    <default>true</default>
                    <label>Generated</label>
                </value>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>In Execution</fullName>
                </value>
                <value>
                    <fullName>Executed</fullName>
                </value>
                <value>
                    <fullName>Not Required</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TLN__c</fullName>
        <label>Service Wire TLN</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Telephone_No__c</fullName>
        <formula>Case__r.Telephone_No__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Primary Telephone</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Wrong_SE_Location__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Service entrance not in agreed location</description>
        <inlineHelpText>Service entrance not in agreed location</inlineHelpText>
        <label>Service entrance not in agreed location</label>
        <type>Checkbox</type>
    </fields>
    <label>Field Order</label>
    <nameField>
        <displayFormat>FO-{00000000}</displayFormat>
        <label>Field Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Field Orders</pluralLabel>
    <recordTypes>
        <fullName>CXE_Inspection_FO</fullName>
        <active>true</active>
        <label>Inspection FO</label>
    </recordTypes>
    <recordTypes>
        <fullName>CXE_Meter_Socket_Delivery</fullName>
        <active>true</active>
        <label>Meter Socket Delivery</label>
    </recordTypes>
    <recordTypes>
        <fullName>CXE_Re_Inspection_FO</fullName>
        <active>true</active>
        <label>Re-Inspection FO</label>
    </recordTypes>
    <recordTypes>
        <fullName>CXE_Survey_FO</fullName>
        <active>true</active>
        <label>Survey FO</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CXE_FOPrintingPDFController.cls
/* 
* Description: Controller for PDF generation
* Author: Rom Edison Reyes (Accenture)
* Date Created: SEP-07-17
*/ 
public class CXE_FOPrintingPDFController{
    public static List<String> lstFOIds = new List<String>();
    public CXE_FOPrintingPDFController(){
        String foIds = ApexPages.currentPage().getParameters().get('foIdList');
        System.debug('>>rr: foIds ' + foIds);
        if(!String.isBlank(foIds)){
            if(foIds.contains(';')){
                lstFOIds = foIds.split(';');
            }else{
                lstFOIds.add(foIds); 
            }    
        }
    }
    
    public List<Field_Order__c> getFieldOrderList(){
       List<Field_Order__c> foList = new List<Field_Order__c>();
       if(!lstFOIds.isEmpty()){
           foList = [SELECT Id, Name, Case__c, Case__r.CaseNumber, Mobile_No__c, Email__c, Address__c, Landmarks__c, Status__c, Schedule_Date__c, CreatedBy.Name, CreatedDate, Meter_Socket_Delivery_Instructions__c,
                          RecordType.Name,RecordType.DeveloperName, Account_Name__c, Contact_Name__c, Telephone_No__c, Resolution_Date__c, Office__r.Name, Executing_Personnel_FO__r.Name, Inspection_Instructions__c, 
                          TLN__c, Pole_Code__c, Material__c, Metering_Scheme__c, Mode_of_Retrieval__c, Service_Wire_Size__c, Service_Wire_Length__c, Service_Wire_Type__c, Resolution_Remarks__c, 
                          Inspection_Result__c, Ready_for_Connection__c, SE_Not_Compliant__c, SE_Not_Installed_Yet__c, Wrong_SE_Location__c, Meter_Socket_Delivery__c, SE_Completion_Target_Negotiated__c,
                          Delivery_for_Reschedule__c, Contact_Person_Unreachable__c, For_BC_Pickup__c, Re_inspection_Instructions__c, Re_Inspection_Result__c, Survey_Instructions__c, Pick_Up_Document__c, 
                          Deliver_Document__c, Additional_Documents_for_Evaluation_Requ__c, Pre_Survey_Result__c, Inconsistent_SA_Data_Required__c, ROW_Grant_for_SE_Required__c, Extensive_modifications_to_premises_requ__c,
                          Unable_to_Locate_Given_Address__c, Add_Distribution_Facilities_Required__c
                     FROM Field_Order__c
                     WHERE Id IN:lstFOIds];
       }
        //for adding a space every 100th character to push it as a next line.
        for (Field_Order__c ii : foList) {
            if (ii.recordType.developerName == 'CXE_Survey_FO') {
                 ii.Survey_Instructions__c = ii.Survey_Instructions__c.replaceAll('.{100}', '$0 ');
            }
            if (ii.recordType.developerName == 'CXE_Inspection_FO') {
                 ii.Inspection_Instructions__c = ii.Inspection_Instructions__c.replaceAll('.{100}', '$0 ');
            }
            if (ii.recordType.developerName == 'CXE_Re_Inspection_FO') {
                 ii.Re_inspection_Instructions__c = ii.Re_inspection_Instructions__c.replaceAll('.{100}', '$0 ');
            }
            if (ii.recordType.developerName == 'CXE_Meter_Socket_Delivery') {
                 ii.Meter_Socket_Delivery_Instructions__c = ii.Meter_Socket_Delivery_Instructions__c.replaceAll('.{100}', '$0 ');
            }
            system.debug(ii.recordType.developerName);
        }

       return foList;
    }
}