src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Tax_Identification_No__c</fullName>
        <label>Tax Identification Number</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Bill_Print_Mode__c</fullName>
        <label>Bill Print Mode</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>BILPRNT001</fullName>
                    <default>true</default>
                    <label>Paper</label>
                </value>
                <value>
                    <fullName>BILPRNT003</fullName>
                    <label>Paperless</label>
                </value>
                <value>
                    <fullName>BILPRNT002</fullName>
                    <label>Paperplus</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Method_of_Payment__c</fullName>
        <label>Method of Payment</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ADA (Bank)</fullName>
                </value>
                <value>
                    <fullName>ADA (Credit Card)</fullName>
                </value>
                <value>
                    <fullName>Over the Counter</fullName>
                </value>
                <value>
                    <fullName>Company Expenses</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Regular</fullName>
                </value>
                <value>
                    <fullName>Prepaid</fullName>
                </value>
                <value>
                    <fullName>SOLR</fullName>
                </value>
                <value>
                    <fullName>Retailer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>V10_Account_No__c</fullName>
        <externalId>true</externalId>
        <label>Legacy Account Number</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/CXE_KeyValueSetting__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Custom setting used to store all generic key value pair settings.</description>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Key Value Setting</label>
</CustomObject>

src/objects/OrganizationSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>All Organization Settings</description>
    <fields>
        <fullName>Heroku_Basic_Auth__c</fullName>
        <description>Used for Basic Authentication of Heroku</description>
        <label>Heroku Basic Auth</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Organization Settings</label>
</CustomObject>

src/classes/CXE_CP_APAFileUpload_CC_Test.cls
@isTest
private class CXE_CP_APAFileUpload_CC_Test {
	
	@testSetup
    static void setupOrgData(){
        OrganizationSettings__c orgSet = new OrganizationSettings__c();
        orgSet.Heroku_Basic_Auth__c = 'Basic TEST=';
        insert orgSet;

        CXE_KeyValueSetting__c keyVal = new CXE_KeyValueSetting__c();
        keyVal.Name = 'APA_UPLOAD_MAX_FILESIZE';
        keyVal.Value__c = '2000000';
        insert keyVal;
    }

	@isTest static void getCaseDetailsTest() {
		List<Account> testAccountList = CXE_TestDataFactory.createBusinessAccount(1);
        Account testAccount = testAccountList.get(0);
        insert testAccount;
       
        Id newServiceApplicationRecordTypeId = Schema.Sobjecttype.Case.getRecordTypeInfosByName().get(CXE_Constants.CASE_NEW_SERVICE_APPLICATION).getRecordTypeId();
        
        List<Case> testCaseList = CXE_TestDataFactory.createCase(1, 'New Electric Service,', 'Single Meter', 'Application Received', 'Private');
        Case testCase = testCaseList.get(0);
        testCase.RecordTypeId = newServiceApplicationRecordTypeId;
        testCase.Tax_Identification_No__c = '1111111';
        testCase.AccountId = testAccount.Id;
        insert testCase;
        
        Contract testContract = new Contract(AccountId = testAccount.Id,
                                             Case__c = testCase.Id,
                                             V10_Account_No__c = '12345678',
                                             Method_of_Payment__c = 'Over the Counter',
                                             Bill_Print_Mode__c = 'Paper',
                                             Type__c = 'Regular');
        insert testContract;

        //CREATE PayOps USER ACCOUNT
        Profile payOps = [SELECT Id FROM Profile WHERE Name ='Payment Operations' Limit 1];
        User payOpsUser = new User(
            Username = System.now().millisecond() + 'test12345@test.com',
            ProfileId = payOps.Id,
            Alias = 'test123',
            Email = 'test12345@test.com',
            EmailEncodingKey = 'UTF-8',
            LastName = 'McTesty',
            CommunityNickname = 'test12345',
            TimeZoneSidKey = 'America/Los_Angeles',
            LocaleSidKey = 'en_US',
            LanguageLocaleKey = 'en_US'
        );

        system.runAs(payOpsUser){
            Case apaCase = CXE_TestDataFactory.createAPACase(1, true, testContract.Id)[0];
            insert apaCase;

            test.startTest();
            Case c = CXE_CP_APAFileUpload_CC.getCaseDetails(apaCase.Id);
            System.assertNotEquals(null, c);
            test.stopTest();
        }
	}
	
	@isTest static void updateFileCountTest_SUCCESS() {
		List<Account> testAccountList = CXE_TestDataFactory.createBusinessAccount(1);
        Account testAccount = testAccountList.get(0);
        insert testAccount;
       
        Id newServiceApplicationRecordTypeId = Schema.Sobjecttype.Case.getRecordTypeInfosByName().get(CXE_Constants.CASE_NEW_SERVICE_APPLICATION).getRecordTypeId();
        
        List<Case> testCaseList = CXE_TestDataFactory.createCase(1, 'New Electric Service,', 'Single Meter', 'Application Received', 'Private');
        Case testCase = testCaseList.get(0);
        testCase.RecordTypeId = newServiceApplicationRecordTypeId;
        testCase.Tax_Identification_No__c = '1111111';
        testCase.AccountId = testAccount.Id;
        insert testCase;
        
        Contract testContract = new Contract(AccountId = testAccount.Id,
                                             Case__c = testCase.Id,
                                             V10_Account_No__c = '12345678',
                                             Method_of_Payment__c = 'Over the Counter',
                                             Bill_Print_Mode__c = 'Paper',
                                             Type__c = 'Regular');
        insert testContract;

        //CREATE PayOps USER ACCOUNT
        Profile payOps = [SELECT Id FROM Profile WHERE Name ='Payment Operations' Limit 1];

        User payOpsUser = new User(
            Username = System.now().millisecond() + 'test12345@test.com',
            ProfileId = payOps.Id,
            Alias = 'test123',
            Email = 'test12345@test.com',
            EmailEncodingKey = 'UTF-8',
            LastName = 'McTesty',
            CommunityNickname = 'test12345',
            TimeZoneSidKey = 'America/Los_Angeles',
            LocaleSidKey = 'en_US',
            LanguageLocaleKey = 'en_US'
        );

        system.runAs(payOpsUser){
            Case apaCase = CXE_TestDataFactory.createAPACase(1, true, testContract.Id)[0];
            apaCase.CXE_APA_Attachment_Count__c = 0;
            insert apaCase;

            test.startTest();
                String result = CXE_CP_APAFileUpload_CC.updateFileCount(apaCase.Id, 1);
                System.assertEquals('SUCCESS', result);

            Case updatedCase = [SELECT CXE_APA_Attachment_Count__c 
            					FROM Case WHERE Id=:apaCase.Id LIMIT 1];
            System.assertEquals(1, updatedCase.CXE_APA_Attachment_Count__c);
            test.stopTest();
        }
	}

	@isTest static void updateFileCountTest_FAILED() {
		test.startTest();
        String result = CXE_CP_APAFileUpload_CC.updateFileCount(null, 1);
        System.assertEquals('FAILED', result);
        test.stopTest();
	}

	@isTest static void getKeyValTest() {
		List<CXE_KeyValueSetting__c> keyValSet = CXE_CP_APAFileUpload_CC.getKeyValSettings();
		System.assert(!keyValSet.isEmpty());
	}

	@isTest static void upload_signTest() {
		String sign = CXE_CP_APAFileUpload_CC.upload_sign('APADocument');
	}
	
}