src/objects/Address__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Billing_Preferences</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Address_Street_No__c</fullName>
        <label>Street #</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address__c</fullName>
        <formula>Address_Unit_No__c &amp; &quot; &quot; &amp;  Address_Street_No__c &amp; &quot; &quot; &amp; Address_Street_Name__r.Name &amp; &quot;, &quot; &amp; Address_Subdivision__r.Name &amp; &quot; &quot; &amp;  Address_Barangay__r.Name &amp; &quot;, &quot; &amp; Address_City_Municipality__r.Name &amp; &quot;, &quot; &amp;  Address_Province__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Address</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipName>Billing_Preferences</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipName>Billing_Preferences</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service</label>
        <referenceTo>Agreement__c</referenceTo>
        <relationshipName>Billing_Preferences</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Service</fullName>
                </value>
                <value>
                    <fullName>Billing</fullName>
                </value>
                <value>
                    <fullName>Customer</fullName>
                </value>
                <value>
                    <fullName>Meter</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Address</label>
    <nameField>
        <displayFormat>ADD-{000000}</displayFormat>
        <label>Address Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Agreement__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Agreements</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipName>Agreements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Code_Segment__c</fullName>
        <label>Code Segment</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contract__c</fullName>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipName>Agreements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Payor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Payor Contract of this Service</description>
        <label>Payor</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Services (Payor)</relationshipLabel>
        <relationshipName>Services_Payor</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Rate__c</fullName>
        <label>Rate</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>General Service A (GSA)</fullName>
                </value>
                <value>
                    <fullName>General Service B (GSB)</fullName>
                </value>
                <value>
                    <fullName>General Power (GP)</fullName>
                </value>
                <value>
                    <fullName>Residential Service (RS)</fullName>
                </value>
                <value>
                    <fullName>Government Hospitals, Metered Streetlights &amp; Charitable Institutions (GHMSCI)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SIN__c</fullName>
        <externalId>true</externalId>
        <label>SIN</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Segment__c</fullName>
        <label>Segment</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Corporate Business Group</fullName>
                </value>
                <value>
                    <fullName>Home and Micro Business</fullName>
                </value>
                <value>
                    <fullName>SME Business Group</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Service_Status__c</fullName>
        <label>Service Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Pending to Terminate</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Drop with service providing</fullName>
                </value>
                <value>
                    <fullName>Sleep</fullName>
                </value>
                <value>
                    <fullName>Active - Disconnected</fullName>
                </value>
                <value>
                    <fullName>Active - Pending to Disconnect</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Service_Supply_Type__c</fullName>
        <label>Service Supply Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Normal with meter</fullName>
                </value>
                <value>
                    <fullName>Streetlight with meter</fullName>
                </value>
                <value>
                    <fullName>Normal without meter</fullName>
                </value>
                <value>
                    <fullName>Temporary with meter</fullName>
                </value>
                <value>
                    <fullName>Streetlight without meter</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Service_Wire_Material__c</fullName>
        <label>Service Wire Material</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Aluminum</fullName>
                </value>
                <value>
                    <fullName>Copper</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Service_Wire_Phase__c</fullName>
        <label>Service Wire Phase</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Single Phase (1Ø), Two (2)-Wire</fullName>
                </value>
                <value>
                    <fullName>Single Phase (1Ø), Network</fullName>
                </value>
                <value>
                    <fullName>Three Phase (3Ø), Four (4)-Wire (Grounded Wye)</fullName>
                </value>
                <value>
                    <fullName>Three Phase (3Ø), Three (3)-Wire (Delta)</fullName>
                </value>
                <value>
                    <fullName>Single Phase (1Ø), Three (3)-Wire</fullName>
                </value>
                <value>
                    <fullName>Three Phase (3Ø), Four (4)-Wire (Delta)</fullName>
                </value>
                <value>
                    <fullName>Three Phase (3Ø), Four (4)-Wire (Grounded Wye/Delta)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Service</label>
    <nameField>
        <displayFormat>SERV-{00000000}</displayFormat>
        <label>Service ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Regular</fullName>
                </value>
                <value>
                    <fullName>Prepaid</fullName>
                </value>
                <value>
                    <fullName>SOLR</fullName>
                </value>
                <value>
                    <fullName>Retailer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/CXE_Service_Enrollment__c.object
<CustomObject>
    <description>Logs customer portal registrations</description>
    <fields>
        <fullName>CXE_IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Is Active?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CXE_ServiceId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service</label>
        <referenceTo>Agreement__c</referenceTo>
        <relationshipLabel>Service Enrollments</relationshipLabel>
        <relationshipName>Service_Enrollments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CXE_UserId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Portal User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Service_Enrollments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Service Enrollment</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Enrollments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Rate__c.object
<CustomObject>
    <label>Rate</label>
    <nameField>
        <displayFormat>RT{0000000000}</displayFormat>
        <label>Rate Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Reference__c.object
<CustomObject>
    <description>This contain Address, Geo Code, Picklist Value, Picklist Code</description>
    <fields>
        <fullName>Field__c</fullName>
        <externalId>true</externalId>
        <label>Field</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Name_Code__c</fullName>
        <externalId>true</externalId>
        <label>Name Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Geo</fullName>
                </value>
                <value>
                    <fullName>Picklist</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Reference</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>References</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CXE_CP_SplashPageSelfRegistration_Test.cls
@isTest
private class CXE_CP_SplashPageSelfRegistration_Test {
    
    
    
    @testSetup static void setup(){
        
        CXE_TestDataFactory.setupPortalData('2', true);
        
        
    }
      @isTest static void createUserTestFalse() {
        // Implement test code
        Test.startTest();
        
        
        CXE_CP_SplashPageSelfRegistration_CC splashPageSelfReg = new CXE_CP_SplashPageSelfRegistration_CC();
       
        
        List<User> portalUsers = [Select Id From User Where Profile.Name =: CXE_Constants.MERALCO_CUSTOMER_COMMUNITY_PROFILE];
    
        try{
            
            if(!portalUsers.isEmpty()) {
                
                System.runAs(portalUsers.get(0)){
                    String email = 'cxe_tcuser2@test.com';
                    String fName = 'mfNametc2';
                    String mName = 'mmNametc2';
                    String lName = 'mlNametc2';
                    String suffix = '';
                    String mobile = '+639999999999';
                    String sin = '293028374839';
                    Decimal amt = 300;
                    String txnDate = '2018-03-15';
                    CXE_CP_SplashPageSelfRegistration_CC.Response response =
                        CXE_CP_SplashPageSelfRegistration_CC.createUser(email, fName, mName, lName, suffix, mobile, sin, amt, txnDate, false);

                    System.assertEquals(CXE_Constants.PORTAL_REGISTRATION_SUCCESSFUL, response.message);
                }                           
                
            }
            
        } catch (Exception e) {
            System.assertEquals('', e.getMessage());
        }
        Test.stopTest();
    }
  
    
    
    
    @isTest static void createUserTestTrue() {
        // Implement test code
        Test.startTest();
        
        CXE_CP_SplashPageSelfRegistration_CC splashPageSelfReg = new CXE_CP_SplashPageSelfRegistration_CC();
        
        List<User> portalUsers = [Select Id From User Where Profile.Name =: CXE_Constants.MERALCO_CUSTOMER_COMMUNITY_PROFILE];
    
        try{
            
            if(!portalUsers.isEmpty()) {
                
                System.runAs(portalUsers.get(0)){
                    String email = 'cxe_tcuser2@test.com';
                    String fName = 'mfNametc2';
                    String mName = 'mmNametc2';
                    String lName = 'mlNametc2';
                    String suffix = '';
                    String mobile = '+639999999999';
                    String sin = '293028374839';
                    Decimal amt = 300;
                    String txnDate = '2018-03-15';
                    CXE_CP_SplashPageSelfRegistration_CC.Response response =
                        CXE_CP_SplashPageSelfRegistration_CC.createUser(email, fName, mName, lName, suffix, mobile, sin, amt, txnDate, True);
                    
                    System.assertEquals(CXE_Constants.PORTAL_REGISTRATION_ERROR_HAS_EXISTING_BILLING_RECORD, response.message);
                }                           
                
            }
            
        } catch (Exception e) {
            System.assertEquals('', e.getMessage());
        }
        Test.stopTest();
    }
    
    
    
    @isTest static void createUserDifferentProfile() {
        // Implement test code
        try{
            User adminUser = CXE_TestDataFactory.createAdminUser();
            adminUser.IsActive = true; //START/END RReyes JAN-03-18
            insert adminUser;
           // CXE_TestDataFactory.setupPortalData('3');
            List<User> portalUsers = [SELECT Id FROM User WHERE Profile.Name =: CXE_Constants.MERALCO_CUSTOMER_COMMUNITY_PROFILE];
            
            //if(!portalUsers.isEmpty()) {
                Test.startTest();
                
                System.runAs(adminUser){
                    String email = 'cxe_tcuser@test.com';
                    String fName = 'mfNametc';
                    String mName = 'mmNametc';
                    String lName = 'mlNametc';
                    String suffix = '';
                    String mobile = '+639999999999';
                    String sin = '293028374839';
                    Decimal amt = 300;
                    String txnDate = '2018-03-15';
                    CXE_CP_SplashPageSelfRegistration_CC.Response response = CXE_CP_SplashPageSelfRegistration_CC.createUser(email, fName, mName, lName, suffix, mobile, sin, amt, txnDate, false);
                    System.assertEquals(CXE_Constants.PORTAL_REGISTRATION_ERROR_HAS_SESSION, response.message);
                }
                Test.stopTest();
            //}
        } catch (Exception e) {
            System.assertEquals('', e.getMessage());
        }
    }
    
    @isTest static void createUserSinInvalidLength() {
        // Implement test code
        try{
            //CXE_TestDataFactory.setupPortalData('3');
            List<User> portalUsers = [SELECT Id FROM User WHERE Profile.Name =: CXE_Constants.MERALCO_CUSTOMER_COMMUNITY_PROFILE];
            
            if(!portalUsers.isEmpty()) {
                Test.startTest();
                
                System.runAs(portalUsers.get(0)){
                    String email = 'cxe_tcuser@test.com';
                    String fName = 'mfNametc';
                    String mName = 'mmNametc';
                    String lName = 'mlNametc';
                    String suffix = '';
                    String mobile = '+639999999999';
                    String sin = '29302837483';
                    Decimal amt = 300;
                    String txnDate = '2018-03-15';
                    CXE_CP_SplashPageSelfRegistration_CC.Response response = CXE_CP_SplashPageSelfRegistration_CC.createUser(email, fName, mName, lName, suffix, mobile, sin, amt, txnDate, false);
                    System.assertEquals(CXE_Constants.PORTAL_REGISTRATION_ERROR_SIN_INVALID_LENGTH, response.message);
                }
                Test.stopTest();
            }
        } catch (Exception e) {
            System.assertEquals('', e.getMessage());
        }
    }
    
    @isTest static void createUserHMB() {
         Test.startTest();
        // Implement test code
        try{
           // CXE_TestDataFactory.setupPortalData('1');
            List<Contact> contacts = CXE_TestDataFactory.createContact(1);
            insert contacts;
            
            
            List<User> portalUsers = [SELECT Id FROM User WHERE Profile.Name =: CXE_Constants.MERALCO_CUSTOMER_COMMUNITY_PROFILE];
            
            if(!portalUsers.isEmpty()) {
               
                
                System.runAs(portalUsers.get(0)){
                    String email = 'cxe_tcuser@test.com';
                    String fName = 'mfNametc';
                    String mName = 'mmNametc';
                    String lName = 'mlNametc';
                    String suffix = '';
                    String mobile = '+639999999999';
                    String sin = '293028374839';
                    Decimal amt = 300;
                    String txnDate = '2018-03-15';
                    CXE_CP_SplashPageSelfRegistration_CC.Response response = CXE_CP_SplashPageSelfRegistration_CC.createUser(email, fName, mName, lName, suffix, mobile, sin, amt, txnDate, false);
                    System.assertEquals(CXE_Constants.PORTAL_REGISTRATION_SUCCESSFUL, response.message);
                    
                }
               
            }
        } catch (Exception e) {
            System.assertEquals('', e.getMessage());
        }
         Test.stopTest();
    }
    
    @isTest
    static void hasBeenUsedByAnotherMethod(){
        
        Test.startTest();
        User adminUser = CXE_TestDataFactory.createAdminUser();
        adminUser.IsActive = true; //START/END RReyes JAN-03-18
        insert adminUser;
        
        //User userAd = [SELECT Id FROM User Where email='bruce.wayne@wayneenterprises.com'];
        System.runAs(adminUser){
            // CXE_TestDataFactory.setupPortalData('1');
            
            Account acct = CXE_TestDataFactory.createSingleAccountForPortalUser(adminUser.Id);
            insert acct;
            Contact  cont =CXE_TestDataFactory.createContact(acct.Id);
            insert cont;
            
            User portalUser = CXE_TestDataFactory.createPortalUser(cont.Id);
            portalUser.IsActive = true;
            insert portalUser; 
            
            System.assert(portalUser!=null);
            
            Agreement__c service =[SELECT Id FROM Agreement__c WHERE SIN__C= '293028374839' LIMIT  1]; 
            //Insert service enrollment for portal user
            CXE_Service_Enrollment__c cxe = new CXE_Service_Enrollment__c();
            cxe.CXE_ServiceId__c = service.Id;
            cxe.CXE_UserId__c = portalUser.ID;
            cxe.CXE_IsActive__c =True;
            
            insert cxe;
            
            System.assert(cxe!=null);
        }
        
        List<User> portalUsers = [SELECT Id FROM User WHERE Profile.Name =: CXE_Constants.MERALCO_CUSTOMER_COMMUNITY_PROFILE];
        System.runAs(portalUsers[0]){ //rom
            String email = 'cxe_tcuser@test.com';
            String fName = 'mfNametc';
            String mName = 'mmNametc';
            String lName = 'mlNametc';
            String suffix = '';
            String mobile = '+639999999999';
            String sin = '293028374839';
            Decimal amt = 300;
            String txnDate = '2018-03-15';
            CXE_CP_SplashPageSelfRegistration_CC.Response response = CXE_CP_SplashPageSelfRegistration_CC.hasBeenUsedByAnotherPortalAccount('293028374839');
           
        }    
        // guestPortalRegistration();
        Test.stopTest();
    }
    
  
    @isTest
    static void Wrapper_Test(){
        Test.startTest();
        List<String> errorMessages = new List<String>();
        errorMessages.add('message 1');
        errorMessages.add('message 2');
        
        CXE_CP_SplashPageSelfRegistration_CC.BillWrapper bwrap = new CXE_CP_SplashPageSelfRegistration_CC.BillWrapper(True);
        CXE_CP_SplashPageSelfRegistration_CC.BillWrapper bwrapErrorList = new CXE_CP_SplashPageSelfRegistration_CC.BillWrapper(errorMessages);
        CXE_CP_SplashPageSelfRegistration_CC.SINWrapper SINWrappers = new CXE_CP_SplashPageSelfRegistration_CC.SINWrapper(True,'caseNumber');
        CXE_CP_SplashPageSelfRegistration_CC.Response resp = new CXE_CP_SplashPageSelfRegistration_CC.Response('caseNumber');
        
        System.assert(bwrap !=null);
        System.assert(bwrapErrorList !=null);
        System.assert(SINWrappers !=null); 
        System.assert(resp !=null);
        
        Test.stopTest();
    }    
    
    @isTest
    static void InactiveSin_Test(){
        
        Test.startTest();
        
        
        Agreement__c service =[SELECT Id, Service_Status__c  FROM Agreement__c WHERE SIN__C= '293028374839' LIMIT  1]; 
        service.Service_Status__c ='Terminated';
        
        update service;
        
        CXE_CP_SplashPageSelfRegistration_CC splashPageSelfReg = new CXE_CP_SplashPageSelfRegistration_CC();
        
        List<User> portalUsers = [Select Id From User Where Profile.Name =: CXE_Constants.MERALCO_CUSTOMER_COMMUNITY_PROFILE];
        
        try{
            if(!portalUsers.isEmpty()) {
                System.runAs(portalUsers.get(0)){
                    String email = 'cxe_tcuser2@test.com';
                    String fName = 'mfNametc2';
                    String mName = 'mmNametc2';
                    String lName = 'mlNametc2';
                    String suffix = '';
                    String mobile = '+639999999999';
                    String sin = '293028374839';
                    Decimal amt = 300;
                    String txnDate = '2018-03-15';
                    CXE_CP_SplashPageSelfRegistration_CC.Response response = CXE_CP_SplashPageSelfRegistration_CC.createUser(email, fName, mName, lName, suffix, mobile, sin, amt, txnDate, false);
                    
                    System.assertEquals(CXE_Constants.PORTAL_REGISTRATION_ERROR_SIN_INACTIVE, response.message);
                }                           
                
            }
            
        } catch (Exception e) {
            System.assertEquals('', e.getMessage());
        }
        
        Test.stopTest();
        
        
    }    
    
    @isTest 
    static void hasBeenRegisteredTwice_Test(){
        
        Test.startTest();

        User adminUser = CXE_TestDataFactory.createAdminUser();
        insert adminUser;
        
        User userAd = [SELECT Id FROM User Where email='bruce.wayne@wayneenterprises.com'];
        System.runAs(userAd){
            Agreement__c serviceRec =[SELECT Id, Service_Status__c ,Code_Segment__c,Segment__c  FROM Agreement__c WHERE SIN__C= '293028374839' LIMIT  1]; 
            serviceRec.Code_Segment__c = '2';
            serviceRec.Segment__c = 'Home and Micro Business';
            
            update serviceRec;
            // CXE_TestDataFactory.setupPortalData('1');
            
            Account acct = CXE_TestDataFactory.createSingleAccountForPortalUser(userAd.Id);
            insert acct;
            Contact  cont =CXE_TestDataFactory.createContact(acct.Id);
            insert cont;
            
            User portalUser = CXE_TestDataFactory.createPortalUser(cont.Id);
            insert portalUser; 
            portalUser.CommunityNickname ='CorbesTest';
            update portalUser;
            
            System.assert(portalUser!=null);
            
            Agreement__c service =[SELECT Id FROM Agreement__c WHERE SIN__C= '293028374839' LIMIT  1]; 
            //Insert service enrollment for portal user
            CXE_Service_Enrollment__c cxe = new CXE_Service_Enrollment__c();
            cxe.CXE_ServiceId__c = service.Id;
            cxe.CXE_UserId__c = portalUser.ID;
            cxe.CXE_IsActive__c =True;
            
            insert cxe;
            
            System.assert(cxe!=null);
            
            //insert record in portal and Enrollments
            Account acct2= CXE_TestDataFactory.createSingleAccountForPortalUser(userAd.Id);
            insert acct2;
            Contact  cont2 =CXE_TestDataFactory.createContact(acct2.Id);
            insert cont2;
            
            User portalUser2 = CXE_TestDataFactory.createPortalUser(cont2.Id);
            insert portalUser2; 
           
            System.assert(portalUser2!=null);
            
            Agreement__c service2 =[SELECT Id FROM Agreement__c WHERE SIN__C= '293028374839' LIMIT  1]; 
            //Insert service enrollment for portal user
            CXE_Service_Enrollment__c cxe2 = new CXE_Service_Enrollment__c();
            cxe2.CXE_ServiceId__c = service2.Id;
            cxe2.CXE_UserId__c = portalUser2.ID;
            cxe2.CXE_IsActive__c =True;
            
            insert cxe2;
        }
        List<User> portalUsers = [Select Id From User Where Profile.Name =: CXE_Constants.MERALCO_CUSTOMER_COMMUNITY_PROFILE];
        try{
            if(!portalUsers.isEmpty()) {
                System.runAs(portalUsers.get(0)){
                    String email = 'cxe_tcuser2@test.com';
                    String fName = 'mfNametc2';
                    String mName = 'mmNametc2';
                    String lName = 'mlNametc2';
                    String suffix = '';
                    String mobile = '+639999999999';
                    String sin = '293028374839';
                    Decimal amt = 300;
                    String txnDate = '2018-03-15';
                    CXE_CP_SplashPageSelfRegistration_CC.Response response = CXE_CP_SplashPageSelfRegistration_CC.createUser(email, fName, mName, lName, suffix, mobile, sin, amt, txnDate, false);
                    
                    System.assertEquals(CXE_Constants.PORTAL_REGISTRATION_ERROR_SIN_ENROLLED_TWICE, response.message);
                }                           
                
            }
            
        } catch (Exception e) {
            System.assertEquals('', e.getMessage());
        }
        Test.stopTest();
    }
    
    @isTest
    static void hasDuplicateEmail_Test(){
        Test.startTest();
            /*
        User adminUser = CXE_TestDataFactory.createAdminUser();
        insert adminUser;
        
        User userAd = [SELECT Id FROM User Where email='bruce.wayne@wayneenterprises.com'];
        System.runAs(userAd){
            
            
            Agreement__c serviceRec =[SELECT Id, Service_Status__c ,Code_Segment__c,Segment__c  FROM Agreement__c WHERE SIN__C= '293028374839' LIMIT  1]; 
            serviceRec.Code_Segment__c = '2';
            serviceRec.Segment__c = 'Home and Micro Business';
            
            update serviceRec;
            
            // CXE_TestDataFactory.setupPortalData('1');
            
            Account acct = CXE_TestDataFactory.createSingleAccountForPortalUser(userAd.Id);
            insert acct;
            Contact  cont =CXE_TestDataFactory.createContact(acct.Id);
            insert cont;
            
            User portalUser = CXE_TestDataFactory.createPortalUser(cont.Id);
            insert portalUser; 
            portalUser.CommunityNickname ='CorbesTest';
            update portalUser;
            
            System.assert(portalUser!=null);
            
            Agreement__c service =[SELECT Id FROM Agreement__c WHERE SIN__C= '293028374839' LIMIT  1]; 
            //Insert service enrollment for portal user
            CXE_Service_Enrollment__c cxe = new CXE_Service_Enrollment__c();
            cxe.CXE_ServiceId__c = service.Id;
            cxe.CXE_UserId__c = portalUser.ID;
            cxe.CXE_IsActive__c =True;
            
            insert cxe;
            
            System.assert(cxe!=null);

        }
       */
        List<User> portalUsers = [Select Id From User Where Profile.Name =: CXE_Constants.MERALCO_CUSTOMER_COMMUNITY_PROFILE];
        try{
            if(!portalUsers.isEmpty()) {
                System.runAs(portalUsers.get(0)){
                    String email = 'test12345@test.com';
                    String fName = 'mfNametc2';
                    String mName = 'mmNametc2';
                    String lName = 'mlNametc2';
                    String suffix = '';
                    String mobile = '+639999999999';
                    String sin = '293028374839';
                    Decimal amt = 300;
                    String txnDate = '2018-03-15';
                    CXE_CP_SplashPageSelfRegistration_CC.Response response = CXE_CP_SplashPageSelfRegistration_CC.createUser(email, fName, mName, lName, suffix, mobile, sin, amt, txnDate, false);
                    CXE_CP_SplashPageSelfRegistration_CC.Response response1 = CXE_CP_SplashPageSelfRegistration_CC.createUser(email, fName, mName, lName, suffix, mobile, sin, amt, txnDate, false);
                   
                    System.assertEquals( CXE_Constants.PORTAL_REGISTRATION_ERROR_DUPLICATE_EMAIL, response1.message);
                }                           
            }
        } catch (Exception e) {
            System.assertEquals('', e.getMessage());
        }
        Test.stopTest();
    }
    
    @isTest 
    static void testforCatchError(){
        
        
        Test.startTest();
        User adminUser = CXE_TestDataFactory.createAdminUser();
        insert adminUser;
        
        User userAd = [SELECT Id FROM User Where email='bruce.wayne@wayneenterprises.com'];
        System.runAs(userAd){
         
            Agreement__c service =[SELECT Id, Payor__c  
                                   FROM Agreement__c WHERE SIN__C= '293028374839' LIMIT  1]; 
            
            service.Payor__c =null;

            update service;
            
            System.assertEquals(false, service.Payor__r.Account.IsPersonAccount);    
            
        }
        //create new Account
        
        List<User> portalUsers = [Select Id From User Where Profile.Name =: CXE_Constants.MERALCO_CUSTOMER_COMMUNITY_PROFILE];
        
        try{
            
            if(!portalUsers.isEmpty()) {
                
                
                
                System.runAs(portalUsers.get(0)){
                    String email = 'cxe_tcuser2@test.com';
                    String fName = 'mfNametc2';
                    String mName = 'mmNametc2';
                    String lName = 'mlNametc2';
                    String suffix = '';
                    String mobile = '+639999999999';
                    String sin = '293028374839';
                    Decimal amt = 300;
                    String txnDate = '2018-03-15';
                    CXE_CP_SplashPageSelfRegistration_CC.Response response = CXE_CP_SplashPageSelfRegistration_CC.createUser(email, fName, mName, lName, suffix, mobile, sin, amt, txnDate, false);
                    
                   
                }                           
                
            }
            
        } catch (Exception e) {
            System.assert(e.getMessage()!=null) ;
        }
        Test.stopTest();
    }



     @isTest static void createCaseTest() {
        // Implement test code
        Test.startTest();
        
        CXE_CP_SplashPageSelfRegistration_CC splashPageSelfReg = new CXE_CP_SplashPageSelfRegistration_CC();
        
        List<User> portalUsers = [Select Id From User Where Profile.Name =: CXE_Constants.MERALCO_CUSTOMER_COMMUNITY_PROFILE];
    
        try{
            if(!portalUsers.isEmpty()) {
                Agreement__c service = [SELECT Code_Segment__c, Segment__c, Account__c, Case__c,
                                               Payor__c
                                        FROM Agreement__c WHERE SIN__C = '293028374839'];
                
                delete [SELECT Id FROM Agreement__c WHERE Id = :service.Id];


                List<Agreement__c> createService = CXE_TestDataFactory.createServiceWithLessDetails(1, service.Account__c, service.Case__c,
                                                                service.Payor__c,'');
        
              
                createService[0].Code_Segment__c = '3';
                createService[0].Segment__c = 'SME Business Group';
                createService[0].SIN__c = '293028374839';
                insert createService;

                System.runAs(portalUsers.get(0)){
                    String email = 'cxe_tcuser2@test.com';
                    String fName = 'mfNametc2';
                    String mName = 'mmNametc2';
                    String lName = 'mlNametc2';
                    String suffix = '';
                    String mobile = '+639999999999';
                    String sin = '293028374839';
                    Decimal amt = 300;
                    String txnDate = '2018-03-15';
                    CXE_CP_SplashPageSelfRegistration_CC.Response response =
                        CXE_CP_SplashPageSelfRegistration_CC.createUser(email, fName, mName, lName, suffix, mobile, sin, amt, txnDate, false);

                    System.assert(String.isNotBlank(response.caseNumber));
                }                           
            }
        } catch (Exception e) {
            System.assertEquals('', e.getMessage());
        }
        Test.stopTest();
    }


    @isTest static void createIROTest() {
        // Implement test code
        Test.startTest();
        
        CXE_CP_SplashPageSelfRegistration_CC splashPageSelfReg = new CXE_CP_SplashPageSelfRegistration_CC();
        
        List<User> portalUsers = [Select Id From User Where Profile.Name =: CXE_Constants.MERALCO_CUSTOMER_COMMUNITY_PROFILE];
    
        try{
            if(!portalUsers.isEmpty()) {
                Agreement__c service = [SELECT Code_Segment__c, Segment__c, Account__c, Case__c,
                                               Payor__c
                                        FROM Agreement__c WHERE SIN__C = '293028374839'];
                
                delete [SELECT Id FROM Agreement__c WHERE Id = :service.Id];
                delete [SELECT Id FROM Case WHERE Id = :service.Case__c];
                
                
                Agreement__c serviceNew = new Agreement__c();
                serviceNew.Account__c = service.Account__c;
                serviceNew.Contract__c = service.Payor__c;
                serviceNew.Payor__c = service.Payor__c;
                serviceNew.Rate__c = 'General Service A (GSA)';
                serviceNew.Segment__c = 'Home and Micro Business';
                serviceNew.Service_Status__c = 'Active';
                serviceNew.Service_Supply_Type__c = 'Normal with meter';
                serviceNew.Service_Wire_Material__c = 'Copper';
                serviceNew.Service_Wire_Phase__c = 'Single Phase (1Ø), Network';
                serviceNew.Code_Segment__c = '3';
                serviceNew.Segment__c = 'SME Business Group';
                serviceNew.SIN__c = '293028374839';
                insert serviceNew;

                Map<String, Reference__c> addressReference = new Map<String, Reference__c>();
                for(Reference__c addRef : [SELECT Id, Field__c, Name_Code__c FROM Reference__c]) {
                    addressReference.put(addRef.Field__c, addRef);
                }

                Address__c createAddress = CXE_TestDataFactory.createAddress(addressReference, true);
                createAddress.Type__c = 'Service';
                createAddress.Service__c = serviceNew.Id;
                createAddress.Address_Street_No__c = '1'; 
                insert createAddress;

                System.runAs(portalUsers.get(0)){
                    String email = 'cxe_tcuser2@test.com';
                    String fName = 'mfNametc2';
                    String mName = 'mmNametc2';
                    String lName = 'mlNametc2';
                    String suffix = '';
                    String mobile = '+639999999999';
                    String sin = '293028374839';
                    Decimal amt = 300;
                    String txnDate = '2018-03-15';
                    CXE_CP_SplashPageSelfRegistration_CC.Response response =
                        CXE_CP_SplashPageSelfRegistration_CC.createUser(email, fName, mName, lName, suffix, mobile, sin, amt, txnDate, false);

                    System.assert(String.isNotBlank(response.caseNumber));
                }                           
            }
        } catch (Exception e) {
            System.assertEquals('', e.getMessage());
        }
        Test.stopTest();
    }


    @isTest static void sendCBGRMEmailTest() {
        // Implement test code
        Test.startTest();
        
        CXE_CP_SplashPageSelfRegistration_CC splashPageSelfReg = new CXE_CP_SplashPageSelfRegistration_CC();
        
        List<User> portalUsers = [Select Id From User Where Profile.Name =: CXE_Constants.MERALCO_CUSTOMER_COMMUNITY_PROFILE];
    
        try{
            if(!portalUsers.isEmpty()) {
                Agreement__c service = [SELECT Code_Segment__c, Segment__c, Account__c, Case__c,
                                               Payor__c, Payor__r.Account.Owner.Name
                                        FROM Agreement__c WHERE SIN__C = '293028374839'];
                
                delete [SELECT Id FROM Agreement__c WHERE Id = :service.Id];
                delete [SELECT Id FROM Case WHERE Id = :service.Case__c];
                
                
                Agreement__c serviceNew = new Agreement__c();
                serviceNew.Account__c = service.Account__c;
                serviceNew.Contract__c = service.Payor__c;
                serviceNew.Payor__c = service.Payor__c;
                serviceNew.Rate__c = 'General Service A (GSA)';
                serviceNew.Segment__c = 'Home and Micro Business';
                serviceNew.Service_Status__c = 'Active';
                serviceNew.Service_Supply_Type__c = 'Normal with meter';
                serviceNew.Service_Wire_Material__c = 'Copper';
                serviceNew.Service_Wire_Phase__c = 'Single Phase (1Ø), Network';
                serviceNew.Code_Segment__c = '1';
                serviceNew.Segment__c = 'Corporate Business Group';
                serviceNew.SIN__c = '293028374839';
                insert serviceNew;

                Map<String, Reference__c> addressReference = new Map<String, Reference__c>();
                for(Reference__c addRef : [SELECT Id, Field__c, Name_Code__c FROM Reference__c]) {
                    addressReference.put(addRef.Field__c, addRef);
                }

                Address__c createAddress = CXE_TestDataFactory.createAddress(addressReference, true);
                createAddress.Type__c = 'Service';
                createAddress.Service__c = serviceNew.Id;
                createAddress.Address_Street_No__c = '1'; 
                insert createAddress;

                System.runAs(portalUsers.get(0)){
                    String email = 'cxe_tcuser2@test.com';
                    String fName = 'mfNametc2';
                    String mName = 'mmNametc2';
                    String lName = 'mlNametc2';
                    String suffix = '';
                    String mobile = '+639999999999';
                    String sin = '293028374839';
                    Decimal amt = 300;
                    String txnDate = '2018-03-15';
                    CXE_CP_SplashPageSelfRegistration_CC.Response response =
                        CXE_CP_SplashPageSelfRegistration_CC.createUser(email, fName, mName, lName, suffix, mobile, sin, amt, txnDate, false);

                    System.assertEquals(String.format(CXE_Constants.PORTAL_REGISTRATION_ERROR_SIN_CBG_ACCOUNT, new List<String>{ service.Payor__r.Account.Owner.Name }), response.message);
                }                           
            }
        } catch (Exception e) {
            System.assertEquals('', e.getMessage());
        }
        Test.stopTest();
    }
       
    
    
}