src/objects/Address__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Billing_Preferences</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Address__c</fullName>
        <formula>Address_Unit_No__c &amp; &quot; &quot; &amp;  Address_Street_No__c &amp; &quot; &quot; &amp; Address_Street_Name__r.Name &amp; &quot;, &quot; &amp; Address_Subdivision__r.Name &amp; &quot; &quot; &amp;  Address_Barangay__r.Name &amp; &quot;, &quot; &amp; Address_City_Municipality__r.Name &amp; &quot;, &quot; &amp;  Address_Province__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Address</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipName>Billing_Preferences</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service</label>
        <referenceTo>Agreement__c</referenceTo>
        <relationshipName>Billing_Preferences</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Address</label>
    <nameField>
        <displayFormat>ADD-{000000}</displayFormat>
        <label>Address Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Agreement__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Agreements</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Payor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Payor Contract of this Service</description>
        <label>Payor</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Services (Payor)</relationshipLabel>
        <relationshipName>Services_Payor</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SIN__c</fullName>
        <externalId>true</externalId>
        <label>SIN</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Service_Status__c</fullName>
        <label>Service Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Pending to Terminate</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Drop with service providing</fullName>
                </value>
                <value>
                    <fullName>Sleep</fullName>
                </value>
                <value>
                    <fullName>Active - Disconnected</fullName>
                </value>
                <value>
                    <fullName>Active - Pending to Disconnect</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>V10_Account_No__c</fullName>
        <label>V10 Account #</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Service</label>
    <nameField>
        <displayFormat>SERV-{00000000}</displayFormat>
        <label>Service ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Bill_Print_Mode__c</fullName>
        <label>Bill Print Mode</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>BILPRNT001</fullName>
                    <default>true</default>
                    <label>Paper</label>
                </value>
                <value>
                    <fullName>BILPRNT003</fullName>
                    <label>Paperless</label>
                </value>
                <value>
                    <fullName>BILPRNT002</fullName>
                    <label>Paperplus</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contract_External_ID__c</fullName>
        <externalId>true</externalId>
        <label>Contract External ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>V10_Account_No__c</fullName>
        <externalId>true</externalId>
        <label>Legacy Account Number</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/CXE_Service_Enrollment__c.object
<CustomObject>
    <description>Logs customer portal registrations</description>
    <fields>
        <fullName>CXE_Alias__c</fullName>
        <label>Alias</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CXE_IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Is Active?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CXE_ServiceId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service</label>
        <referenceTo>Agreement__c</referenceTo>
        <relationshipLabel>Service Enrollments</relationshipLabel>
        <relationshipName>Service_Enrollments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CXE_Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Payor</fullName>
                </value>
                <value>
                    <fullName>Non-Payor</fullName>
                </value>
                <value>
                    <fullName>Tenant</fullName>
                    <isActive>false</isActive>
                    <label>Tenant</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CXE_Unenrollment_Date__c</fullName>
        <label>Unenrollment Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>CXE_UserId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Portal User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Service_Enrollments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Service Enrollment</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Enrollments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CXE_CP_MyAccountsAccountDetail.cls
public without sharing class CXE_CP_MyAccountsAccountDetail { //CSM-12485 GGrandea 09.08.2017 - changed to "without sharing"
    
    @AuraEnabled
    public static String checkSinToDelete(String myAccount, String mySin){ //CXE_CP_PortalUtility.PortalData
        String returnMsg = 'error';
        String RTN_MSG_PAPERLESS = 'PAPERLESS';
        String RTN_MSG_PAYOR = 'PAYOR';
        String RTN_MSG_SUCCESS = 'SUCCESS';
        
        try{
            
            //GET SIN BILL PRINT MODE THRU AGREEMENT__c /PAPER, PAPERLESS, AND ETC.
            List<Agreement__c> checkBillPrintMode= [SELECT payor__r.Bill_Print_Mode__c
                                                      , Payor__c //CSM-12359
                                                    FROM Agreement__c WHERE SIN__c =: mySin];
            
            if(!checkBillPrintMode.isEmpty()){
                
                String billPrintMode = String.ValueOf(checkBillPrintMode[0].payor__r.Bill_Print_Mode__c);
                
                if (billPrintMode == CXE_Constants.BPM_PAPERLESS){
                    
                    returnMsg = RTN_MSG_PAPERLESS;    
                    
                } else {
                    
                    //GET SPECIFIC SIN UNDER THE USER
                    List<CXE_Service_Enrollment__c> listofEnrollments = [Select Id, CXE_ServiceId__c, CXE_Alias__c, CXE_IsActive__c , CXE_Unenrollment_Date__c, CXE_Type__c
                                                                         , CXE_ServiceId__r.SIN__c
                                                                         , CXE_ServiceId__r.Account__c
                                                                         , CXE_ServiceId__r.Payor__c
                                                                         , CXE_ServiceId__r.Payor__r.V10_Account_No__c
                                                                         From CXE_Service_Enrollment__c 
                                                                         Where CXE_UserId__c=:UserInfo.getUserId() 
                                                                         AND CXE_ServiceId__r.SIN__c =: mySin
                                                                         //START - CSM-13024 JRances Added CXE_IsActive__c for filtering to get only Active SIN for unenrollment
                                                                         AND CXE_IsActive__c = True
                                                                         //END - CSM-13024 JRances
                                                                        ];
                    
                    if(!listofEnrollments.isEmpty()){
                        
                        //START CSM-12359 GGrandea 09.20.2017
                        //GET ALL THE SIN THE USER ENROLLED, AND SELECTING THE SIN NEEDED FOR DELETION
                        /*List<Agreement__c> listofServiceAgreements = [Select ID ,Payor__c,Payor__r.V10_Account_No__c, SIN__c,Account__c,Service_Status__c
                                                                      ,(Select Address__c from Billing_Preferences__r) 
                                                                      from Agreement__c 
                                                                      where Account__c =: listofEnrollments[0].CXE_ServiceId__r.Account__c
                                                                      AND SIN__c =: mySin];
                        
                        String AcctServiceAgreement = String.ValueOf(listofServiceAgreements[0].Account__c);
                        String AcctEnrollment = String.ValueOf(listofEnrollments[0].CXE_ServiceId__r.Account__c);
                        String sinType = String.ValueOf(listofEnrollments[0].CXE_Type__c); */
                        
                        //if(sinType == CXE_Constants.SERVICE_ENROLLMENT_TYPE_PAYOR){
                        if(listofEnrollments[0].CXE_Type__c==CXE_Constants.SERVICE_ENROLLMENT_TYPE_PAYOR){
                        //END CSM-12359 GGrandea 09.20.2017
                            
                            returnMsg = RTN_MSG_PAYOR;
                            
                        } else {
                            
                            //if(AcctServiceAgreement == AcctEnrollment){ //CSM-12359 disabled IF

                                // integration comes first before DML
                                //vincent V10 integration

                                //START CSM-12877 GGrandea 09.22.2017 disable BillPrintMode invocation from this class
                                /*List<CXE_Service_Enrollment__c> listofRelatedAccounts = [Select Id, CXE_ServiceId__c, CXE_Alias__c, CXE_IsActive__c , CXE_Unenrollment_Date__c, CXE_Type__c
                                                                                         , CXE_ServiceId__r.SIN__c
                                                                                         , CXE_ServiceId__r.Account__c
                                                                                         , CXE_ServiceId__r.Payor__r.V10_Account_No__c
                                                                                         From CXE_Service_Enrollment__c 
                                                                                         //Where CXE_ServiceId__r.SIN__c =: mySin //CSM-12359
                                                                                         WHERE CXE_ServiceId__r.Payor__c =: checkBillPrintMode[0].Payor__c //CSM-12359
                                                                                         and CXE_IsActive__c = true
                                                                                         AND Id != :listofEnrollments[0].Id
                                                                                        ];*/
                                //END CSM-12877 GGrandea 09.22.2017 disable BillPrintMode invocation from this class

                                //START CSM-12359 GGrandea 09.20.2017
                                /*List<CXE_Service_Enrollment__c> checkType = [Select Id,CXE_Type__c 
                                                                                           From CXE_Service_Enrollment__c
                                                                                           Where Id =: listofEnrollments[0].Id];*/
                                //END CSM-12359 GGrandea 09.20.2017
                                
                                //START CSM-12877 GGrandea 09.22.2017 disable BillPrintMode invocation from this class
                                /*system.debug('hereiam: ' + listofRelatedAccounts.size());
                                system.debug('billPrintMode: ' + billPrintMode);
                                if (billPrintMode == CXE_Constants.BPM_PAPERPLUS && listofRelatedAccounts.size() == 0){
                                    
                                    List<Contract> contractRecords = [Select Id,Contract_External_ID__c,Bill_Print_Mode__c
                                                                      from Contract 
                                                                      where id=:listofEnrollments[0].CXE_ServiceId__r.Payor__c];
                                    
                                    system.debug('>>>>>>>>>>>>>>>>>>>>>>>>>>>here'+contractRecords);
                                    
                                    system.debug('8/11/2017' + contractRecords.size());
                                    //START CSM-12359 GGrandea 09.20.2017
                                    //if(contractRecords.size() > 0 && checkType[0].CXE_Type__c == 'Payor'){
                                    if(contractRecords.size() > 0){
                                    //END CSM-12359 GGrandea 09.20.2017
                                        system.debug('8/11/2017' + contractRecords.size());
                                        CXE_CP_BillPrintModeIntegrationUtility.printmodeUpdateRequest (contractRecords , CXE_Constants.BPM_PAPER);
                                    } 
                                }*/
                                //END CSM-12877 GGrandea 09.22.2017 disable BillPrintMode invocation from this class
                                
                                
                                listofEnrollments[0].CXE_IsActive__c = false;
                                listofEnrollments[0].CXE_Unenrollment_Date__c = System.now();
                                update listofEnrollments[0];
                                
                                
                                returnMsg = RTN_MSG_SUCCESS;  
                                
                            //} //CSM-12359
                        }
                    }
                }
            }
            
        } catch(exception e){
            returnMsg = e.getMessage();
                ErrorHandlerException.recordException(null, true, 'CXE_CP_MyAccountsAccountDetail', 'checkSinToDelete', e.getMessage());
        }
        
        return returnMsg;
    }
}