src/objects/Address__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Billing_Preferences</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Address__c</fullName>
        <formula>Address_Unit_No__c &amp; &quot; &quot; &amp;  Address_Street_No__c &amp; &quot; &quot; &amp; Address_Street_Name__r.Name &amp; &quot;, &quot; &amp; Address_Subdivision__r.Name &amp; &quot; &quot; &amp;  Address_Barangay__r.Name &amp; &quot;, &quot; &amp; Address_City_Municipality__r.Name &amp; &quot;, &quot; &amp;  Address_Province__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Address</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Service</fullName>
                </value>
                <value>
                    <fullName>Billing</fullName>
                </value>
                <value>
                    <fullName>Customer</fullName>
                </value>
                <value>
                    <fullName>Meter</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Address</label>
    <nameField>
        <displayFormat>ADD-{000000}</displayFormat>
        <label>Address Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Barangay__c</fullName>
        <label>Barangay</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City_Municipality__c</fullName>
        <label>City / Municipality</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Province__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>City_Municipality</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Province__c</fullName>
        <label>Province</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Province</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Street_Name__c</fullName>
        <label>Street Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street_No__c</fullName>
        <label>House #</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subdivision__c</fullName>
        <label>Subdivision / Bldg Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unit_No__c</fullName>
        <label>Unit #</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Reference__c.object
<CustomObject>
    <description>This contain Address, Geo Code, Picklist Value, Picklist Code</description>
    <fields>
        <fullName>Block__c</fullName>
        <label>Block</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Field__c</fullName>
        <externalId>true</externalId>
        <label>Field</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Name_Code__c</fullName>
        <externalId>true</externalId>
        <label>Name Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent</label>
        <referenceTo>Reference__c</referenceTo>
        <relationshipName>Picklist_Codes_Transformation</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Geo</fullName>
                </value>
                <value>
                    <fullName>Picklist</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Reference</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>References</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/City_Municipality.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>ALAMINOS</fullName>
    </customValue>
    <customValue>
        <fullName>ALFONSO</fullName>
    </customValue>
    <customValue>
        <fullName>AMADEO</fullName>
    </customValue>
    <customValue>
        <fullName>ANGAT</fullName>
    </customValue>
    <customValue>
        <fullName>ANGONO</fullName>
    </customValue>
    <customValue>
        <fullName>ANTIPOLO</fullName>
    </customValue>
    <customValue>
        <fullName>APALIT</fullName>
    </customValue>
    <customValue>
        <fullName>BACOOR</fullName>
    </customValue>
    <customValue>
        <fullName>BALAGTAS</fullName>
    </customValue>
    <customValue>
        <fullName>BALIUAG</fullName>
    </customValue>
    <customValue>
        <fullName>BARAS</fullName>
    </customValue>
    <customValue>
        <fullName>BATANGAS CITY</fullName>
    </customValue>
    <customValue>
        <fullName>BAY</fullName>
    </customValue>
    <customValue>
        <fullName>BINAN</fullName>
    </customValue>
    <customValue>
        <fullName>BINANGONAN</fullName>
    </customValue>
    <customValue>
        <fullName>BOCAUE</fullName>
    </customValue>
    <customValue>
        <fullName>BULACAN</fullName>
    </customValue>
    <customValue>
        <fullName>BUSTOS</fullName>
    </customValue>
    <customValue>
        <fullName>CABUYAO</fullName>
    </customValue>
    <customValue>
        <fullName>CAINTA</fullName>
    </customValue>
    <customValue>
        <fullName>CALAMBA</fullName>
    </customValue>
    <customValue>
        <fullName>CALAUAN</fullName>
    </customValue>
    <customValue>
        <fullName>CALOOCAN CITY</fullName>
    </customValue>
    <customValue>
        <fullName>CALUMPIT</fullName>
    </customValue>
    <customValue>
        <fullName>CANDABA</fullName>
    </customValue>
    <customValue>
        <fullName>CANDELARIA</fullName>
    </customValue>
    <customValue>
        <fullName>CARDONA</fullName>
    </customValue>
    <customValue>
        <fullName>CARMONA</fullName>
    </customValue>
    <customValue>
        <fullName>CAVITE CITY</fullName>
    </customValue>
    <customValue>
        <fullName>DASMARINAS CITY</fullName>
    </customValue>
    <customValue>
        <fullName>MARIKINA</fullName>
    </customValue>
    <customValue>
        <fullName>SAN JOSE</fullName>
    </customValue>
    <masterLabel>City/ Municipality</masterLabel>
</GlobalValueSet>

src/globalValueSets/Province.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>BATANGAS</fullName>
    </customValue>
    <customValue>
        <fullName>BULACAN</fullName>
    </customValue>
    <customValue>
        <fullName>METRO MANILA</fullName>
    </customValue>
    <customValue>
        <fullName>CAVITE</fullName>
    </customValue>
    <customValue>
        <fullName>LAGUNA</fullName>
    </customValue>
    <customValue>
        <fullName>RIZAL</fullName>
    </customValue>
    <customValue>
        <fullName>QUEZON</fullName>
    </customValue>
    <customValue>
        <fullName>PAMPANGA</fullName>
    </customValue>
    <customValue>
        <fullName>NUEVA ECIJA</fullName>
    </customValue>
    <customValue>
        <fullName>FLAT STREETLIGHT</fullName>
    </customValue>
    <masterLabel>Province</masterLabel>
</GlobalValueSet>

src/classes/LeadTriggerHandler_Test.cls
/* Description: CaseTriggerHandler test class
 * Author: Von Pernicia
 * Date Created: MAR-07-17
 *               MAR-31-17      Jerome To       Refactored/Updated test class for test coverage
 */             
@isTest
private class LeadTriggerHandler_Test {

    static testMethod void createAddressForConvertedAccounts_Test() {   

        // create References
        List<Reference__c> addressRefList = CXE_TestDataFactory.createSampleReferenceListForAddress();
        insert addressRefList;
        for(Integer i=0 ; i<addressRefList.size() ; i++) {
            if(i>0){
                addressRefList.get(i).Parent__c = addressRefList.get(i-1).Id;
            }
        }
        update addressRefList;
        //create qualified leads
        List<Lead> leadList1 = CXE_TestDataFactory.createCreateLead(1);
        for(Lead leadRec : leadList1) {
            leadRec.Status = 'Qualified';
            leadRec.Phone = '+63464736453';
            leadRec.Unit_No__c = '1';
            leadRec.Street_No__c = '1';
            leadRec.Street_Name__c = addressRefList.get(4).Name;
            leadRec.Subdivision__c = addressRefList.get(3).Name;
            leadRec.Barangay__c = addressRefList.get(2).Name;
            leadRec.City_Municipality__c = addressRefList.get(1).Name;
            leadRec.Province__c = addressRefList.get(0).Name;
        }
        insert leadList1;

        // create address 2 with different Steet Name
        //List<Reference__c> secondAddressRefList = CXE_TestDataFactory.createSampleReferenceListForAddress();
        //secondAddressRefList.remove(secondAddressRefList.size()-1);
        //secondAddressRefList.add(new Reference__c (Block__c='BATANGAS',                                  
        //                                           Field__c='Street',                                   
        //                                           Name='SAN ROQUE',
        //                                           Name_Code__c='01029001700002',                                   
        //                                           Type__c='Geo'));
        //insert secondAddressRefList;
        //for(Integer i=0 ; i<secondAddressRefList.size() ; i++) {
        //    if(i>0){
        //        secondAddressRefList.get(i).Parent__c = secondAddressRefList.get(i-1).Id;
        //    }
        //}
        //update secondAddressRefList;

        //// create address 3 with different City and Province
        List<Reference__c> thirdAddressRefList = CXE_TestDataFactory.createSampleReferenceListForAddress();
        thirdAddressRefList.remove(addressRefList.size()-1);
        thirdAddressRefList.add(new Reference__c (Block__c='METRO MANILA',                                  
                                                   Field__c='Street',                                   
                                                   Name='SAN ROQUE',
                                                   Name_Code__c='01029001700002',                                   
                                                   Type__c='Geo'));
        insert thirdAddressRefList;
        for(Integer i=0 ; i<thirdAddressRefList.size() ; i++) {
            if(i>0){
                thirdAddressRefList.get(i).Parent__c = thirdAddressRefList.get(i-1).Id;
            }
            if(i == 0){ // PROVINCE
                thirdAddressRefList.get(i).Name = 'METRO MANILA';
            }
            //if(i == 1){ // CITY             
            //    thirdAddressRefList.get(i).Name = 'MARIKINA';
            //}
            if(i == 2){ // BARANGAY             
                thirdAddressRefList.get(i).Name = 'SUMULONG';
            }
            thirdAddressRefList.get(i).Block__c = 'METRO MANILA';
        }
        update thirdAddressRefList;

        List<Reference__c> fourthAddressRefList = CXE_TestDataFactory.createSampleReferenceListForAddress();
        fourthAddressRefList.remove(addressRefList.size()-1);
        fourthAddressRefList.add(new Reference__c (Block__c='METRO MANILA',                                  
                                                   Field__c='Street',                                   
                                                   Name='SAN ROQUE',
                                                   Name_Code__c='01029001700002',                                   
                                                   Type__c='Geo'));
        insert fourthAddressRefList;
        for(Integer i=0 ; i<fourthAddressRefList.size() ; i++) {
            if(i>0){
                fourthAddressRefList.get(i).Parent__c = fourthAddressRefList.get(i-1).Id;
            }
            if(i == 0){ // PROVINCE
                fourthAddressRefList.get(i).Name = 'METRO MANILA';
            }
            if(i == 1){ // CITY             
                thirdAddressRefList.get(i).Name = 'MARIKINA';
            }
            if(i == 2){ // BARANGAY             
                fourthAddressRefList.get(i).Name = 'SUMULONG';
            }
            if(i == 3){ // SUBDIVISION             
                fourthAddressRefList.get(i).Name = 'MARIKINA HEIGHTS';
            }

            fourthAddressRefList.get(i).Block__c = 'METRO MANILA';
        }
        update fourthAddressRefList;

        List<Reference__c> fifthAddress = CXE_TestDataFactory.createSampleReferenceListForAddress();
       	fifthAddress.remove(addressRefList.size()-1); 
       	fifthAddress.add(new Reference__c (Block__c='BULACAN',                                  
                                                   Field__c='Street',                                   
                                                   Name='SAN JOSE',
                                                   Name_Code__c='01029001700002',                                   
                                                   Type__c='Geo'));
       	for(Integer i=0 ; i<fifthAddress.size() ; i++) {
            if(i>0){
                fifthAddress.get(i).Parent__c = fifthAddress.get(i-1).Id;
            }
            if(i == 0){ // PROVINCE
                fifthAddress.get(i).Name = 'BULACAN';
            }
            if(i == 1){ // CITY             
                fifthAddress.get(i).Name = 'MARIKINA';
            }
            if(i == 2){ // BARANGAY             
                fifthAddress.get(i).Name = 'SUMULONG';
            }
            if(i == 3){ // SUBDIVISION             
                fifthAddress.get(i).Name = 'MARIKINA HEIGHTS';
            }
            fifthAddress.get(i).Block__c = 'BULACAN';
        }
        insert fifthAddress;

        List<Reference__c> sixth = CXE_TestDataFactory.createSampleReferenceListForAddress();
       	sixth.remove(addressRefList.size()-1); 
       	sixth.add(new Reference__c (Block__c='BATANGAS',                                  
                                                   Field__c='Street',                                   
                                                   Name='STA. MESA',
                                                   Name_Code__c='01029001700002',                                   
                                                   Type__c='Geo'));
       	for(Integer i=0 ; i<sixth.size() ; i++) {
            if(i>0){
                sixth.get(i).Parent__c = sixth.get(i-1).Id;
            }
            
            if(i == 1){ // CITY             
                sixth.get(i).Name = 'PARANG';
            }
            
            if(i == 3){ // SUBDIVISION             
                sixth.get(i).Name = 'MARIKINA HEIGHTS';
            }
            sixth.get(i).Block__c = 'BATANGAS';
        }
        insert sixth;


        Set<Id> accountIdsWithAddress = new Set<Id>();
        Set<Id> accountIds = new Set<Id>();
        List<Lead> leadList = [SELECT Id FROM Lead WHERE Status='Qualified'];
        System.assertEquals(0, [SELECT Id FROM Address__c].size());
        System.assertEquals(0, [SELECT Id FROM Account].size());
        LeadStatus leadStatus = [SELECT Id, MasterLabel FROM LeadStatus WHERE IsConverted=true LIMIT 1];
        Test.startTest();
        if(!leadList.isEmpty()) {
            list<Database.LeadConvert> leadConverts = new list<Database.LeadConvert>();
            for(Lead leadRec : leadList) {
                Database.LeadConvert lc = new database.LeadConvert();
                lc.setLeadId(leadRec.Id);
                lc.setDoNotCreateOpportunity(TRUE);
                lc.setConvertedStatus(leadStatus.MasterLabel);
                leadConverts.add(lc);
            }           
            List<Database.LeadConvertResult> lcrList = Database.convertLead(leadConverts, false);
            if(!lcrList.isEmpty()) {
                for(Database.LeadConvertResult lc : lcrList){
                    
                    if(lc.isSuccess()) {
                        accountIds.add(lc.getAccountId());
                    } else {
                        String errors = '';             
                        List<String> errorList = new List<String>();
                        for(Database.Error err : lc.getErrors()) {
                            //errors += err.getStatusCode() + ': ' + err.getMessage();
                            errorList.add(err.getMessage());
                            //errors += CXE_Constants.CASE_APPLICATION_ERROR_MESSAGE_STRING2 + err.getFields();
                        }
                        errors += String.join(errorList, '');
                        System.assertEquals(TRUE, lc.isSuccess(), errors);
                    }
                }
                if(!accountIds.isEmpty()) {
                    List<Address__c> addressList = [SELECT Account__c FROM Address__c WHERE Account__c IN:accountIds];
                    if(!addressList.isEmpty()) {
                        for(Address__c addressRec : addressList) {
                            accountIdsWithAddress.add(addressRec.Account__c);
                        }
                    }
                }
            }
            
        }
        Test.stopTest();
        System.assertEquals(accountIds.size(), accountIdsWithAddress.size());
        System.assertEquals(accountIdsWithAddress.size(), [SELECT Id FROM Address__c].size());
    }

    static testMethod void runOtherMethods() {   
        List<Lead> leadList = [SELECT Id FROM Lead WHERE Status='Qualified'];
        if(!leadList.isEmpty()) {
            delete leadList;
            System.assertEquals(0, [SELECT Id FROM Lead WHERE Status='Qualified'].size());
            undelete leadList;
            System.assertEquals(leadList.size(), [SELECT Id FROM Lead WHERE Status='Qualified'].size());
        }
    }

    static testMethod void forceRunUninvokedEvents() {   
        LeadTriggerHandler l = new LeadTriggerHandler();
        l.BeforeDelete(null);
        l.AfterDelete(null);
        l.AfterUndelete(null);
    }
    
}