src/objects/Address__c.object
<CustomObject>
    <fields>
        <fullName>Address_Barangay__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Barangay</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Reference__c.Field__c</field>
                <operation>equals</operation>
                <value>Barangay</value>
            </filterItems>
            <filterItems>
                <field>Reference__c.Parent__c</field>
                <operation>equals</operation>
                <valueField>$Source.Address_City_Municipality__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Reference__c</referenceTo>
        <relationshipLabel>Addresses (Barangay)</relationshipLabel>
        <relationshipName>Addresses2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Address_City_Municipality__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>City / Municipality</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Reference__c.Field__c</field>
                <operation>equals</operation>
                <value>City</value>
            </filterItems>
            <filterItems>
                <field>Reference__c.Parent__c</field>
                <operation>equals</operation>
                <valueField>$Source.Address_Province__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Reference__c</referenceTo>
        <relationshipLabel>Addresses (City / Municipality)</relationshipLabel>
        <relationshipName>Addresses1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Address_Province__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Province</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Reference__c.Field__c</field>
                <operation>equals</operation>
                <value>Province</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Reference__c</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>Addresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Address_Street_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Street Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Reference__c.Field__c</field>
                <operation>equals</operation>
                <value>Street</value>
            </filterItems>
            <filterItems>
                <field>Reference__c.Parent__c</field>
                <operation>equals</operation>
                <valueField>$Source.Address_Subdivision__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Reference__c</referenceTo>
        <relationshipLabel>Addresses (Street Name)</relationshipLabel>
        <relationshipName>Addresses4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Address_Subdivision__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subdivision / Bldg</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Reference__c.Field__c</field>
                <operation>equals</operation>
                <value>Subdivision</value>
            </filterItems>
            <filterItems>
                <field>Reference__c.Parent__c</field>
                <operation>equals</operation>
                <valueField>$Source.Address_Barangay__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Reference__c</referenceTo>
        <relationshipLabel>Addresses (Subdivision)</relationshipLabel>
        <relationshipName>Addresses3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Address__c</fullName>
        <formula>Address_Unit_No__c &amp; &quot; &quot; &amp;  Address_Street_No__c &amp; &quot; &quot; &amp; Address_Street_Name__r.Name &amp; &quot;, &quot; &amp; Address_Subdivision__r.Name &amp; &quot; &quot; &amp;  Address_Barangay__r.Name &amp; &quot;, &quot; &amp; Address_City_Municipality__r.Name &amp; &quot;, &quot; &amp;  Address_Province__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Address</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipName>Billing_Preferences</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Code_Address_Barangay__c</fullName>
        <label>Code Barangay</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Code_Address_City_Municipality__c</fullName>
        <label>Code City / Municipality</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Code_Address_Province__c</fullName>
        <label>Code Province</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Code_Address_Street_Name__c</fullName>
        <label>Code Street Name</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Code_Address_Subdivision__c</fullName>
        <label>Code Subdivision</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Service</fullName>
                </value>
                <value>
                    <fullName>Billing</fullName>
                </value>
                <value>
                    <fullName>Customer</fullName>
                </value>
                <value>
                    <fullName>Meter</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Address</label>
    <nameField>
        <displayFormat>ADD-{000000}</displayFormat>
        <label>Address Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Office__c.object
<CustomObject>
    <label>Office</label>
    <nameField>
        <label>Office</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Offices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Office_Jurisdiction__c.object
<CustomObject>
    <fields>
        <fullName>Barangay__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Barangay</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Reference__c.Field__c</field>
                <operation>equals</operation>
                <value>Barangay</value>
            </filterItems>
            <filterItems>
                <field>Reference__c.Parent__c</field>
                <operation>equals</operation>
                <valueField>$Source.City__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Reference__c</referenceTo>
        <relationshipLabel>Office Jurisdictions (Barangay)</relationshipLabel>
        <relationshipName>Office_Jurisdictions2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Search City</inlineHelpText>
        <label>City</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Reference__c.Parent__c</field>
                <operation>equals</operation>
                <valueField>$Source.Province__c</valueField>
            </filterItems>
            <filterItems>
                <field>Reference__c.Field__c</field>
                <operation>equals</operation>
                <value>City</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Reference__c</referenceTo>
        <relationshipLabel>Office Jurisdictions (City)</relationshipLabel>
        <relationshipName>Office_Jurisdictions1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Office__c</fullName>
        <label>Office</label>
        <referenceTo>Office__c</referenceTo>
        <relationshipLabel>Office Jurisdictions</relationshipLabel>
        <relationshipName>Office_Jurisdictions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Province__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Search Province</inlineHelpText>
        <label>Province</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Reference__c.Field__c</field>
                <operation>equals</operation>
                <value>Province</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Reference__c</referenceTo>
        <relationshipLabel>Office Jurisdictions</relationshipLabel>
        <relationshipName>Office_Jurisdictions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Street_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Street Name</label>
        <referenceTo>Reference__c</referenceTo>
        <relationshipLabel>Office Jurisdictions (Street Name)</relationshipLabel>
        <relationshipName>Office_Jurisdictions4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subdivision__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subdivision</label>
        <referenceTo>Reference__c</referenceTo>
        <relationshipLabel>Office Jurisdictions (Subdivision)</relationshipLabel>
        <relationshipName>Office_Jurisdictions3</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Office Jurisdiction</label>
    <nameField>
        <displayFormat>OJ-{0000000000}</displayFormat>
        <label>Office Jurisdiction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Office Jurisdictions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Reference__c.object
<CustomObject>
    <description>This contain Address, Geo Code, Picklist Value, Picklist Code</description>
    <fields>
        <fullName>Field__c</fullName>
        <externalId>true</externalId>
        <label>Field</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Name_Code__c</fullName>
        <externalId>true</externalId>
        <label>Name Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent</label>
        <referenceTo>Reference__c</referenceTo>
        <relationshipName>Picklist_Codes_Transformation</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Geo</fullName>
                </value>
                <value>
                    <fullName>Picklist</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Reference</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>References</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AddressTriggerHandler_Test.cls
/* Description: AgreementTriggerHandler test class
 * Author: Jerome To
 * Date Created: MAR-07-17
 */
@isTest
private class AddressTriggerHandler_Test {
	
	@testSetup static void setUp() {
		// create References
		List<Reference__c> addressRefList = CXE_TestDataFactory.createSampleReferenceListForAddress();
		insert addressRefList;
		for(Integer i=0 ; i<addressRefList.size() ; i++) {
			if(i>0){
				addressRefList.get(i).Parent__c = addressRefList.get(i-1).Id;
			}
		}
		update addressRefList;		
	}

	@isTest static void validateAddressCreationUsingLookUp() {
        // Implement test code
		Map<String, Reference__c> addressReference = new Map<String, Reference__c>();
		for(Reference__c addRef : [SELECT Id, Field__c, Name_Code__c FROM Reference__c]) {
			addressReference.put(addRef.Field__c, addRef);
		}
		Address__c addressRec = CXE_TestDataFactory.createAddress(addressReference, true);
		insert addressRec;
		Test.startTest();
		Address__c	newAddressRec = [SELECT Address_Province__c, Address_City_Municipality__c, Address_Barangay__c, 
								 			Address_Street_Name__c, Address_Subdivision__c,
								 			Code_Address_Province__c, Code_Address_City_Municipality__c, Code_Address_Barangay__c, 
								 			Code_Address_Street_Name__c, Code_Address_Subdivision__c 
						  			 FROM Address__c
						  			 WHERE Id=:addressRec.Id];

		System.assertEquals(newAddressRec.Address_Province__c, addressReference.get('Province').Id);
		System.assertEquals(newAddressRec.Address_City_Municipality__c, addressReference.get('City').Id);
		System.assertEquals(newAddressRec.Address_Barangay__c, addressReference.get('Barangay').Id);
		System.assertEquals(newAddressRec.Address_Street_Name__c, addressReference.get('Street').Id);
		System.assertEquals(newAddressRec.Address_Subdivision__c, addressReference.get('Subdivision').Id);
		System.assertEquals(newAddressRec.Code_Address_Province__c, addressReference.get('Province').Name_Code__c);
		System.assertEquals(newAddressRec.Code_Address_City_Municipality__c, addressReference.get('City').Name_Code__c);
		System.assertEquals(newAddressRec.Code_Address_Barangay__c, addressReference.get('Barangay').Name_Code__c);
		System.assertEquals(newAddressRec.Code_Address_Street_Name__c, addressReference.get('Street').Name_Code__c);
		System.assertEquals(newAddressRec.Code_Address_Subdivision__c, addressReference.get('Subdivision').Name_Code__c);
		Test.stopTest();

	}

	@isTest static void validateAddressCreationUsingCode() {
		// Implement test code
		Map<String, Reference__c> addressReference = new Map<String, Reference__c>();
		for(Reference__c addRef : [SELECT Id, Field__c, Name_Code__c FROM Reference__c]) {
			addressReference.put(addRef.Field__c, addRef);
		}
		Address__c addressRec = CXE_TestDataFactory.createAddress(addressReference, false);
		insert addressRec;
		Test.startTest();
		Address__c	newAddressRec = [SELECT Code_Address_Province__c, Code_Address_City_Municipality__c, Code_Address_Barangay__c, 
								 			Code_Address_Street_Name__c, Code_Address_Subdivision__c,
								 			Address_Province__c, Address_City_Municipality__c, Address_Barangay__c, 
								 			Address_Street_Name__c, Address_Subdivision__c 
						  			 FROM Address__c
						  			 WHERE Id=:addressRec.Id];

		System.assertEquals(newAddressRec.Code_Address_Province__c, addressReference.get('Province').Name_Code__c);
		System.assertEquals(newAddressRec.Code_Address_City_Municipality__c, addressReference.get('City').Name_Code__c);
		System.assertEquals(newAddressRec.Code_Address_Barangay__c, addressReference.get('Barangay').Name_Code__c);
		System.assertEquals(newAddressRec.Code_Address_Street_Name__c, addressReference.get('Street').Name_Code__c);
		System.assertEquals(newAddressRec.Code_Address_Subdivision__c, addressReference.get('Subdivision').Name_Code__c);
		System.assertEquals(newAddressRec.Address_Province__c, addressReference.get('Province').Id);
		System.assertEquals(newAddressRec.Address_City_Municipality__c, addressReference.get('City').Id);
		System.assertEquals(newAddressRec.Address_Barangay__c, addressReference.get('Barangay').Id);
		System.assertEquals(newAddressRec.Address_Street_Name__c, addressReference.get('Street').Id);
		System.assertEquals(newAddressRec.Address_Subdivision__c, addressReference.get('Subdivision').Id);
		Test.stopTest();
	}

	@isTest static void validateAddressUpdateUsingCode() {
		// Implement test code
		//List<Reference__c> addList = CXE_TestDataFactory.createSampleReferenceListForAddress();
        //insert addList;
		Map<String, Reference__c> addressReference = new Map<String, Reference__c>();
		for(Reference__c addRef : [SELECT Id, Field__c, Name_Code__c FROM Reference__c]) {
			addressReference.put(addRef.Field__c, addRef);
		}
		Address__c addressRec = CXE_TestDataFactory.createAddress(addressReference, true);
		insert addressRec;
		
		Address__c	newAddressRec = [SELECT Address_Province__c, Address_City_Municipality__c, Address_Barangay__c, 
								 			Address_Street_Name__c, Address_Subdivision__c,
								 			Code_Address_Province__c, Code_Address_City_Municipality__c, Code_Address_Barangay__c, 
								 			Code_Address_Street_Name__c, Code_Address_Subdivision__c  
						  			 FROM Address__c
						  			 WHERE Id=:addressRec.Id];
		newAddressRec.Address_Province__c = null;
		newAddressRec.Address_City_Municipality__c = null;
		newAddressRec.Address_Barangay__c = null;
		newAddressRec.Address_Street_Name__c = null;
		newAddressRec.Address_Subdivision__c = null;
		update newAddressRec;
		Test.startTest();
		Address__c	updatedAddress = [SELECT Address_Province__c, Address_City_Municipality__c, Address_Barangay__c, 
								 			 Address_Street_Name__c, Address_Subdivision__c 
						  			  FROM Address__c
						  			  WHERE Id=:addressRec.Id];		

		System.assertEquals(updatedAddress.Address_Province__c, null);
		System.assertEquals(updatedAddress.Address_City_Municipality__c, null);
		System.assertEquals(updatedAddress.Address_Barangay__c, null);
		System.assertEquals(updatedAddress.Address_Street_Name__c, null);
		System.assertEquals(updatedAddress.Address_Subdivision__c, null);
		Test.stopTest();
	}

	@isTest static void validateAddressUpdateUsingLookUp() {
		// Implement test code
		Map<String, Reference__c> addressReference = new Map<String, Reference__c>();
		for(Reference__c addRef : [SELECT Id, Field__c, Name_Code__c FROM Reference__c]) {
			addressReference.put(addRef.Field__c, addRef);
		}
		Address__c addressRec = CXE_TestDataFactory.createAddress(addressReference, true);
		insert addressRec;

		Address__c	newAddressRec = [SELECT Address_Province__c, Address_City_Municipality__c, Address_Barangay__c, 
								 			Address_Street_Name__c, Address_Subdivision__c,
								 			Code_Address_Province__c, Code_Address_City_Municipality__c, Code_Address_Barangay__c, 
								 			Code_Address_Street_Name__c, Code_Address_Subdivision__c  
						  			 FROM Address__c
						  			 WHERE Id=:addressRec.Id];
		newAddressRec.Code_Address_Province__c = '';
		newAddressRec.Code_Address_City_Municipality__c = '';
		newAddressRec.Code_Address_Barangay__c = '';
		newAddressRec.Code_Address_Street_Name__c = '';
		newAddressRec.Code_Address_Subdivision__c = '';
		update newAddressRec;
		Test.startTest();
		Address__c	updatedAddress = [SELECT Code_Address_Province__c, Code_Address_City_Municipality__c, Code_Address_Barangay__c, 
								 			 Code_Address_Street_Name__c, Code_Address_Subdivision__c 
						  			  FROM Address__c
						  			  WHERE Id=:addressRec.Id];		

		System.assertEquals(updatedAddress.Code_Address_Province__c, null);
		System.assertEquals(updatedAddress.Code_Address_City_Municipality__c, null);
		System.assertEquals(updatedAddress.Code_Address_Barangay__c, null);
		System.assertEquals(updatedAddress.Code_Address_Street_Name__c, null);
		System.assertEquals(updatedAddress.Code_Address_Subdivision__c, null);
		Test.stopTest();
	}
    
    @isTest static void createAddressWithCase() {
		// Implement test code   
		//List<Reference__c> refList = CXE_TestDataFactory.createSampleReferenceListForAddress();
        //insert refList;
		
		List<Reference__c> referenceRecord = CXE_TestDataFactory.createReferencePicklist(2, 'Billing Class');
        insert referenceRecord;

		Case caseRecord = CXE_TestDataFactory.createCase(1, 'New Electric Service,', 'Single Meter', CXE_Constants.CASE_APPLICATION_RECEIVED, 'Private')[0];
		//caseRecord.Application_for_Residential_Service__c = true;
		caseRecord.Date_of_Birth__c = system.today() - 1000;
		caseRecord.Tax_Identification_No__c = '123124123';
		caseRecord.Billing_Class__c = 'Name0';
        insert caseRecord;
        
		Map<String, Reference__c> addressReference = new Map<String, Reference__c>();
		for(Reference__c addRef : [SELECT Id, Field__c, Name_Code__c FROM Reference__c]) {
			addressReference.put(addRef.Field__c, addRef);
		}
        
        Id offRecTypeId = Schema.Sobjecttype.Office__c.getRecordTypeInfosByName().get(CXE_Constants.OFFICE_WEB).getRecordTypeId();
        Office__c officeRec = CXE_TestDataFactory.createOffice(1)[0];
        officeRec.RecordTypeId = offRecTypeId;
        
        insert officeRec;
        
        Office_Jurisdiction__c officeJurRec = CXE_TestDataFactory.createOfficeJurisdiction(1)[0];
        officeJurRec.Province__c = addressReference.get('Province').Id;
        officeJurRec.City__c = addressReference.get('City').Id;
        officeJurRec.Barangay__c = addressReference.get('Barangay').Id;
        officeJurRec.Street_Name__c = addressReference.get('Street').Id;
        officeJurRec.Subdivision__c = addressReference.get('Subdivision').Id;
        officeJurRec.Office__c = officeRec.Id;
        
        insert officeJurRec;
        
        Address__c addressRec = CXE_TestDataFactory.createAddress(addressReference, true);
        addressRec.Type__c = 'Service';
        addressRec.Case__c = caseRecord.Id;
		insert addressRec;
		
	}
	
}