src/objects/Agreement__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Agreements</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Contract__c</fullName>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipName>Agreements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Payor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Payor Contract of this Service</description>
        <label>Payor</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Services (Payor)</relationshipLabel>
        <relationshipName>Services_Payor</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SIN__c</fullName>
        <externalId>true</externalId>
        <label>SIN</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>V10_Account_No__c</fullName>
        <label>V10 Account #</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Service</label>
    <nameField>
        <displayFormat>SERV-{00000000}</displayFormat>
        <label>Service ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>CXE_APA_Agent__c</fullName>
        <description>APA Agent</description>
        <label>APA Agent</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>076006</fullName>
                    <label>AUB</label>
                </value>
                <value>
                    <fullName>003006</fullName>
                    <label>BDO</label>
                </value>
                <value>
                    <fullName>002006</fullName>
                    <label>BPI</label>
                </value>
                <value>
                    <fullName>010206</fullName>
                    <label>Chinabank</label>
                </value>
                <value>
                    <fullName>010506</fullName>
                    <label>Citibank</label>
                </value>
                <value>
                    <fullName>001106</fullName>
                    <label>PBCOM</label>
                </value>
                <value>
                    <fullName>026506</fullName>
                    <label>PNB</label>
                </value>
                <value>
                    <fullName>031306</fullName>
                    <label>RCBC</label>
                </value>
                <value>
                    <fullName>031806</fullName>
                    <label>Robinsons Bank</label>
                </value>
                <value>
                    <fullName>032406</fullName>
                    <label>Security Bank</label>
                </value>
                <value>
                    <fullName>035506</fullName>
                    <label>UCPB</label>
                </value>
                <value>
                    <fullName>035006</fullName>
                    <label>UnionBank</label>
                </value>
                <value>
                    <fullName>097006</fullName>
                    <label>PNB Card</label>
                </value>
                <value>
                    <fullName>109006</fullName>
                    <label>BDO Card</label>
                </value>
                <value>
                    <fullName>108006</fullName>
                    <label>BPI Card</label>
                </value>
                <value>
                    <fullName>107006</fullName>
                    <label>Citibank Card</label>
                </value>
                <value>
                    <fullName>074006</fullName>
                    <label>Equicom Card</label>
                </value>
                <value>
                    <fullName>000606</fullName>
                    <label>East West Card</label>
                </value>
                <value>
                    <fullName>019406</fullName>
                    <label>Metrobank Card</label>
                </value>
                <value>
                    <fullName>031206</fullName>
                    <label>RCBC Bankard</label>
                </value>
                <value>
                    <fullName>032606</fullName>
                    <label>Security Bank MasterCard</label>
                </value>
                <value>
                    <fullName>035406</fullName>
                    <label>Unionbank Visa</label>
                </value>
                <value>
                    <fullName>101006</fullName>
                    <label>DINER&apos;S CLUB CARD</label>
                </value>
                <value>
                    <fullName>104006</fullName>
                    <label>EQUITABLE CARD NETWORK</label>
                </value>
                <value>
                    <fullName>099006</fullName>
                    <label>HSBC Card</label>
                </value>
                <value>
                    <fullName>033606</fullName>
                    <label>Standard Chartered Credit</label>
                </value>
                <value>
                    <fullName>000106</fullName>
                    <label>PNB (Allied)</label>
                </value>
                <value>
                    <fullName>002806</fullName>
                    <label>BDO (Filinvest)</label>
                </value>
                <value>
                    <fullName>002906</fullName>
                    <label>BDO (SMDC)</label>
                </value>
                <value>
                    <fullName>003206</fullName>
                    <label>BDO (St. Francis Hotels)</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CXE_Enrolled_to_APA_formula__c</fullName>
        <description>Set Enrolled to APA? to true if Method of Payment is ADA (Bank).</description>
        <formula>ISPICKVAL(Method_of_Payment__c, &quot;ADA (Bank)&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Enrolled to APA?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CXE_Is_APA_Blacklisted__c</fullName>
        <formula>IF(NOT(ISNULL(CXE_APA_BL_Expiry_Date__c))  &amp;&amp; CXE_APA_BL_Expiry_Date__c &gt;= TODAY(), TRUE, FALSE)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is APA Blacklisted?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CXE_Pending_APA_Cancellation__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Pending APA Cancellation?</description>
        <label>Pending APA Cancellation?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CXE_Pending_APA_Enrollment__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Pending APA Enrollment?</description>
        <label>Pending APA Enrollment?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CXE_Reason_for_Cancellation_APA__c</fullName>
        <description>Reason for Cancellation APA</description>
        <label>Reason for Cancellation APA</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Change in bank account or card number</fullName>
                </value>
                <value>
                    <fullName>Change in payment method</fullName>
                </value>
                <value>
                    <fullName>Change in address</fullName>
                </value>
                <value>
                    <fullName>Change in payor</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>V10_Account_No__c</fullName>
        <externalId>true</externalId>
        <label>Legacy Account Number</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/CXE_KeyValueSetting__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Custom setting used to store all generic key value pair settings.</description>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Key Value Setting</label>
</CustomObject>

src/objects/CXE_Service_Enrollment__c.object
<CustomObject>
    <description>Logs customer portal registrations</description>
    <fields>
        <fullName>CXE_Alias__c</fullName>
        <label>Alias</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CXE_IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Is Active?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CXE_ServiceId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service</label>
        <referenceTo>Agreement__c</referenceTo>
        <relationshipLabel>Service Enrollments</relationshipLabel>
        <relationshipName>Service_Enrollments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CXE_Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Payor</fullName>
                </value>
                <value>
                    <fullName>Non-Payor</fullName>
                </value>
                <value>
                    <fullName>Tenant</fullName>
                    <isActive>false</isActive>
                    <label>Tenant</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CXE_UserId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Portal User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Service_Enrollments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Service Enrollment</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Enrollments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CXE_CP_AutoPaymentArrangement_CC.cls
/* Description: Controller class for Auto Pay Arrangement (APA) Subscribe and Unsubscribe Lightning components
 * Author: Rom Edison Reyes
 * Date Created: OCT-04-17
 * APA Enrollment: CSM-XXXXX, --- 
 * APA Cancellation: CSM-13204, CSM-13209, CSM-13214, CSM-13219, CSM-13224, CSM-13229, CSM-13234, CSM-13239
 */
 public without sharing class CXE_CP_AutoPaymentArrangement_CC {

public class AutoPayData {
    @AuraEnabled
    public List<String> validAccts;

    //START CSM-13089 RReyes OCT-26-17
    @AuraEnabled
    public List<String> blacklistedAccts;
    //END CSM-13089 RReyes OCT-26-17

    //START CSM-13099 RReyes OCT-11-17
    @AuraEnabled
    public List<CXE_KeyValueSetting__c> keyValueSetting;
    //END CSM-13099 RReyes OCT-11-17
}
 
//START CSM-13094 RReyes OCT-04-17
 /* Description: Get contract account Ids for Enrollment/Cancellation
 * Parameters: none
 * Returns: List<String>
 * Author: Rom Edison Reyes
 * Date Created: OCT-05-17
 */
 @AuraEnabled
 public static AutoPayData getAccounts(Boolean isEnroll){
    AutoPayData apaData = new AutoPayData();
    Set<String> setAccounts = new Set<String>();
    List<String> lstAccounts = new List<String>();
    Set<String> setBlacklist = new Set<String>();
    List<String> lstBlacklist = new List<String>();
    List<CXE_Service_Enrollment__c> listofEnrollments = [SELECT Id, CXE_ServiceId__c, CXE_Alias__c,
                                                                    CXE_ServiceId__r.SIN__c,
                                                                    CXE_ServiceId__r.Account__c,
                                                                    CXE_ServiceId__r.Payor__c,
                                                                    CXE_ServiceId__r.Payor__r.CXE_Enrolled_to_APA_formula__c, //START/END CSM-14973 RReyes
                                                                    CXE_ServiceId__r.Payor__r.CXE_Pending_APA_Cancellation__c,
                                                                    CXE_ServiceId__r.Payor__r.CXE_Pending_APA_Enrollment__c,
                                                                    CXE_ServiceId__r.Payor__r.CXE_Reason_for_Cancellation_APA__c,
                                                                  //  CXE_ServiceId__r.Payor__r.CXE_APA_Blacklist_Tagging__c
                                                                    CXE_ServiceId__r.Payor__r.CXE_Is_APA_Blacklisted__c, //Start/End Rabayon updated code CSM-13204 10/11/17
                                                                    CXE_ServiceId__r.Payor__r.V10_Account_No__c,
                                                                    CXE_ServiceId__r.Payor__r.AccountId,
                                                                    CXE_Type__c,
                                                                    CXE_IsActive__c
                                                                    FROM CXE_Service_Enrollment__c 
                                                                    WHERE CXE_UserId__c=:UserInfo.getUserId() 
                                                                    AND CXE_IsActive__c = true];
    if(!listofEnrollments.isEmpty()){
        for(CXE_Service_Enrollment__c serv: listofEnrollments){
            if(serv.CXE_ServiceId__r.Payor__c != null){
                //For APA Enrollment - get contracts which is NOT enrolled to APA 
                    //OR, contracts which is ENROLLED to APA and has a pending APA Cancellation case with Change in bank account or card no. as reason for cancellation, 
                    //AND has no pending APA enrollment request
                //For APA Cancellation - get contracts which is enrolled to APA, and has no pending APA cancellation request
                //START CSM-14973 RReyes DEC-27-17- change from CXE_Enrolled_to_APA__c to CXE_Enrolled_to_APA_formula__c
                if(!String.isBlank(serv.CXE_ServiceId__r.Payor__r.V10_Account_No__c) 
                && !setAccounts.contains(serv.CXE_ServiceId__r.Payor__r.V10_Account_No__c)
                && (
                    (isEnroll 
                    && (!serv.CXE_ServiceId__r.Payor__r.CXE_Enrolled_to_APA_formula__c 
                        || (serv.CXE_ServiceId__r.Payor__r.CXE_Enrolled_to_APA_formula__c 
                            && serv.CXE_ServiceId__r.Payor__r.CXE_Pending_APA_Cancellation__c 
                            && serv.CXE_ServiceId__r.Payor__r.CXE_Reason_for_Cancellation_APA__c == Label.RFC_CHANGE_IN_NUMBER)) 
                        && !serv.CXE_ServiceId__r.Payor__r.CXE_Pending_APA_Enrollment__c ) 
                    || 
                    (!isEnroll 
                        && serv.CXE_ServiceId__r.Payor__r.CXE_Enrolled_to_APA_formula__c 
                        && !serv.CXE_ServiceId__r.Payor__r.CXE_Pending_APA_Cancellation__c)
                    ))
                {
                //END CSM-14973 RReyes DEC-27-17- change from CXE_Enrolled_to_APA__c to CXE_Enrolled_to_APA_formula__c
                    setAccounts.add(serv.CXE_ServiceId__r.Payor__r.V10_Account_No__c);
                    //get blacklisted accounts
                    //START CSM-13089 RReyes OCT-26-17
                    if(serv.CXE_ServiceId__r.Payor__r.CXE_Is_APA_Blacklisted__c //Start/end Rabayon updated code CSM-13204 10/11/17 
                        && !setBlacklist.contains(serv.CXE_ServiceId__r.Payor__r.V10_Account_No__c)){
                        setBlacklist.add(serv.CXE_ServiceId__r.Payor__r.V10_Account_No__c);
                    }
                    //END CSM-13089 RReyes OCT-26-17
                }
            }
        }

        lstAccounts.addAll(setAccounts);
        lstBlacklist.addAll(setBlacklist); //START/END CSM-13089 RReyes OCT-26-17
        if(!lstAccounts.isEmpty()){
            lstAccounts.sort();  
        }
    }

    apaData.validAccts = lstAccounts;
    apaData.blacklistedAccts = lstBlacklist; //START/END CSM-13089 RReyes OCT-26-17
    //START CSM-13099 RReyes OCT-11-17
    if(isEnroll){
        List<CXE_KeyValueSetting__c> keyValueSet = [SELECT Name, Value__c FROM CXE_KeyValueSetting__c];
        if(!keyValueSet.isEmpty()){
            apaData.keyValueSetting = keyValueSet;
        }
    }
    //END CSM-13099 RReyes OCT-11-17

    return apaData;
 }

/* Description: create APA case
 * Parameters: contractAcctNum, isAPAEnroll, reasonForCancel
 * Returns: List<String>
 * Author: Rom Edison Reyes
 * Date Created: OCT-05-17
 */
 @AuraEnabled
 //START CSM-13109 RReyes OCT-27-17 - added fileCount
 public static String createAPACase(String contractAcctNum, Boolean isAPAEnroll, String reasonForCancel, String apaScheme, String apaAgent, Integer fileCount){
 //END CSM-13109 RReyes OCT-27-17 - added fileCount   
    Id apaRecTypeId = Schema.Sobjecttype.Case.getRecordTypeInfosByName().get(CXE_Constants.CASE_APA).getRecordTypeId();
    String caseNum = '';
    CXE_Service_Enrollment__c servEnroll = new CXE_Service_Enrollment__c();
    List<CXE_Service_Enrollment__c> listofEnrollments = [SELECT Id, CXE_ServiceId__c,
                                                            CXE_Type__c,
                                                            CXE_ServiceId__r.Payor__c,
                                                            CXE_ServiceId__r.Payor__r.V10_Account_No__c,
                                                            CXE_ServiceId__r.Payor__r.AccountId,
                                                            CXE_IsActive__c
                                                        FROM CXE_Service_Enrollment__c 
                                                        WHERE CXE_UserId__c =: UserInfo.getUserId()
                                                        AND CXE_IsActive__c = true];

    User myUser = [SELECT Id, ContactId FROM User WHERE Id=:UserInfo.getUserId() LIMIT 1];
        
    if(!listofEnrollments.isEmpty()){
        for(CXE_Service_Enrollment__c enroll : listofEnrollments){
            if(enroll.CXE_ServiceId__r.Payor__c != null){
                if(enroll.CXE_ServiceId__r.Payor__r.V10_Account_No__c == contractAcctNum){
                    servEnroll = enroll;
                    break;
                }
            }
        }

        if(servEnroll != null){
            Case newCase = new Case();
            //START CSM-13144/CSM-13234 RReyes OCT-13-17
            //START CSM-14517 JFernandez 1252017 Commented the code and transfer to CaseTriggerHandler after sending of email for APA
            /*List<Group> paymentOpsQueue = [SELECT Id FROM Group WHERE Type = 'Queue' AND DeveloperName =:CXE_Constants.QUEUE_PAYMENT_OPERATIONS LIMIT 1];
            if(!paymentOpsQueue.isEmpty()){
                newCase.OwnerId = paymentOpsQueue[0].Id;
            }*/
            //END CSM-14517 JFernandez 1252017
            //END CSM-13144/CSM-13234 RReyes OCT-13-17
            newCase.RecordTypeId = apaRecTypeId;
            newCase.Account_Number__c = contractAcctNum;
            if(isAPAEnroll){
                newCase.Application_Type_Subtype__c = 'APA Enrollment';
                newCase.CXE_APA_Scheme__c = apaScheme;
                newCase.CXE_APA_Agent__c = apaAgent;
                newCase.Status = 'Document Received';//START/END CSM-13144 RReyes OCT-19-17
                //START CSM-13109 RReyes OCT-27-17 - added fileCount
                fileCount = Integer.valueOf(fileCount);
                newCase.CXE_APA_Attachment_Count__c = fileCount; 
                //END CSM-13109 RReyes OCT-27-17 - added fileCount
            }else{
                newCase.Application_Type_Subtype__c = 'APA Cancellation';
                newCase.CXE_Reason_for_Cancellation_APA__c = reasonForCancel;
                newCase.Status = 'Open';//START/END CSM-13144 RReyes OCT-19-17
            }
            //newCase.Origin = 'Customer'; ///START END CSM-15047 JFernandez JAN-10-18 Commented
            newCase.Origin = CXE_Constants.PAYMENT_ORIGIN_PORTAL;//START END CSM-15047 JFernandez JAN-10-18
            //newCase.Status = 'Open';//START/END CSM-13144 RReyes OCT-19-17
            newCase.CXE_Request_Date__c = date.today();

            newCase.AccountId = servEnroll.CXE_ServiceId__r.Payor__r.AccountId;
            newCase.Contract__c = servEnroll.CXE_ServiceId__r.Payor__c;
            newCase.ContactId = myUser.ContactId;
            insert newCase;
            
            Case c = [SELECT CaseNumber FROM Case WHERE Id=:newCase.Id LIMIT 1];
            caseNum = c.CaseNumber;

            if(!String.isBlank(caseNum)){
                if(servEnroll.CXE_ServiceId__r.Payor__c != null){
                    Contract ctr = new Contract();
                    ctr.Id = servEnroll.CXE_ServiceId__r.Payor__c;
                    if(isAPAEnroll){
                        ctr.CXE_Pending_APA_Enrollment__c = true;
                    }else{
                        ctr.CXE_Pending_APA_Cancellation__c = true;
                        ctr.CXE_Reason_for_Cancellation_APA__c = reasonForCancel; //START/END CSM-13848 RReyes OCT-11-17
                    }
                    try{
                        update ctr;
                    }catch(DMLException dmlEx){
                        ErrorHandlerException.recordException(ctr.Id, true, 'CXE_CP_AutoPaymentArrangement_CC', 'createAPACase', dmlEx.getDMLMessage(0));
                    }
                }
            }
        }
    }

    return caseNum;
 }
 //END CSM-13209 RReyes OCT-04-17

//START CSM-13109 RReyes OCT-26-17
/* Description: do an upload sign for apa
* Parameters: caseNumber, agentName, ext
* Returns: String (url)
* Author: Rom Edison Reyes
* Date Created: OCT-26-17
*/
@AuraEnabled
public static String upload_sign(String documentName) {
    return CXE_HerokuApps.apa_upload_sign(documentName);
}
//END CSM-13109 RReyes OCT-26-17
     
    //START R2C CSM-14749 Shayne 12/01/2017
	@AuraEnabled
     public static Boolean retrieveCheckConglomerate(){
         return CXE_CP_PortalUtility.checkIfConglomerateAccount();
     }
     //END R2C CSM-14749 Shayne 12/01/2017
}