src/objects/Agreement__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Agreements</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Active_Agreement__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Active Agreement</description>
        <label>Active Agreement</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Advance_Frequency_months__c</fullName>
        <description>Advanced frequency</description>
        <label>Advance Frequency (months)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Advance_amount__c</fullName>
        <description>Current advanced amount</description>
        <label>Advance Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Agreement_Duration_Months__c</fullName>
        <defaultValue>36</defaultValue>
        <label>Agreement Term (months)</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Agreement_End_Date__c</fullName>
        <description>Agreement End Date</description>
        <inlineHelpText>End Date of the agreement</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Agreement_Start_Date__c</fullName>
        <description>Agreement Start Date</description>
        <inlineHelpText>Start Date of the agreement</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipName>Agreements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Charges_for_breach_of_contract__c</fullName>
        <formula>Commercial_Product__r.Charges_for_breach_of_contract__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Charges for Breach of Contract</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Commercial_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Commercial Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipName>Agreements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ERP_Agreement_ID__c</fullName>
        <externalId>true</externalId>
        <label>ERP Agreement ID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Service</label>
    <nameField>
        <displayFormat>SERV-{00000000}</displayFormat>
        <label>Service ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Advance_amount__c</fullName>
        <label>Advance amount</label>
        <summarizedField>Agreement__c.Advance_amount__c</summarizedField>
        <summaryFilterItems>
            <field>Agreement__c.Active_Agreement__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryForeignKey>Agreement__c.Contract__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Charges_for_breach_of_contract__c</fullName>
        <label>Charges for Breach of Contract</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
</CustomObject>

src/classes/ContractTermination.cls
public with sharing class ContractTermination
{
   //public case ThisCase{get;set;}
   //public list<AgreementWrapper> agreementWrap{get;set;}
   //Public List<agreement__C> AgreementstoUpdate;
   //Public List<agreement__C> Agreementoncase;
   //public map<Id,Case> agrtocasemap;
    public ContractTermination (ApexPages.StandardController controller) 
    {
        //this.ThisCase = (Case)controller.getRecord();
        //agreementWrap=new list<AgreementWrapper>();
        //AgreementstoUpdate  = new List<agreement__C>();
        //Agreementoncase = new List<agreement__C>();
        //agrtocasemap = new map<Id,Case>();
        
        //ThisCase=[select id,accountid,CaseNumber,Subject,Effective_date_End_of_Contract__c  from case where id=:controller.getrecord().id];
        
        //Agreementoncase = [select id from Agreement__C where Case__c = :Thiscase.Id];
        //for(agreement__C ags: Agreementoncase)
        //{ 
        //    agrtocasemap.put(ags.Id,Thiscase);
        //}
        
        //for(agreement__C ag:[select id ,Account__c,name,Commercial_Product__c,Agreement_Duration_Months__c,Agreement_Start_Date__c,Agreement_End_Date__c,ERP_Agreement_ID__c,
        //                         Advance_Frequency_months__c,Advance_amount__c,Charges_for_breach_of_contract__c,Commercial_Product__r.name from agreement__c where Account__c =:ThisCase.accountid and Active_Agreement__c=true])
        //{
        //    system.debug('true123:' +ag);    
        //  AgreementWrapper agwp=new AgreementWrapper();
        //  agwp.agreement=ag;
        //  if(agrtocasemap.containskey(ag.Id))
        //  {
        //      system.debug('true123');
        //      agwp.sel = true;
        //  }   
        //  agreementWrap.add(agwp);
          
        //}
            
        
    }
    
    //public class AgreementWrapper
    //{
    //  public Agreement__C agreement{get;set;}
    //  public boolean Sel{get;set;}
    //}
    //public pagereference save()
    //{
    //    for(AgreementWrapper agr: agreementWrap)
    //    {
    //        if(agr.sel)
    //        {
    //            agr.agreement.Case__c = ThisCase.Id;
    //            agr.agreement.Agreement_End_Date__c = Thiscase.Effective_date_End_of_Contract__c;
    //            AgreementstoUpdate.add(agr.agreement);
    //        }
    //        if(!agr.sel)
    //        {
    //            if(agrtocasemap.containskey(agr.agreement.Id))
    //            {
    //                agr.agreement.Case__c = null;
    //                AgreementstoUpdate.add(agr.agreement);
    //            }
    //        }                       
    //    }
    //    if(AgreementstoUpdate.size() > 0)
    //    {
    //        update AgreementstoUpdate;
    //    }
    //    if(AgreementstoUpdate.size() == 0)
    //    {
    //        ApexPages.addMessage(new ApexPages.message(ApexPages.severity.WARNING, 'Please select atleast 1 agreement to terminate and click on save'));
    //        return null;
    //    } 
    //    ThisCase.status = 'Backend Handling';  
    //    update ThisCase;
    //    return new ApexPages.StandardController(Thiscase).view();
    //}
    //public pagereference cancel()
    //{
    //    return new ApexPages.StandardController(Thiscase).view();
    //}
    
    //public String title
    //{
    //    get {
    //        return 'Case' + ' - Contract Termination';
    //    }
    //} 
    
    //public String subtitle
    //{
    //    get {
    //        return ThisCase.Subject;
    //    }
    //}        
}