src/objects/Agreement__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Agreements</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SIN__c</fullName>
        <externalId>true</externalId>
        <label>SIN</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Service</label>
    <nameField>
        <displayFormat>SERV-{00000000}</displayFormat>
        <label>Service ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CXE_Service_Enrollment__c.object
<CustomObject>
    <description>Logs customer portal registrations</description>
    <fields>
        <fullName>CXE_Alias__c</fullName>
        <label>Alias</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CXE_Icon_Id__c</fullName>
        <description>Used for MoVE app - Service Icon Image ID</description>
        <label>Icon Id</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CXE_ServiceId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service</label>
        <referenceTo>Agreement__c</referenceTo>
        <relationshipLabel>Service Enrollments</relationshipLabel>
        <relationshipName>Service_Enrollments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CXE_UserId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Portal User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Service_Enrollments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Service Enrollment</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Enrollments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CXE_BS_Alias.cls
@RestResource(urlMapping='/alias-icon')
global with sharing class CXE_BS_Alias  {

	@HttpGet
	global static CXE_Service_Enrollment__c load(){

		Map<String, String> params = RestContext.request.params;
        return load(params.get('sid'));
	}

    @HttpPost
    global static CXE_Service_Enrollment__c post(String sid, String alias, String icon) {

    	CXE_Service_Enrollment__c target = load(sid);
    	target.CXE_Alias__c = alias;
    	target.CXE_Icon_Id__c = icon;

    	update target;

    	return target;
        
        //CXE_Json.text(CXE_CP_MyAccounts.changeAura(sin, aura));
    }

    private static CXE_Service_Enrollment__c load(String sid){
    	return [
			Select Id, CXE_ServiceId__c
             , CXE_Alias__c
             , CXE_Icon_Id__c
             , CXE_ServiceId__r.Account__c 
             , CXE_ServiceId__r.SIN__c 
            From CXE_Service_Enrollment__c 
            Where CXE_UserId__c = :UserInfo.getUserId()
            and CXE_ServiceId__c = :sid
            limit 1
        ];
    }
}