src/objects/Agreement__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Agreements</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Contract__c</fullName>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipName>Agreements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Payor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Payor Contract of this Service</description>
        <label>Payor</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Services (Payor)</relationshipLabel>
        <relationshipName>Services_Payor</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SIN__c</fullName>
        <externalId>true</externalId>
        <label>SIN</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>V10_Account_No__c</fullName>
        <label>V10 Account #</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Service</label>
    <nameField>
        <displayFormat>SERV-{00000000}</displayFormat>
        <label>Service ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Email_2__c</fullName>
        <label>Secondary Email</label>
        <type>Email</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Bill_Print_Mode__c</fullName>
        <label>Bill Print Mode</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>BILPRNT001</fullName>
                    <default>true</default>
                    <label>Paper</label>
                </value>
                <value>
                    <fullName>BILPRNT003</fullName>
                    <label>Paperless</label>
                </value>
                <value>
                    <fullName>BILPRNT002</fullName>
                    <label>Paperplus</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contract_External_ID__c</fullName>
        <externalId>true</externalId>
        <label>Contract External ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Form_of_Payment__c</fullName>
        <label>Payment Mode</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Cash</fullName>
                </value>
                <value>
                    <fullName>Check</fullName>
                </value>
                <value>
                    <fullName>Certificate of Tax Withheld at Source (BIR Forms)</fullName>
                </value>
                <value>
                    <fullName>Fund Transfer</fullName>
                </value>
                <value>
                    <fullName>Meralco Internal</fullName>
                </value>
                <value>
                    <fullName>Credit card</fullName>
                </value>
                <value>
                    <fullName>Debit card</fullName>
                </value>
                <value>
                    <fullName>E-wallet</fullName>
                </value>
                <value>
                    <fullName>Prepaid Card</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Method_of_Payment__c</fullName>
        <label>Method of Payment</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ADA (Bank)</fullName>
                </value>
                <value>
                    <fullName>ADA (Credit Card)</fullName>
                </value>
                <value>
                    <fullName>Over the Counter</fullName>
                </value>
                <value>
                    <fullName>Company Expenses</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Regular</fullName>
                </value>
                <value>
                    <fullName>Prepaid</fullName>
                </value>
                <value>
                    <fullName>SOLR</fullName>
                </value>
                <value>
                    <fullName>Retailer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>V10_Account_No__c</fullName>
        <externalId>true</externalId>
        <label>Legacy Account Number</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/CXE_Service_Enrollment__c.object
<CustomObject>
    <description>Logs customer portal registrations</description>
    <fields>
        <fullName>CXE_Alias__c</fullName>
        <label>Alias</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CXE_IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Is Active?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CXE_ServiceId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service</label>
        <referenceTo>Agreement__c</referenceTo>
        <relationshipLabel>Service Enrollments</relationshipLabel>
        <relationshipName>Service_Enrollments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CXE_UserId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Portal User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Service_Enrollments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Service Enrollment</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Enrollments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CXE_CP_PaperlessBillingSubscribeEmail.cls
public without sharing class CXE_CP_PaperlessBillingSubscribeEmail {
    public class returnEmails{
        @AuraEnabled
        public String firstEmail;
        
        @AuraEnabled
        public String secondEmail;
    }
    
    @AuraEnabled	
    public static returnEmails firstEmail(string accountid){
        List<User> returnEmails = [SELECT LastLoginDate,FirstName,Email FROM User WHERE Id =:UserInfo.getUserId()]; 
        
        List<CXE_Service_Enrollment__c> listofEnrollments = [Select Id, CXE_ServiceId__c, CXE_Alias__c  
                                                             , CXE_ServiceId__r.Account__c, CXE_ServiceId__r.SIN__c
                                                             , CXE_ServiceId__r.Payor__c
                                                             From CXE_Service_Enrollment__c Where CXE_UserId__c=:UserInfo.getUserId()];
        
        
        Set<string> ContractIds = new Set<string>();
        for(CXE_Service_Enrollment__c agreement : listofEnrollments){
            if(agreement.CXE_ServiceId__r.Payor__c!=null){
                ContractIds.add(agreement.CXE_ServiceId__r.Payor__c);
            }
        }
        
        List<Contract> listofContract = [Select Id,V10_Account_No__c,TYPE__c,Form_of_Payment__c,Method_of_Payment__c,AccountId, Account.PersonContactId from Contract where Id in:ContractIds and V10_Account_No__c =: accountid];
        
        List<Contact> c = new List<Contact>();
        if(listofContract.size() > 0){
            c = [select id,Email_2__c from Contact where Id=:listofContract[0].Account.PersonContactId];
        }
        returnEmails myReturn = new returnEmails();
        if(returnEmails.size() > 0){
            myReturn.firstEmail = returnEmails[0].Email;
        }
        if(c.size() > 0){
            myReturn.secondEmail = c[0].Email_2__c;
        }
        return myReturn;
    }
    
    @AuraEnabled	
    public static string updateEmail(string emailadd,string accountid){
        
        String returnMsg = 'none';
        try{
            List<CXE_Service_Enrollment__c> listofEnrollments = [Select Id, CXE_ServiceId__c, CXE_Alias__c  
                                                                 , CXE_ServiceId__r.Account__c, CXE_ServiceId__r.SIN__c
                                                                 , CXE_ServiceId__r.Payor__c
                                                                 From CXE_Service_Enrollment__c 
                                                                  Where CXE_UserId__c=:UserInfo.getUserId()
                                                                  AND CXE_IsActive__c = true ]; //CSM-13961 10.18.2017
            
            
            Set<string> ContractIds = new Set<string>();
            for(CXE_Service_Enrollment__c agreement : listofEnrollments){
                if(agreement.CXE_ServiceId__r.Payor__c!=null){
                    ContractIds.add(agreement.CXE_ServiceId__r.Payor__c);
                }
            }
            
            //Id test1; //CSM-13961 removed
            
            
            List<Contract> contract = [Select ID,Contract_External_ID__c,Name,V10_Account_No__c,Bill_Print_Mode__c,AccountId from Contract where Id In: ContractIds and V10_Account_No__c =: accountid];
            
            
            if(contract.size() > 0){
                //system.debug('here' + contract); //CSM-13961 removed
                //CXE_CP_BillPrintModeIntegrationUtility.printmodeUpdateRequest(contract , CXE_Constants.BPM_PAPERLESS); //CSM-12877 GGrandea 09.22.2017
                
                //START CSM-13961 GGrandea 10.18.2017
                /*List<Contract> listofContract = [Select Id,V10_Account_No__c,TYPE__c,Form_of_Payment__c
                                                 ,Method_of_Payment__c,AccountId, Account.PersonContactId 
                                                 from Contract 
                                                 where Id in: ContractIds 
                                                 and V10_Account_No__c =: accountid];
                //test1 = listofContract[0].Account.PersonContactId; //CSM-13961 removed
                //try{
                if(listofContract.size() > 0){
                    Contact c;
                    if(listofContract[0].Account.PersonContactId!=null){ //if person account
                        c = new Contact(Id=listofContract[0].Account.PersonContactId);
                        c.Email_2__c = emailadd;
                        update c;
                    }else{
                        Contact[] contacts = [SELECT Id,Email_2__c FROM Contact WHERE AccountId =: listofContract[0].AccountId]; 
                        //GVG check if okay to use first if query returned multiple
                        contacts[0].Email_2__c = emailadd;
                        update contacts;
                    }
                    
                    returnMSG = 'success';
                }*/

                if(String.isNotBlank(emailadd)){
                    Contact con = new Contact(  Id = CXE_CP_PortalUtility.getCurrentUserContacId(), 
                                                    Email_2__c = emailadd);
                    update con;
                }
                //END CSM-13961 GGrandea 10.18.2017
                
                
                Case newCase = new Case();
                newCase.Account_Number__c = accountid;
                newCase.Application_Type_Subtype__c = 'Paperless Billing Subscription';
                newCase.CXE_Request_Date__c = date.today();
                newCase.CXE_Effective_Date__c = date.today(); //CSM-12589 Emandolado 9/15/2017
                newCase.Status = 'Successful';
                newCase.CXE_Agreed_to_the_T_C_and_Privacy_Policy__c = true;
                newCase.Origin = 'Customer';
                //newCase.CXE_Bill_Print_Mode__c = 'BILPRNT003'; //CSM-12981 GGrandea 09.26.2017 - field removal
                newCase.CXE_Secondary_Email__c =emailadd;
                newCase.AccountId = contract[0].AccountId;
                newCase.Contract__c = contract[0].Id;

                // START CSM-13935 Jerome To 10/17/2017 [R2B SQT] Only Portal created requests are displayed in the Request tab
                Id contactId = CXE_CP_PortalUtility.getCurrentUserContacId();
                if(contactId != null){
                    newCase.ContactId = contactId;
                }
                // END CSM-13935 Jerome To 10/17/2017 [R2B SQT] Only Portal created requests are displayed in the Request tab
                
                insert newCase;
                Case getReference = [select CaseNumber from Case where Id=:newCase.id];
                returnMSG = getReference.CaseNumber;
            }
        }catch (Exception ex){
            returnMSG = 'error';
            ErrorHandlerException.recordException(null, true, 'CXE_CP_PaperlessBillingSubscribeEmail', 'updateEmail' ,ex.getMessage());
        }
        return returnMsg;
    }
    
    
}