src/objects/Agreement__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Agreements</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Agreement_End_Date__c</fullName>
        <description>Agreement End Date</description>
        <inlineHelpText>End Date of the agreement</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Agreement_Start_Date__c</fullName>
        <description>Agreement Start Date</description>
        <inlineHelpText>Start Date of the agreement</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipName>Agreements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Commercial_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Commercial Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipName>Agreements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contract__c</fullName>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipName>Agreements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Service</label>
    <nameField>
        <displayFormat>SERV-{00000000}</displayFormat>
        <label>Service ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Bank_Name__c</fullName>
        <label>Bank Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IBAN__c</fullName>
        <label>IBAN</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Method_of_Payment__c</fullName>
        <label>Method of Payment</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ADA (Bank)</fullName>
                </value>
                <value>
                    <fullName>ADA (Credit Card)</fullName>
                </value>
                <value>
                    <fullName>Over the Counter</fullName>
                </value>
                <value>
                    <fullName>Company Expenses</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Payment_Day__c</fullName>
        <label>Payment Day</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1st of month</fullName>
                </value>
                <value>
                    <fullName>Last day of month</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Terms_of_Payment__c</fullName>
        <label>Terms of Payment</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>14d end of month</fullName>
                </value>
                <value>
                    <fullName>14d net</fullName>
                </value>
                <value>
                    <fullName>30d end of month</fullName>
                </value>
                <value>
                    <fullName>30d net</fullName>
                </value>
                <value>
                    <fullName>60d end of month</fullName>
                </value>
                <value>
                    <fullName>60d net</fullName>
                </value>
                <value>
                    <fullName>Cash on delivery</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Bank_Name__c</fullName>
        <label>Bank Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Case.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IBAN__c</fullName>
        <label>IBAN</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Method_of_Payment__c</fullName>
        <label>Method of Payment</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cash</fullName>
                </value>
                <value>
                    <fullName>Cheque</fullName>
                    <default>true</default>
                    <label>Cheque</label>
                </value>
                <value>
                    <fullName>Credit card</fullName>
                </value>
                <value>
                    <fullName>Direct Debit</fullName>
                </value>
                <value>
                    <fullName>Transfer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Payment_Day__c</fullName>
        <label>Payment Day</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1st of month</fullName>
                    <default>true</default>
                    <label>1st of month</label>
                </value>
                <value>
                    <fullName>Last day of month</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Terms_of_Payment__c</fullName>
        <label>Terms of Payment</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>14d end of month</fullName>
                </value>
                <value>
                    <fullName>14d net</fullName>
                </value>
                <value>
                    <fullName>30d end of month</fullName>
                </value>
                <value>
                    <fullName>30d net</fullName>
                </value>
                <value>
                    <fullName>60d end of month</fullName>
                </value>
                <value>
                    <fullName>60d net</fullName>
                </value>
                <value>
                    <fullName>Cash on delivery</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Agreement_Start_Date__c</fullName>
        <label>Agreement Start Date</label>
        <type>Date</type>
    </fields>
</CustomObject>

src/objects/Quote.object
<CustomObject>
    <fields>
        <fullName>Bank_Name__c</fullName>
        <label>Bank Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IBAN__c</fullName>
        <label>IBAN</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Method_of_Payment__c</fullName>
        <label>Method of Payment</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cash</fullName>
                </value>
                <value>
                    <fullName>Cheque</fullName>
                </value>
                <value>
                    <fullName>Credit card</fullName>
                </value>
                <value>
                    <fullName>Direct Debit</fullName>
                </value>
                <value>
                    <fullName>Transfer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Payment_Day__c</fullName>
        <label>Payment Day</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1st of month</fullName>
                </value>
                <value>
                    <fullName>Last day of month</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Terms_of_Payment__c</fullName>
        <label>Terms of Payment</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>14d end of month</fullName>
                </value>
                <value>
                    <fullName>14d net</fullName>
                </value>
                <value>
                    <fullName>30d end of month</fullName>
                </value>
                <value>
                    <fullName>30d net</fullName>
                </value>
                <value>
                    <fullName>60d end of month</fullName>
                </value>
                <value>
                    <fullName>60d net</fullName>
                </value>
                <value>
                    <fullName>Cash on delivery</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Business</fullName>
        <active>true</active>
        <label>Business</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/MoveHomeOpportunity.cls
public class MoveHomeOpportunity {
    
     //public id caseid ;
     //public case Thiscase{get;set;}
     //public opportunity opp{get;set;}
     
    public MoveHomeOpportunity(ApexPages.StandardController controller) {
    //caseid= ApexPages.currentPage().getParameters().get('caseid');
    //Thiscase=[select id,accountid,account.name,Description,NEW_Bank_Name__c,NEW_Terms_of_Payment__c,New_Payment_Day__c,NEW_IBAN__c from case where id=:caseid];
    //opp=new opportunity();

    
    }
   
   //public void SaveOpportunity()
   //{
   //if (Test.isrunningtest()) { 
   // Agreement__c contractid2=[select Contract__c from Agreement__c where case__c=:caseid][0];
   // system.assertequals(contractid2, null); system.assertequals(1, 2); 
   // }
   //    id contractid=[select Contract__c from Agreement__c where case__c=:caseid][0].Contract__c;
   //    boolean condition;
   //     for(Agreement__c Agrement:[select contract__c from Agreement__c where case__c=:caseid])
   //        {
   //             if(Agrement.contract__C==contractid)
   //             {
   //                 condition=true;
   //             }
   //             else 
   //             {
   //                 condition=false;
   //                 break;
   //             }
   //        }
   //        contract contract=[select id ,Bank_Name__c,IBAN__c,Method_of_Payment__c,Payment_Day__c,Terms_of_Payment__c from contract where id = :contractid];
           
   //         if(condition)
   //         {
   //             opp.name=thiscase.account.name +' '+ system.today().day()+'-'+ system.today().month()+'-'+ system.today().year();
   //             opp.accountid=thiscase.accountid;
   //             opp.closedate=system.today().adddays(30);
   //             opp.Description=thiscase.Description;
   //             opp.type='Retention Business';
   //             opp.Bank_Name__c=contract.Bank_Name__c;
   //             opp.Method_of_Payment__c=contract.Method_of_Payment__c;
   //             opp.Payment_Day__c=contract.Payment_Day__c;
   //             opp.Terms_of_Payment__c=contract.Terms_of_Payment__c ;
   //             opp.IBAN__c=contract.IBAN__c;
   //             opp.stagename='Proposal/Price Quote';
   //         }
   //         else
   //         {
   //             opp.name=thiscase.account.name +' '+ system.today().day()+'-'+ system.today().month()+'-'+ system.today().year();
   //             opp.accountid=thiscase.accountid;
   //             opp.closedate=system.today().adddays(30);
   //             opp.Description=thiscase.Description;
   //             opp.type='Retention Business';
   //             opp.stagename='Proposal/Price Quote';
   //         }
   //         insert opp;
            
   //         map<id,id> productToPricebookentrymap=new map<id,id>();            
   //         list<opportunitylineitem> opplineitems=new list<opportunityLineItem>();
   //         list<id> productids=new list<id>();
            
   //         for(Agreement__c Agrements:[select Case__c,Account__c,Agreement_End_Date__c,
   //                                        Agreement_Start_Date__c,Commercial_Product__c from Agreement__c where case__c=:caseid])
   //        {
   //         productids.add(agrements.Commercial_Product__c );
   //        }
           
   //        for(pricebookentry pbe:[select id,product2id from pricebookentry where product2id in :productids ])
   //        {
   //          productToPricebookentrymap.put(pbe.product2id,pbe.id);
   //          system.debug('Product to Pricebook map' + productToPricebookentrymap);
   //        }
           
   //        for(Agreement__c activeAgrements:[select Case__c,Account__c,Agreement_End_Date__c,Contract__c,
   //                                        Agreement_Start_Date__c,Commercial_Product__c from Agreement__c where case__c=:caseid])
   //        {
            
   //         if(productToPricebookentrymap.containskey(activeagrements.Commercial_Product__c))
   //         {
   //           opportunitylineitem oppline=new opportunityLineItem();
              
   //           oppline.pricebookentryid=productToPricebookentrymap.get(activeagrements.Commercial_Product__c);
   //           oppline.quantity=1;
   //           oppline.opportunityid=opp.id;
   //           system.debug('Opportunty Price' + oppline.TotalPrice);
   //           opplineitems.add(oppline);
   //          }
   //          else
   //          {
   //           ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR, 'Contact administrator '));
   //          }
              
   //        }
            
   //   if(!opplineitems.isempty())
   //   insert opplineitems;
   //}

}