src/objects/Agreement__c.object
<CustomObject>
    <fields>
        <fullName>SIN__c</fullName>
        <externalId>true</externalId>
        <label>SIN</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Service_Status__c</fullName>
        <label>Service Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Pending to Terminate</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Drop with service providing</fullName>
                </value>
                <value>
                    <fullName>Sleep</fullName>
                </value>
                <value>
                    <fullName>Active - Disconnected</fullName>
                </value>
                <value>
                    <fullName>Active - Pending to Disconnect</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Service</label>
    <nameField>
        <displayFormat>SERV-{00000000}</displayFormat>
        <label>Service ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CXE_Service_Enrollment__c.object
<CustomObject>
    <description>Logs customer portal registrations</description>
    <fields>
        <fullName>CXE_IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Is Active?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CXE_ServiceId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service</label>
        <referenceTo>Agreement__c</referenceTo>
        <relationshipLabel>Service Enrollments</relationshipLabel>
        <relationshipName>Service_Enrollments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CXE_Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Payor</fullName>
                </value>
                <value>
                    <fullName>Non-Payor</fullName>
                </value>
                <value>
                    <fullName>Tenant</fullName>
                    <isActive>false</isActive>
                    <label>Tenant</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CXE_UserId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Portal User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Service_Enrollments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Service Enrollment</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Enrollments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AgreementTriggerHandlerPortalUser_Test.cls
@isTest
private class AgreementTriggerHandlerPortalUser_Test {

     @testSetup static void setup(){
        
        CXE_TestDataFactory.setupPortalData('2', true);

    }
    
    
    @isTest
    static void terminateService_Test(){
        
        Test.startTest();
        
        User adminUser = CXE_TestDataFactory.createAdminUser();
        insert adminUser;
        User userAd = [SELECT Id FROM User Where email='bruce.wayne@wayneenterprises.com'];
        System.runAs(userAd){
            
            
            Account acct = CXE_TestDataFactory.createSingleAccountForPortalUser(userAd.Id);
            insert acct;
            Contact  cont =CXE_TestDataFactory.createContact(acct.Id);
            insert cont;
            
            User portalUser = CXE_TestDataFactory.createPortalUser(cont.Id);
            insert portalUser; 
            portalUser.CommunityNickname ='CorbesTest';
            update portalUser;
            
            System.assert(portalUser!=null);
            
            
            Agreement__c service =[SELECT Id,Service_Status__c  FROM Agreement__c WHERE SIN__C= '293028374839' LIMIT  1]; 
            
            CXE_Service_Enrollment__c cxe = new CXE_Service_Enrollment__c();
            cxe.CXE_ServiceId__c = service.Id;
            cxe.CXE_UserId__c = portalUser.ID;
            cxe.CXE_IsActive__c =True;
            cxe.CXE_Type__c  ='Payor';
            
            insert cxe;
            
            System.assert(cxe!=null);
            
            service.Service_Status__c ='Terminated';
            
            update service;
            
            System.assertEquals('Terminated',  service.Service_Status__c);
            // Activate the Service
            service.Service_Status__c ='Active';
            
            update service; 
            
           System.assertEquals('Active',  service.Service_Status__c);
        }
        Test.stopTest();
        
    }
    
    
 }