src/objects/Auto_Payment_Arrangement__c.object
<CustomObject>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Available</fullName>
                </value>
                <value>
                    <fullName>Downloaded</fullName>
                </value>
                <value>
                    <fullName>Deleted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Auto Payment Arrangement</label>
    <nameField>
        <displayFormat>APA-{000000}</displayFormat>
        <label>Auto Payment Arrangement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Auto Payment Arrangements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OrganizationSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>All Organization Settings</description>
    <fields>
        <fullName>Heroku_Basic_Auth__c</fullName>
        <description>Used for Basic Authentication of Heroku</description>
        <label>Heroku Basic Auth</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Organization Settings</label>
</CustomObject>

src/classes/CXE_APADownloadController_Test.cls
@isTest
public class CXE_APADownloadController_Test {
	
    @testSetup
    static void setupOrgData(){
        OrganizationSettings__c orgSet = new OrganizationSettings__c();
        orgSet.Heroku_Basic_Auth__c = 'Basic TEST=';
        insert orgSet;
    }

    @isTest
    static void redirectToDownloadURLtest(){
        Auto_Payment_Arrangement__c apaRec = new Auto_Payment_Arrangement__c();
        apaRec.Status__c = 'Available';
        apaRec.Date__c = date.today();
        insert apaRec;
        
        test.startTest();
        Test.setCurrentPageReference(new PageReference('Page.CXE_APADownload'));
        System.currentPageReference().getParameters().put('id', apaRec.Id);

        CXE_APADownloadController apaDownload = new CXE_APADownloadController();
        apaDownload.apaId = apaRec.Id;
    	PageReference pageRef = apaDownload.redirectToDownloadURL();
        System.assertNotEquals(pageRef, null);
        test.stopTest();
    }

    @isTest
    static void redirectToDownloadURLtest_Downloaded(){
        Auto_Payment_Arrangement__c apaRec = new Auto_Payment_Arrangement__c();
        apaRec.Status__c = 'Downloaded';
        apaRec.Date__c = date.today();
        insert apaRec;
        
        test.startTest();
        Test.setCurrentPageReference(new PageReference('Page.CXE_APADownload'));
        System.currentPageReference().getParameters().put('id', apaRec.Id);

        CXE_APADownloadController apaDownload = new CXE_APADownloadController();
        apaDownload.apaId = apaRec.Id;
        PageReference pageRef = apaDownload.redirectToDownloadURL();

        List<Apexpages.Message> msgs = ApexPages.getMessages();
        Boolean b = false;
        for(Apexpages.Message msg:msgs){
            if (msg.getDetail().contains('File has already been downloaded.')) b = true;
        }
        System.assert(b);
        test.stopTest();
    }
}