src/objects/Auto_Payment_Arrangement__c.object
<CustomObject>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Available</fullName>
                </value>
                <value>
                    <fullName>Downloaded</fullName>
                </value>
                <value>
                    <fullName>Deleted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Auto Payment Arrangement</label>
    <nameField>
        <displayFormat>APA-{000000}</displayFormat>
        <label>Auto Payment Arrangement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Auto Payment Arrangements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CXE_CP_APADocumentBatch.cls
/* 
 * Description: Scheduled Batch which creates a new APA record per day
 * Author: Von Pernicia (Accenture)
 * Date Created: NOV-09-17
 * Requirement: CSM-13169
 */ 
global class CXE_CP_APADocumentBatch implements Schedulable {
    
    global void execute(SchedulableContext sc) {
        Auto_Payment_Arrangement__c newApa = new Auto_Payment_Arrangement__c();
        List<Auto_Payment_Arrangement__c> existingApa = new List<Auto_Payment_Arrangement__c>();
        Date dateYesterday = system.today() - 1;
        existingApa = [SELECT Id FROM Auto_Payment_Arrangement__c WHERE Date__c =:dateYesterday];
        
        if(existingApa.isEmpty()) {
            newApa.Date__c = dateYesterday;
            newApa.Status__c = 'Available';
            insert newApa;
        }
    }


}