src/objects/Auto_Payment_Arrangement__c.object
<CustomObject>
    <fields>
        <fullName>CXE_isForPurging__c</fullName>
        <defaultValue>false</defaultValue>
        <description>The indicator in the trigger to check if the file is for purging in S3.</description>
        <label>For Purging?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Last_Downloaded_Time__c</fullName>
        <label>Last Downloaded Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Available</fullName>
                </value>
                <value>
                    <fullName>Downloaded</fullName>
                </value>
                <value>
                    <fullName>Deleted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Auto Payment Arrangement</label>
    <nameField>
        <displayFormat>APA-{000000}</displayFormat>
        <label>Auto Payment Arrangement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Auto Payment Arrangements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/APATriggerHandler_Test.cls
@isTest
public class APATriggerHandler_Test {
    
    @isTest
    static void testUpdateStatusToDownloaded(){
        DateTime lastDownloadedTime = System.now() - 10;
        Auto_Payment_Arrangement__c apaRec = new Auto_Payment_Arrangement__c();
        apaRec.Status__c = 'Available';
        apaRec.Date__c = date.today();
        apaRec.Last_Downloaded_Time__c = lastDownloadedTime;
        insert apaRec;

        test.startTest();
        apaRec.Status__c = 'Downloaded';
        update apaRec;

        Auto_Payment_Arrangement__c updatedAPARec = [SELECT Last_Downloaded_Time__c 
                                                        FROM Auto_Payment_Arrangement__c 
                                                        WHERE Id=:apaRec.Id LIMIT 1];

        System.assertNotEquals(updatedAPARec.Last_Downloaded_Time__c, lastDownloadedTime);
        test.stopTest();
    }

    @isTest
    static void testAutoPurge(){
        DateTime lastDownloadedTime = System.now();
        Auto_Payment_Arrangement__c apaRec = new Auto_Payment_Arrangement__c();
        apaRec.Status__c = 'Downloaded';
        apaRec.Date__c = date.today();
        apaRec.Last_Downloaded_Time__c = lastDownloadedTime;
        insert apaRec;

        test.startTest();
        apaRec.CXE_isForPurging__c = true;
        update apaRec;

        Auto_Payment_Arrangement__c updatedAPARec = [SELECT Status__c 
                                                        FROM Auto_Payment_Arrangement__c 
                                                        WHERE Id=:apaRec.Id  LIMIT 1];
                                                        
        System.assertEquals('Deleted', updatedAPARec.Status__c);
        test.stopTest();
    }

    @isTest
    static void testDeleteUndelete(){
        Map<Id, SObject> oldMap = new Map<Id, SObject>();
        APATriggerHandler apa = new APATriggerHandler();
        apa.BeforeDelete(oldMap);
        apa.AfterDelete(oldMap);
        apa.AfterUndelete(oldMap);
    }
}