src/objects/Bundle_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Bundle__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bundle</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Product2.RecordTypeId</field>
                <operation>equals</operation>
                <value>Bundle</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Bundle Line Items</relationshipLabel>
        <relationshipName>Bundle_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Product2.RecordTypeId</field>
                <operation>equals</operation>
                <value>Discount, Commercial Product</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Bundles</relationshipLabel>
        <relationshipName>Bundle_Line_Items1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Bundle Line Item</label>
    <nameField>
        <displayFormat>BLI-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bundle Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Commercial_Product_Value__c.object
<CustomObject>
    <fields>
        <fullName>Included__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Included</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Percentage_Value_Override__c</fullName>
        <label>Percentage Value Override</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Percentage_Value__c</fullName>
        <formula>if(Product_Item__r.Variable__c, Product_Item__r.Percentage_Value__c,Percentage_Value_Override__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Percentage Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Product_Item__c</fullName>
        <label>Product Item</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Product_Item__c.Mandatory__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Product_Item__c</referenceTo>
        <relationshipLabel>Commercial Product Values</relationshipLabel>
        <relationshipName>Commercial_Product_Values</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Commercial Product Values</relationshipLabel>
        <relationshipName>Commercial_Product_Values</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Rate_Value_Override__c</fullName>
        <label>Rate Value Override</label>
        <precision>16</precision>
        <scale>8</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Rate_Value__c</fullName>
        <formula>if( Product_Item__r.Variable__c , Product_Item__r.Rate_Value__c, Rate_Value_Override__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Rate Value</label>
        <precision>18</precision>
        <scale>8</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Variable__c</fullName>
        <formula>Product_Item__r.Variable__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Variable</label>
        <type>Checkbox</type>
    </fields>
    <label>Commercial Product Value</label>
    <nameField>
        <displayFormat>CPV-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Commercial Product Values</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Discount_End_Date__c</fullName>
        <label>Discount End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Discount_Start_Date__c</fullName>
        <label>Discount Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Original_Bundle_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Original Bundle Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Products (Product)</relationshipLabel>
        <relationshipName>Products2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Original_Commercial_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Original Commercial Product</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Commercial Product</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Original_Discount_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Original Discount Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Products (Product)</relationshipLabel>
        <relationshipName>Products3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <recordTypes>
        <fullName>Bundle</fullName>
        <active>true</active>
        <label>Bundle</label>
    </recordTypes>
</CustomObject>

src/objects/Product_Item__c.object
<CustomObject>
    <fields>
        <fullName>Percentage_Value__c</fullName>
        <label>Percentage Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Rate_Value__c</fullName>
        <label>Rate Value</label>
        <precision>16</precision>
        <scale>8</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Variable__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Variable</label>
        <type>Checkbox</type>
    </fields>
    <label>Product Item</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ProductClonecontroller.cls
/**
  * @author       : Accenture IDC
  * @date         : 03/08/2015
  * @description  : Controller Class for Product Cloning
  */
public class ProductClonecontroller
{
    //Variables
    //private ApexPages.StandardController StdController {get; set;}
    //private Product2 Potcustomer {get;set;}
    //public list<Bundle_Line_Item__c> bundlelineitem = new list<Bundle_Line_Item__c>();
    //public list<Commercial_Product_Value__c> cpval1;
    //Constructor
    public ProductClonecontroller(Apexpages.StandardController controller)
    {
        //this.StdController=controller;
        //Potcustomer=(Product2)StdController.getrecord();
        //cpval1 = new list<Commercial_Product_Value__c>();
        //    if(potcustomer.RecordtypeId == Label.COMMERCIAL_PRODUCT_RECORDTYPE)
        //    {
        //        potcustomer.Start_Date__c = null;
        //        potcustomer.End_Date__c = null;
        //        potcustomer.IsActive=false;
        //        potcustomer.Original_Commercial_Product__c=potcustomer.id;
        //    }
        //    if(potcustomer.RecordtypeId == Label.DISCOUNT_RECORDTYPE)
        //    {
        //        potcustomer.Discount_End_Date__c = null;
        //        potcustomer.Discount_Start_Date__c = null;
        //        potcustomer.IsActive=false;
        //        potcustomer.Original_Discount_Product__c=potcustomer.id;
        //    }
        //    if(potcustomer.RecordtypeId == Label.BUNDLE_RECORDTYPE)
        //    {
        //        potcustomer.Start_Date__c = null;
        //        potcustomer.End_Date__c = null;
        //        potcustomer.IsActive=false;
        //        potcustomer.Original_Bundle_Product__c=potcustomer.id;
        //    }
        
    }
    /**
      * @description       This method is called on click of save button on clone VF page. 
      * @param             NA
      * @return            Product Detail Page
      * @throws            NA
      */
    //public pagereference customsave()
    //{
    //    PageReference page = null;
    //    Savepoint sp=Database.setSavepoint();
    //    potCustomer = (Product2) stdController.getRecord();
    //    try
    //    {
    //        Product2 prd2 = potcustomer;
    //        prd2 = potCustomer.clone(false,true);
    //        //Inserting cloned Product
    //        Database.upsert(prd2);
    //        PricebookEntry pbe = [select Product2Id,UnitPrice from PricebookEntry where Product2Id = :potcustomer.Id];
    //        PricebookEntry pbe2 = [select Product2Id,UnitPrice from PricebookEntry where Product2Id = :prd2.Id];
    //            pbe2.UnitPrice = pbe.UnitPrice;
    //            update pbe2;    
    //        if(potcustomer.RecordtypeId == Label.BUNDLE_RECORDTYPE)
    //        //Creating Bundle Line items here. 
    //        {
    //            list<Bundle_Line_Item__c> lineitemtoinsert = new list<Bundle_Line_Item__c>();
    //            bundlelineitem = [select Id,Product__c,Bundle__c from Bundle_Line_Item__c where Bundle__c =: potcustomer.Id];
    //            for(integer i=0;i<bundlelineitem.size();i++)
    //            {
    //                Bundle_Line_Item__c newbli = new Bundle_Line_Item__c();
    //                newbli.Bundle__c = prd2.Id;
    //                newbli.Product__c = bundlelineitem.get(i).Product__c;
    //                lineitemtoinsert.add(newbli);
    //            }
    //            Database.insert(lineitemtoinsert);
    //         }
    //         if(potcustomer.RecordtypeId == Label.COMMERCIAL_PRODUCT_RECORDTYPE)
    //         {
    //             List<Commercial_Product_Value__c> cpvtoupdate = new list<Commercial_Product_Value__c>();
    //             List<Commercial_Product_Value__c> cpv = new list<Commercial_Product_Value__c>();
    //             cpv = [select Id,Product_Item__c,Rate_Value__c,Percentage_Value__c,Included__c,Variable__c from Commercial_Product_Value__c where Product__c =: potcustomer.Id];
    //             Map<Id,Commercial_Product_Value__c> newmap = new map<Id,Commercial_Product_Value__c>();
    //             for(Commercial_Product_Value__c cpval: cpv)
    //             {
    //                 newmap.put(cpval.Product_Item__c,cpval);
    //             }
    //             system.debug('map'+newmap);
    //             cpval1 = [select id,Rate_Value__c,Percentage_Value__c,Product_Item__c,Included__c,variable__c from Commercial_Product_Value__c where Product__c=:prd2.Id];
    //             if(cpval1.size() != cpv.size())
    //             {
    //                 ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Error,Label.PRODUCT_CLONE_ERROR));
    //                 return null;            
    //             }    
    //             for(Commercial_Product_Value__c cpval2: cpval1)
    //             {
    //               Commercial_Product_Value__c var= newmap.get(cpval2.Product_Item__c);
    //               //Commercial_Product_Value__c var1 = new Commercial_Product_Value__c;
    //               if(!var.variable__C)
    //               {
    //                   cpval2.Rate_Value_Override__c=var.Rate_Value__c;
    //                   cpval2.Percentage_Value_Override__c=var.Percentage_Value__c;
    //                   cpval2.Included__c=var.Included__c;
    //                   cpvtoupdate.add(cpval2);
    //               }    
    //             }
    //             system.debug('list'+cpvtoupdate);
    //             Database.Upsert(cpvtoupdate);         
                     
    //         }                    
    //         page = new ApexPages.StandardController(Prd2).view();
    //    }
    //    Catch(Exception e)
    //    {
    //        Database.rollback(sp);
    //        ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Error,Label.PRODUCT_CLONE_GENERIC_ERROR));
    //        page=null;
    //    }
    //    return page;
        
    // }
}