src/objects/Case_Connection__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Connection Meter Reads</relationshipLabel>
        <relationshipName>Connection_Meter_Reads</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Connection__c</fullName>
        <label>Connection</label>
        <referenceTo>Connection__c</referenceTo>
        <relationshipName>Case_Connections</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Meter_Read_Date__c</fullName>
        <label>Meter Read Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Meter_Read_Value__c</fullName>
        <label>Meter Read Value</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Move In</fullName>
                </value>
                <value>
                    <fullName>Move Out</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Connection Meter Read</label>
    <nameField>
        <displayFormat>CC-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Connection Meter Reads</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Connection__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Connections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EAN__c</fullName>
        <label>EAN</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Utility_type__c</fullName>
        <label>Utility Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Electricity</fullName>
                </value>
                <value>
                    <fullName>Gas</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Connection</label>
    <nameField>
        <displayFormat>CONN-{00000000}</displayFormat>
        <label>Connection ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Connections</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/ConnectionMeterReadsManagerTest.cls
/**
  * @author       : Sanchayeeta
  * @date         : 05/11/2015
  * @description  : Test Class for ConnectionMeterReadsManager class 
  */  
@isTest
public class ConnectionMeterReadsManagerTest{
 /*    
    private static testMethod void TestMet(){
            
        //inserting Account
        Account acc=new Account();
        acc.LastName = 'SanTestSanS';
        acc.Phone = '55555555';
        insert acc;
        
        
        //inserting Connection
        Connection__c connect =new Connection__c();
        connect.Account__c=acc.id;
        connect.name='Test San Connect';
        connect.Utility_type__c = 'Electricity';
        connect.EAN__c ='89898989';
        insert connect;
        
        //inserting CAse Connection
        Case_Connection__c caseConnect = new Case_Connection__c();
        caseConnect.Connection__c= connect.id;
        caseConnect.Type__c= 'Move In';
        caseConnect.Meter_Read_Date__c= System.today();
        caseConnect.Meter_Read_Value__c = 50.02;
        insert caseConnect;
        
        Case_Connection__c newManualMeterRead=[select Meter_Read_Date__c,Meter_Read_Value__c from Case_Connection__c where id =: caseConnect.id];
         
        Date d5 = Date.newInstance(2015, 3, 29);
        system.Test.startTest();                   
        ConnectionMeterReadsManager cTerm= new ConnectionMeterReadsManager(connect.EAN__c);
        //cTerm.meterReadsAsGoogleChartsJson();
        cTerm.fetchMeterReads();
        system.Test.stopTest();
        
        
        
  
    
    }*/  
}