src/objects/Commercial_Product_Value__c.object
<CustomObject>
    <fields>
        <fullName>Product_Item__c</fullName>
        <label>Product Item</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Product_Item__c.Mandatory__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Product_Item__c</referenceTo>
        <relationshipLabel>Commercial Product Values</relationshipLabel>
        <relationshipName>Commercial_Product_Values</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Commercial Product Values</relationshipLabel>
        <relationshipName>Commercial_Product_Values</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <formula>if((Rate_Value__c+Percentage_Value__c)!=0, TEXT(Rate_Value__c)+TEXT( Percentage_Value__c ),&apos;0&apos;)</formula>
        <label>Value</label>
        <type>Text</type>
    </fields>
    <label>Commercial Product Value</label>
    <nameField>
        <displayFormat>CPV-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Commercial Product Values</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Master_Product__c.object
<CustomObject>
    <label>Master Product</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Master Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Master_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Master Product</label>
        <referenceTo>Master_Product__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/Product_Item__c.object
<CustomObject>
    <fields>
        <fullName>Master_Product__c</fullName>
        <label>Master Product</label>
        <referenceTo>Master_Product__c</referenceTo>
        <relationshipLabel>Product Items</relationshipLabel>
        <relationshipName>Product_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Product Item</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/OliProductItemValuesControllerExtTest.cls
/**  
* @author       : Accenture IDC  
* @date         : 17/07/2015  
* @description  : Test Class for OliProductItemValuesControllerExt  
*/ 
 @isTest
private class OliProductItemValuesControllerExtTest
{
  private static final String ADMIN_PROFILE = 'System Administrator';
  private static testMethod void productLineItemTestController()
  {   
     Profile prof = [select id from profile where Name =: ADMIN_PROFILE LIMIT 1];
     User contextUser = TestDataFactoryTest.createUser('Dev',prof.id,null);  
    
     Account acc=TestDataFactoryTest.createAccount('Test Account');  
      Master_Product__c MasterProduct= TestDataFactoryTest.createMasterProduct('Test MasterProduct','Gas');  
      id commercialProductRectype=product2.sobjectType.getDescribe().getRecordTypeInfosByName().get('Commercial Product').getRecordTypeId();
      product2 product=TestDataFactoryTest.createProduct('test Product',masterproduct.id,commercialProductRectype,'Variable') ;
     Pricebookentry pbe=[select id from Pricebookentry where product2id=:product.id];
      //Pricebookentry pbe=TestDataFactoryTest.createPricebookEntry(product.id,test.getStandardPricebookid(),20);
      Product_Item__c productItem=TestDataFactoryTest.createProductItem('Test ProductItem','Rate',MasterProduct.id,true);
      Commercial_Product_Value__c commercialProdValue=TestDataFactoryTest.commercialProductValue(productItem.id,product.id,09,20);
      opportunity opp=TestDataFactoryTest.createOpportunity(acc.id,'Test Opportunity',System.today(),'Close Won',System.Test.getStandardPricebookId(),null);
      OpportunityLineItem OLI=TestDataFactoryTest.createOpportunityLineItem(opp.id,PBE.id,1,20);
     system.runas(contextUser)
     {
             ApexPages.StandardController cont = new ApexPages.StandardController(OLI);
             OliProductItemValuesControllerExt  OLIV=new OliProductItemValuesControllerExt(Cont);
             list<Commercial_Product_Value__c> ActualRecords=[select Product_Item__r.Name, Value__c from Commercial_Product_Value__c 
                                                                where Product__c in (select Product2Id from PricebookEntry where id = :PBE.id)
                                                                    order by Name asc];
             system.assertEquals(ActualRecords, OLIV.getCommercialProductValues());
      }
      
   }   
  
}