src/objects/Commercial_Product_Value__c.object
<CustomObject>
    <fields>
        <fullName>Percentage_Value_Override__c</fullName>
        <label>Percentage Value Override</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Percentage_Value__c</fullName>
        <formula>if(Product_Item__r.Variable__c, Product_Item__r.Percentage_Value__c,Percentage_Value_Override__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Percentage Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Price_Group__c</fullName>
        <label>Price Group</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Item__c</fullName>
        <label>Product Item</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Product_Item__c.Mandatory__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Product_Item__c</referenceTo>
        <relationshipLabel>Commercial Product Values</relationshipLabel>
        <relationshipName>Commercial_Product_Values</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Commercial Product Values</relationshipLabel>
        <relationshipName>Commercial_Product_Values</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Rate_Value_Override__c</fullName>
        <label>Rate Value Override</label>
        <precision>16</precision>
        <scale>8</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Rate_Value__c</fullName>
        <formula>if( Product_Item__r.Variable__c , Product_Item__r.Rate_Value__c, Rate_Value_Override__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Rate Value</label>
        <precision>18</precision>
        <scale>8</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Variable__c</fullName>
        <formula>Product_Item__r.Variable__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Variable</label>
        <type>Checkbox</type>
    </fields>
    <label>Commercial Product Value</label>
    <nameField>
        <displayFormat>CPV-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Commercial Product Values</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Master_Product__c.object
<CustomObject>
    <label>Master Product</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Master Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Master_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Master Product</label>
        <referenceTo>Master_Product__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Commercial_Product</fullName>
        <active>true</active>
        <label>Commercial Product</label>
    </recordTypes>
</CustomObject>

src/objects/Product_Item__c.object
<CustomObject>
    <fields>
        <fullName>Master_Product__c</fullName>
        <label>Master Product</label>
        <referenceTo>Master_Product__c</referenceTo>
        <relationshipLabel>Product Items</relationshipLabel>
        <relationshipName>Product_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Percentage_Value__c</fullName>
        <label>Percentage Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Price_Group__c</fullName>
        <label>Price Group</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rate_Value__c</fullName>
        <label>Rate Value</label>
        <precision>16</precision>
        <scale>8</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Variable__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Variable</label>
        <type>Checkbox</type>
    </fields>
    <label>Product Item</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/UpdatePrdComValHandler.cls
/**  
* @author       : Accenture IDC  
* @date         : 18/07/2015  
* @description  : Class to create Commercial product value line items for new product, being called by Trigger.  
*/ 
public with sharing class UpdatePrdComValHandler
{
    
    /**   
      * @description       This method creates Commercial product value line items for new product.
      * @param             Product List                 
      * @return            NA     
      * @throws            NA      
      */
    public void Updateprdcomval(List<Product2> lstprd)
    {
        
         Id commercialProductRecordTypeId = [select Id from RecordType where DeveloperName = 'Commercial_Product' limit 1][0].Id;
         system.debug(' recordtype  '+commercialProductRecordTypeId );
        map<id,product2> productmap = new map<id,product2>();
        List<Commercial_Product_Value__c> Comprdtoinsert = new List<Commercial_Product_Value__c>();
        for (Product2 product: lstprd)
        {
            if (product.RecordTypeId == commercialProductRecordTypeId)
            {      
                for (Product_Item__c pi: [Select Id, Rate_Value__c,Price_Group__c,Percentage_Value__c,Variable__c from Product_Item__c where  Master_Product__c = :product.Master_Product__c])
                {
                Commercial_Product_Value__c cpv = new Commercial_Product_Value__c();
                cpv.Product__c = product.Id;
                cpv.Product_Item__c = pi.Id;
                cpv.Price_Group__c=pi.Price_Group__c;
                if(!pi.Variable__c)
                {
                    cpv.Rate_Value_Override__c = pi.Rate_Value__c;
                    cpv.Percentage_Value_Override__c = pi.Percentage_Value__c; 
                }    
                comprdtoinsert.add(cpv);
                productmap.put(product.id,product);
                }
             }
         }
         system.debug('products to create   '+comprdtoinsert);
         try
         {
             if(!comprdtoinsert.isempty())
             insert comprdtoinsert;
            
         }
         catch(dmlexception dmx)
         {
             for (Integer i = 0; i < dmx.getNumDml(); i++)
             {
                 Product2 source = productMap.get(dmx.getDmlId(i));
                 if (source != null) source.addError(Label.COM_PRD_VAL_INSERT_ERROR);
             }
         }        
     }
}