src/objects/Commercial_Product_Value__c.object
<CustomObject>
    <fields>
        <fullName>Product_Item__c</fullName>
        <label>Product Item</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Product_Item__c.Mandatory__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Product_Item__c</referenceTo>
        <relationshipLabel>Commercial Product Values</relationshipLabel>
        <relationshipName>Commercial_Product_Values</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Commercial Product Values</relationshipLabel>
        <relationshipName>Commercial_Product_Values</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <formula>if((Rate_Value__c+Percentage_Value__c)!=0, TEXT(Rate_Value__c)+TEXT( Percentage_Value__c ),&apos;0&apos;)</formula>
        <label>Value</label>
        <type>Text</type>
    </fields>
    <label>Commercial Product Value</label>
    <nameField>
        <displayFormat>CPV-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Commercial Product Values</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Product_Item__c.object
<CustomObject>
    <label>Product Item</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/OliProductItemValuesControllerExt.cls
/**  
* @author       : Accenture IDC  
* @date         : 21/07/2015  
* @description  : class is used to display the table with commercial product values in opportunity line items  
*/ 
public class OliProductItemValuesControllerExt {

    Id pricebookEntryId;
    
    public oliProductItemValuesControllerExt(ApexPages.StandardController stdController) 
    {
        pricebookEntryId = ((OpportunityLineItem)stdController.getRecord()).PricebookEntryId;
    }    
    
    public List<Commercial_Product_Value__c> getCommercialProductValues() 
    {
        return [select Product_Item__r.Name, Value__c from Commercial_Product_Value__c 
            where Product__c in (select Product2Id from PricebookEntry where id = :pricebookEntryId)
            order by Name asc];
    }
}