src/objects/Commercial_Product_Value__c.object
<CustomObject>
    <fields>
        <fullName>Percentage_Value_Override__c</fullName>
        <label>Percentage Value Override</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Percentage_Value__c</fullName>
        <formula>if(Product_Item__r.Variable__c, Product_Item__r.Percentage_Value__c,Percentage_Value_Override__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Percentage Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Product_Item__c</fullName>
        <label>Product Item</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Product_Item__c.Mandatory__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Product_Item__c</referenceTo>
        <relationshipLabel>Commercial Product Values</relationshipLabel>
        <relationshipName>Commercial_Product_Values</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Rate_Value_Override__c</fullName>
        <label>Rate Value Override</label>
        <precision>16</precision>
        <scale>8</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Value_Type__c</fullName>
        <formula>TEXT(Product_Item__r.Value_Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Value Type</label>
        <type>Text</type>
    </fields>
    <label>Commercial Product Value</label>
    <nameField>
        <displayFormat>CPV-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Commercial Product Values</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Master_Product__c.object
<CustomObject>
    <label>Master Product</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Master Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>EAV__c</fullName>
        <label>EAV</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Master_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Master Product</label>
        <referenceTo>Master_Product__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Discount</fullName>
        <active>true</active>
        <label>Discount</label>
    </recordTypes>
</CustomObject>

src/objects/Product_Item__c.object
<CustomObject>
    <fields>
        <fullName>Criterium__c</fullName>
        <label>Criterium</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Never</fullName>
                </value>
                <value>
                    <fullName>Always</fullName>
                </value>
                <value>
                    <fullName>Single Meter</fullName>
                </value>
                <value>
                    <fullName>Double Meter</fullName>
                </value>
                <value>
                    <fullName>Exclusive Night</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Field__c</fullName>
        <label>Field</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>EAV</fullName>
                </value>
                <value>
                    <fullName>EAV High (Day)</fullName>
                </value>
                <value>
                    <fullName>EAV Low (Night)</fullName>
                </value>
                <value>
                    <fullName>EAV (Exclusive Night)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Master_Product__c</fullName>
        <label>Master Product</label>
        <referenceTo>Master_Product__c</referenceTo>
        <relationshipLabel>Product Items</relationshipLabel>
        <relationshipName>Product_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Operation__c</fullName>
        <label>Operation</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>+ Value</fullName>
                </value>
                <value>
                    <fullName>* Value</fullName>
                </value>
                <value>
                    <fullName>* (1 - Value)</fullName>
                </value>
                <value>
                    <fullName>+ (Value * Field)</fullName>
                </value>
                <value>
                    <fullName>+ (12 * Value)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Percentage_Value__c</fullName>
        <label>Percentage Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Value_Type__c</fullName>
        <label>Value Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                </value>
                <value>
                    <fullName>Rate</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Product Item</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CommercialProductUnitPriceCalculatorTest.cls
/**
 * @author Aard-Jan van Kesteren
 * @description Tests CommercialProductUnitPriceCalculator            
 */
@isTest
public class CommercialProductUnitPriceCalculatorTest {

    @isTest 
    static void testCalculateUnitPrices() {
        CommercialProductUnitPriceCalculator calculator = new CommercialProductUnitPriceCalculator();
        
        Master_Product__c masterProduct = TestDataFactoryTest.createMasterProduct();
        
        // P * Q
        Product_Item__c pi1 = TestDataFactoryTest.createRateProductItem(masterProduct, 0.14, 1, 
                                                                    CommercialProductUnitPriceCalculator.ALWAYS,
                                                                    CommercialProductUnitPriceCalculator.PLUS_VALUE_TIMES_FIELD,
                                                                    CommercialProductUnitPriceCalculator.EAV_FIELD
                                                                    );
 
        // Grid fee
        Product_Item__c pi2 = TestDataFactoryTest.createRateProductItem(masterProduct, 35, 2, 
                                                                    CommercialProductUnitPriceCalculator.ALWAYS,
                                                                    CommercialProductUnitPriceCalculator.PLUS_VALUE,
                                                                    null
                                                                    );   
        
        // Discount
        Product_Item__c pi3 = TestDataFactoryTest.createPercentageProductItem(masterProduct, 1000, 3, 
                                                                    CommercialProductUnitPriceCalculator.ALWAYS,
                                                                    CommercialProductUnitPriceCalculator.TIMES_ONE_MINUS_VALUE,
                                                                    null
                                                                    );   
        
        
        Product_Item__c pi4 = TestDataFactoryTest.createPercentageProductItem(masterProduct, 1000, 3, 
                                                                    CommercialProductUnitPriceCalculator.ALWAYS,
                                                                    CommercialProductUnitPriceCalculator.TIMES_VALUE,
                                                                    null
                                                                    );  

        Product_Item__c pi5 = TestDataFactoryTest.createPercentageProductItem(masterProduct, 1000, 3, 
                                                                    CommercialProductUnitPriceCalculator.ALWAYS,
                                                                    CommercialProductUnitPriceCalculator.PLUS_TWELVE_TIMES_VALUE,
                                                                    null
                                                                    ); 
        

        Product2 commercialProduct = TestDataFactoryTest.createCommercialProduct(masterProduct);
        // Note that the commercial product values are created automatically by a trigger

        //System.assertEquals(0.1, [select Percentage_Value__c from Commercial_Product_Value__c where Product_Item__c = :pi3.Id][0].Percentage_Value__c);
        
        OpportunityLineItem oli1 = new OpportunityLineItem();
        oli1.PricebookEntryId = [select Id from PriceBookEntry where Product2Id = :commercialProduct.Id limit 1][0].Id;
        oli1.EAV__c = 1300;        
        
        OpportunityLineItem oli2 = new OpportunityLineItem();
        oli2.PricebookEntryId = [select Id from PriceBookEntry where Product2Id = :commercialProduct.Id limit 1][0].Id;
        oli2.EAV__c = 1000;
        
        
        List<OpportunityLineItem> olis = new List<OpportunityLineItem>();
        olis.add(oli1);
        olis.add(oli2);
        calculator.calculateUnitPrices(olis);
        
        System.assertNotEquals(null, oli1.PricebookEntryId);
        System.assertNotEquals(null, oli2.PricebookEntryId);

        Opportunity opp=TestDataFactoryTest.createOpportunity();
        CommercialProductUnitPriceCalculator cpupc = new CommercialProductUnitPriceCalculator();
        cpupc.updateOpportunity(opp.Id);
     //   System.assertEquals(0.9 * ((1300 * 0.14) + 35), olis[0].UnitPrice);
      //  System.assertEquals(0.9 * ((1000 * 0.14) + 35), olis[1].UnitPrice);
    }
    
    @isTest
    static void testProcessCpvCalc_Rate_Always_PlusValue() {
        CommercialProductUnitPriceCalculator calculator = new CommercialProductUnitPriceCalculator();
        
        OpportunityLineItem oli = new OpportunityLineItem();
        
        Product_Item__c productItem = new Product_Item__c();
        productItem.Value_Type__c = Constants.PRODUCT_ITEM_VALUE_TYPE_RATE;
        productItem.Criterium__c = CommercialProductUnitPriceCalculator.ALWAYS;
        productItem.Operation__c = CommercialProductUnitPriceCalculator.PLUS_VALUE;
        
        Commercial_Product_Value__c cpv = new Commercial_Product_Value__c();
        cpv.Product_Item__r = productItem;
        cpv.Rate_Value_Override__c = 4.56;
        
        //System.assertEquals(5.76, calculator.processCpvCalculation(1.2, cpv, oli));
    }

    @isTest
    static void testProcessCpvCalc_Percentage_Always_TimesValue() {
        CommercialProductUnitPriceCalculator calculator = new CommercialProductUnitPriceCalculator();
        
        OpportunityLineItem oli = new OpportunityLineItem();
        
        Product_Item__c productItem = new Product_Item__c();
        productItem.Value_Type__c = Constants.PRODUCT_ITEM_VALUE_TYPE_PERCENTAGE;
        productItem.Criterium__c = CommercialProductUnitPriceCalculator.ALWAYS;
        productItem.Operation__c = CommercialProductUnitPriceCalculator.TIMES_VALUE;
    
        Commercial_Product_Value__c cpv = new Commercial_Product_Value__c();
        cpv.Product_Item__r = productItem;
        cpv.Percentage_Value_Override__c = 0.1;        
        
        //System.assertEquals(18, calculator.processCpvCalculation(180, cpv, oli));
    }
    
    @isTest
    static void testProcessCpvCalc_Rate_Always_PlusValueTimesField() {
        CommercialProductUnitPriceCalculator calculator = new CommercialProductUnitPriceCalculator();
        
        OpportunityLineItem oli = new OpportunityLineItem();
        oli.EAV__c = 2300;
        
        Product_Item__c productItem = new Product_Item__c();
        productItem.Value_Type__c = Constants.PRODUCT_ITEM_VALUE_TYPE_RATE;
        productItem.Criterium__c = CommercialProductUnitPriceCalculator.ALWAYS;
        productItem.Operation__c = CommercialProductUnitPriceCalculator.PLUS_VALUE_TIMES_FIELD;
        //productItem.Field__c = CommercialProductUnitPriceCalculator.EAV;
        
        Commercial_Product_Value__c cpv = new Commercial_Product_Value__c();
        cpv.Product_Item__r = productItem;
        cpv.Rate_Value_Override__c = 0.14;          
        
        //System.assertEquals(20 + (0.14 * 2300), calculator.processCpvCalculation(20, cpv, oli));
    }    

    @isTest
    static void testProcessCpvCalc_Percentage_Always_TimesOneMinusValue() {
        CommercialProductUnitPriceCalculator calculator = new CommercialProductUnitPriceCalculator();
        
        OpportunityLineItem oli = new OpportunityLineItem();
        
        Product_Item__c productItem = new Product_Item__c();
        productItem.Value_Type__c = Constants.PRODUCT_ITEM_VALUE_TYPE_PERCENTAGE;
        productItem.Criterium__c = CommercialProductUnitPriceCalculator.ALWAYS;
        productItem.Operation__c = CommercialProductUnitPriceCalculator.TIMES_ONE_MINUS_VALUE;

        Commercial_Product_Value__c cpv = new Commercial_Product_Value__c();
        cpv.Product_Item__r = productItem;
        cpv.Percentage_Value_Override__c = 0.2;  
        
        //System.assertEquals(300 * (1 - 0.2), calculator.processCpvCalculation(300, cpv, oli));
    } 
    
}