src/objects/Commercial_Product_Value__c.object
<CustomObject>
    <fields>
        <fullName>Percentage_Value__c</fullName>
        <formula>if(Product_Item__r.Variable__c, Product_Item__r.Percentage_Value__c,Percentage_Value_Override__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Percentage Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Product_Item__c</fullName>
        <label>Product Item</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Product_Item__c.Mandatory__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Product_Item__c</referenceTo>
        <relationshipLabel>Commercial Product Values</relationshipLabel>
        <relationshipName>Commercial_Product_Values</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Commercial Product Values</relationshipLabel>
        <relationshipName>Commercial_Product_Values</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Rate_Value__c</fullName>
        <formula>if( Product_Item__r.Variable__c , Product_Item__r.Rate_Value__c, Rate_Value_Override__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Rate Value</label>
        <precision>18</precision>
        <scale>8</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Value_Type__c</fullName>
        <formula>TEXT(Product_Item__r.Value_Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Value Type</label>
        <type>Text</type>
    </fields>
    <label>Commercial Product Value</label>
    <nameField>
        <displayFormat>CPV-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Commercial Product Values</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Master_Product__c.object
<CustomObject>
    <label>Master Product</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Master Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>EAV__c</fullName>
        <label>EAV</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Master_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Master Product</label>
        <referenceTo>Master_Product__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Commercial_Product</fullName>
        <active>true</active>
        <label>Commercial Product</label>
    </recordTypes>
</CustomObject>

src/objects/Product_Item__c.object
<CustomObject>
    <fields>
        <fullName>Calculation_Order__c</fullName>
        <label>Calculation Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Criterium__c</fullName>
        <label>Criterium</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Never</fullName>
                </value>
                <value>
                    <fullName>Always</fullName>
                </value>
                <value>
                    <fullName>Single Meter</fullName>
                </value>
                <value>
                    <fullName>Double Meter</fullName>
                </value>
                <value>
                    <fullName>Exclusive Night</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Field__c</fullName>
        <label>Field</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>EAV</fullName>
                </value>
                <value>
                    <fullName>EAV High (Day)</fullName>
                </value>
                <value>
                    <fullName>EAV Low (Night)</fullName>
                </value>
                <value>
                    <fullName>EAV (Exclusive Night)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Master_Product__c</fullName>
        <label>Master Product</label>
        <referenceTo>Master_Product__c</referenceTo>
        <relationshipLabel>Product Items</relationshipLabel>
        <relationshipName>Product_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Operation__c</fullName>
        <label>Operation</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>+ Value</fullName>
                </value>
                <value>
                    <fullName>* Value</fullName>
                </value>
                <value>
                    <fullName>* (1 - Value)</fullName>
                </value>
                <value>
                    <fullName>+ (Value * Field)</fullName>
                </value>
                <value>
                    <fullName>+ (12 * Value)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Percentage_Value__c</fullName>
        <label>Percentage Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Rate_Value__c</fullName>
        <label>Rate Value</label>
        <precision>16</precision>
        <scale>8</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Value_Type__c</fullName>
        <label>Value Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                </value>
                <value>
                    <fullName>Rate</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Product Item</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/QuoteLineItem.object
<CustomObject>
    <fields>
        <fullName>EAV__c</fullName>
        <label>EAV</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CommercialProductUnitPriceCalculator.cls
/**
 * @author Aard-Jan van Kesteren
 * @description Calculates the unit prices for 
 *              OpportunityLineItem or QuoteLineItem
 *              records if the related
 *              product is a commercial product.            
 */
public class CommercialProductUnitPriceCalculator {

    public static final String NEVER = 'Never'; 
    public static final String ALWAYS = 'Always';
    public static final String SINGLE_METER = 'Single Meter';
    public static final String DOUBLE_METER = 'Double Meter';
    
    public static final String PLUS_VALUE = '+ Value';
    public static final String TIMES_VALUE = '* Value';
    public static final String PLUS_VALUE_TIMES_FIELD = '+ (Value * Field)';
    public static final String TIMES_ONE_MINUS_VALUE = '* (1 - Value)';
    public static final String PLUS_TWELVE_TIMES_VALUE = '+ (12 * Value)';
    
    public static final String EAV_FIELD = 'EAV';
    
    public Map<OpportunityLineItem, List<Line>> calculateUnitPrices(List<OpportunityLineItem> olis) {
        
        Map<OpportunityLineItem, List<CommercialProductUnitPriceCalculator.Line>> linesMap = new
                Map<OpportunityLineItem, List<CommercialProductUnitPriceCalculator.Line>>();
        
        // Gather the pricebook entry ids
        List<Id> pricebookEntryIds = new List<Id>();
        for (OpportunityLineItem oli: olis) {
            pricebookEntryIds.add(oli.pricebookEntryId);
        }
        
        // Query the realted pricebook entries at its master product id
        // Only consider commercial products
        List<PricebookEntry> pricebookEntries = [
            select Product2Id, Product2.Master_Product__c
            from PricebookEntry        
            where Id in :pricebookEntryIds
            and Product2.RecordType.DeveloperName = 'Commercial_Product'
        ];
        
        // Gather the master product ids
        // And maintain a pricebook entry id to master product id map
        // And maintain a lit of product ids
        List<Id> masterProductIds = new List<Id>();
        List<Id> productIds = new List<Id>();
        Map<Id, Id> pricebookEntryIdToProductId = new Map<Id, Id>();
        for (PricebookEntry pricebookEntry: pricebookEntries) {
            masterProductIds.add(pricebookEntry.Product2.Master_Product__c);
            pricebookEntryIdToProductId.put(pricebookEntry.Id, pricebookEntry.Product2Id);
            productIds.add(pricebookEntry.Product2Id);
        }
        
        // Find the product items. Make sure that they ordered on calculation order
        List<Commercial_Product_Value__c> cpvs = [
            select Product__r.Master_Product__c, Product_Item__r.Value_Type__c, Rate_Value__c,Percentage_Value__c, 
                   Product_Item__r.Criterium__c, Product_Item__r.Operation__c, Product_Item__r.Field__c,
                   Product_Item__r.Name, Product_Item__r.Calculation_Order__c
            from Commercial_Product_Value__c 
            where Product__c in :productIds
            order by Product_Item__r.Calculation_Order__c asc
        ];
        // Now group the product items per master product
        Map<Id, Set<Commercial_Product_Value__c>> cpvMap 
            = new Map<Id, Set<Commercial_Product_Value__c>>();
        for (Commercial_Product_Value__c cpv: cpvs) {
            if (!cpvMap.containsKey(cpv.Product__c)) {
                cpvMap.put(cpv.Product__c, new Set<Commercial_Product_Value__c>());
            }
            cpvMap.get(cpv.Product__c).add(cpv);
        }
        
        // Do the calculation per Opportunity Line Item
        for (OpportunityLineItem oli: olis) {
            // Get all the product items relevant for oli.
            // For this, we first need to get master product for this oli
            
            Id productId = pricebookEntryIdToProductId.get(oli.PricebookEntryId); 
            
            Decimal value = 0;
            linesMap.put(oli, new List<Line>());
            
            System.debug('***** cpvMap: ' + cpvMap);
            
            if (cpvMap.containsKey(productId)) {
                for (Commercial_Product_Value__c cpv: cpvMap.get(productId)) {
                    value = processCpvCalculation(value, cpv, oli, linesMap); 
                }
            }
            oli.UnitPrice =value;
        }
        return linesMap;
    }
    
    public Decimal processCpvCalculation(Decimal value, Commercial_Product_Value__c cpv, sObject lineItem, Map<OpportunityLineItem, List<Line>> linesMap) {
        
        Decimal newValue;
      
            
            Line line = new Line();
            line.name = cpv.Product_Item__r.Name;
            line.operation = cpv.Product_Item__r.Operation__c;
            line.criterium = cpv.Product_Item__r.Criterium__c;
            
            // Handle "+ Value" operation
            if (cpv.Product_Item__r.Operation__c == PLUS_VALUE) {
        
                    line.rate = Util.formatRate(cpv.Rate_Value__c);     
                    newValue = value + cpv.Rate_Value__c;
                
            }
            
            // Handle "* Value" operation
            if (cpv.Product_Item__r.Operation__c == TIMES_VALUE) {
               
                    line.rate = Util.formatPercentage(cpv.Rate_Value__c);
                    newValue = value * cpv.Rate_Value__c;
                
            }    
            
            // Handle "+ (Value * Field) operation" 
            if (cpv.Product_Item__r.Operation__c == PLUS_VALUE_TIMES_FIELD) {
               
                    Decimal fieldValue;
                    if (lineItem instanceof OpportunityLineItem) {
                        if (cpv.Product_Item__r.Field__c == EAV_FIELD) {
                            fieldValue = ((OpportunityLineItem)lineItem).EAV__c;
                        } 
                    }
                    if (fieldValue == null) fieldValue = 0;
                    
                    line.rate = Util.formatRate(cpv.Rate_Value__c);
                    line.EAV = fieldValue + '';
                        
                    newValue = value + (cpv.Rate_Value__c * fieldValue);
                       
            }
            
            // Handle "+ (1 - Value) operation" 
            if (cpv.Product_Item__r.Operation__c == TIMES_ONE_MINUS_VALUE) {
               
                    line.rate = Util.formatPercentage(cpv.Rate_Value__c);
                    newValue = value * (1 - (cpv.Rate_Value__c ));
                      
            }

            // Handle "+ (12 * Value) operation" 
            if (cpv.Product_Item__r.Operation__c == PLUS_TWELVE_TIMES_VALUE) {
                
                    line.rate = Util.formatRate(cpv.Rate_Value__c);
                    newValue = value + 12 * cpv.Rate_Value__c;
                       
            }              
            
            line.newTotal = Util.formatRate(newValue, true);
            line.delta = Util.formatRate(((newValue==null)?0:newvalue)- ((value==null)?0:value), true);
            
            linesMap.get((OpportunityLineItem)lineItem).add(line);
            return newValue;
        
     //   throw new ConfigException('Cannot handle commercial product value '+ cpv.Product_Item__r);
    }
    
    public void updateOpportunity(Id opportunityId) {
        List<OpportunityLineItem> olis = [
            select PricebookEntryId, EAV__c
            from OpportunityLineItem
            where OpportunityId = :opportunityId
        ];
        
        Map<OpportunityLineItem, List<Line>> linesMap = calculateUnitPrices(olis);
        update olis;
    }
    
    class ConfigException extends Exception {}
    
    public class Line {
        public String name {get; set;}
        public String eav {get; set;}
        public String rate {get; set;}
        public String operation {get; set;}
        public String newTotal {get; set;}
        public String delta {get; set;}
        public String criterium {get; set;}
        
        
    }
}