src/objects/Commercial_Product_Value__c.object
<CustomObject>
    <fields>
        <fullName>Product_Item__c</fullName>
        <label>Product Item</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Product_Item__c.Mandatory__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Product_Item__c</referenceTo>
        <relationshipLabel>Commercial Product Values</relationshipLabel>
        <relationshipName>Commercial_Product_Values</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Commercial Product Values</relationshipLabel>
        <relationshipName>Commercial_Product_Values</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <formula>if((Rate_Value__c+Percentage_Value__c)!=0, TEXT(Rate_Value__c)+TEXT( Percentage_Value__c ),&apos;0&apos;)</formula>
        <label>Value</label>
        <type>Text</type>
    </fields>
    <label>Commercial Product Value</label>
    <nameField>
        <displayFormat>CPV-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Commercial Product Values</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>EAV__c</fullName>
        <label>EAV</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Brand_s_Logo__c</fullName>
        <formula>IF(ISPICKVAL(Brand__c, &apos;Blue&apos;), IMAGE(&quot;https://c.ap2.content.force.com/servlet/servlet.ImageServer?id=015280000002kXw&amp;oid=00D28000000WToJ&amp;lastMod=1449565130000&quot;, &quot;Blue&quot; , 30, 30), 
IF(ISPICKVAL(Brand__c, &apos;Green&apos;), IMAGE(&quot;https://c.ap2.content.force.com/servlet/servlet.ImageServer?id=015280000002kc8&amp;oid=00D28000000WToJ&amp;lastMod=1449565254000&quot;, &quot;Green&quot; , 30, 30), 
IF(ISPICKVAL(Brand__c, &apos;Grey&apos;), IMAGE(&quot;https://c.ap2.content.force.com/servlet/servlet.ImageServer?id=015280000002kdG&amp;oid=00D28000000WToJ&amp;lastMod=1449565288000&quot;, &quot;Grey&quot; , 30, 30), 
IF(ISPICKVAL(Brand__c, &apos;Orange&apos;), IMAGE(&quot;https://c.ap2.content.force.com/servlet/servlet.ImageServer?id=015280000002ke9&amp;oid=00D28000000WToJ&amp;lastMod=1449565319000&quot;, &quot;Orange&quot; , 30, 30), 
IF(ISPICKVAL(Brand__c, &apos;Red&apos;), IMAGE(&quot;https://c.ap2.content.force.com/servlet/servlet.ImageServer?id=015280000002kfW&amp;oid=00D28000000WToJ&amp;lastMod=1449565356000&quot;, &quot;Red&quot; , 30, 30),
IMAGE(&quot;https://c.ap2.content.force.com/servlet/servlet.ImageServer?id=015280000002kgK&amp;oid=00D28000000WToJ&amp;lastMod=1449565383000&quot;, &quot;Yellow&quot; , 30, 30) 
)))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Brand&apos;s Logo</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contract_Duration_Years__c</fullName>
        <label>Contract Duration</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1 Year</fullName>
                </value>
                <value>
                    <fullName>2 Years</fullName>
                </value>
                <value>
                    <fullName>3 Years</fullName>
                </value>
                <value>
                    <fullName>4 Years</fullName>
                </value>
                <value>
                    <fullName>5 Years</fullName>
                </value>
                <value>
                    <fullName>None</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Rating__c</fullName>
        <formula>IF( AND(Score__c  &gt;= 0,Score__c &lt;=0.49), IMAGE(&quot;/img/samples/stars_000.gif&quot;, &quot;0 star image&quot;), IF(AND(Score__c  &gt;= 0.50,Score__c &lt;=1.49),  IMAGE(&quot;/img/samples/stars_100.gif&quot;, &quot;1 star image&quot;),  IF(AND(Score__c  &gt;= 1.50,Score__c &lt;=2.49), IMAGE(&quot;/img/samples/stars_200.gif&quot;, &quot;2 star image&quot;),  IF(AND(Score__c  &gt;= 2.50,Score__c &lt;=3.49), IMAGE(&quot;/img/samples/stars_300.gif&quot;, &quot;3 star image&quot;),  IF(AND(Score__c  &gt;= 3.50,Score__c &lt;=4.49), IMAGE(&quot;/img/samples/stars_400.gif&quot;, &quot;4 star image&quot;),  IF(AND(Score__c  &gt;= 4.50,Score__c &lt;=5.00), IMAGE(&quot;/img/samples/stars_500.gif&quot;, &quot;5 star image&quot;), IMAGE(&quot;/img/samples/stars_000.gif&quot;, &quot;0 star image&quot;)) ) ) ) ) )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Rating</label>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/Product_Item__c.object
<CustomObject>
    <label>Product Item</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CommercialProductOverviewController.cls
public class CommercialProductOverviewController {
    
    public String productId {get; set;}
    public Integer eavParam {get; set;}
    
    public List<CommercialProductUnitPriceCalculator.Line> lines {
        
        get {
            
            if (productId != null && productId.trim() != '') {
                CommercialProductUnitPriceCalculator calculator = new CommercialProductUnitPriceCalculator();
                System.debug('productid---'+productId );
                OpportunityLineItem oli = new OpportunityLineItem();

                // The Commerical Product Unit Calculator price needs to have the
                // the pricebook entry id filled on the opportunity line item. Therefore we
                // query it here. It's a workaround, but it works. 
                oli.PricebookEntryId = [
                    select Id
                    from PricebookEntry
                    where Product2Id = :productId
                    and Pricebook2.IsStandard = true
                    limit 1
                ][0].Id;
                oli.EAV__c = eavParam == null ? 0 : eavParam;
                System.debug('*****: ' + oli);
                List<OpportunityLineItem> olis = new List<OpportunityLineItem>{oli};
                Map<OpportunityLineItem, List<CommercialProductUnitPriceCalculator.Line>> linesMap = 
                    calculator.calculateUnitPrices(olis);
                System.debug('*****: ' + linesMap);
                
                /* List<CpvLineItem> cpvLineItems = new List<CpvLineItem>();
                for (Commercial_Product_Value__c cpv: [select Product_Item__r.Name, Value__c from Commercial_Product_Value__c 
                    where Product__c = :productId
                    order by Name asc]) {
                    CpvLineItem cpvLineItem = new CpvLineItem();
                    cpvLineItem.Name = cpv.Product_Item__r.Name;
                    cpvLineItem.value = cpv.Value__c;
                    cpvLineItems.add(cpvLineItem);
                } 
                return cpvLineItems;
                */
                List<CommercialProductUnitPriceCalculator.Line> lines = linesMap.values()[0];
                
                CommercialProductUnitPriceCalculator.Line totalLine = 
                    new CommercialProductUnitPriceCalculator.Line();
                totalLine.name = 'Total';
              //  if(lines.size()>1){
                totalLine.delta = (lines[lines.size() - 1].newTotal);
             //   }
                totalLine.eav=''+eavParam;
                lines.add(totalLine);
                
                return lines;
            } else {
                return new List<CommercialProductUnitPriceCalculator.Line>();
            }
        }
    }
       
    public Product2 getProductDetail() {
        System.debug('*****: getProductDetail()');
        return [
            select Id, Name, Description,Product_Rating__c,Contract_Duration_Years__c, 
            Brand_s_Logo__c from product2 where id=:productid];                           
    }
    
}