src/objects/Connection__c.object
<CustomObject>
    <fields>
        <fullName>Meter_Status__c</fullName>
        <label>Meter Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Sealed</fullName>
                </value>
                <value>
                    <fullName>Created</fullName>
                </value>
                <value>
                    <fullName>Removed</fullName>
                </value>
                <value>
                    <fullName>Reserved</fullName>
                </value>
                <value>
                    <fullName>Scrapped</fullName>
                </value>
                <value>
                    <fullName>Maintenance</fullName>
                </value>
                <value>
                    <fullName>Requested</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Connection</label>
    <nameField>
        <displayFormat>CONN-{00000000}</displayFormat>
        <label>Connection ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Connections</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/ConnectionTriggerHandler_Test.cls
/* Description: ConnectionTriggerHandler test class
 * Author: Christian Peter Doctolero
 * Date Created: MAR-10-17
 */
@isTest
private class ConnectionTriggerHandler_Test {

    static testMethod void createConnection() {
        List<Connection__c> connectionList = CXE_TestDataFactory.createConnection(1);
        Connection__c connectionRecord = connectionList[0];
        
        insert connectionRecord;
        
        Connection__c connUpdate = [Select Meter_Status__c from Connection__c where id=:connectionRecord.id];
        connUpdate.Meter_Status__c = 'Active';
        system.assertequals(connUpdate.Meter_Status__c, 'Active');
        
        update connUpdate;
        
        delete connUpdate;
        //system.assertequals(connUpdate.Meter_Status, null);
        
        undelete connUpdate;
    }
}