src/objects/Connection__c.object
<CustomObject>
    <fields>
        <fullName>Utility_type__c</fullName>
        <label>Utility Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Electricity</fullName>
                </value>
                <value>
                    <fullName>Gas</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Connection</label>
    <nameField>
        <displayFormat>CONN-{00000000}</displayFormat>
        <label>Connection ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Connections</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Utility_Type__c</fullName>
        <label>Utility Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Green</fullName>
                </value>
                <value>
                    <fullName>Grey</fullName>
                </value>
                <value>
                    <fullName>Grey / Green</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Bundle</fullName>
        <active>true</active>
        <label>Bundle</label>
    </recordTypes>
</CustomObject>

src/classes/BundleConfigurator_test.cls
@istest(seealldata=true)
public class BundleConfigurator_test {
    
//private static testmethod void BundleConfigurator_test()
// {
//      PageReference pageref = Page.bundleConfigurator;
//        System.Test.setCurrentPage(pageref);
//      account acc=TestDataFactoryTest.createAccount('test account');
//      opportunity opp= TestDataFactoryTest.createOpportunity(acc.id,'test opportunity',system.today(),'prospecting',null,null);
//     connection__C conn=TestDataFactoryTest.createConnection('test connection','12345');
//     conn.Utility_type__c='electricity';
//     update conn;
//      connection__C conn2=TestDataFactoryTest.createConnection('test connection 2','123456');
//     conn.Utility_type__c='Gas';
//     update conn2;
//     pricebook2 pb2=TestDataFactoryTest.createPricebook(true,'bundlepricebook');
//     product2 BundleProduct=TestDataFactoryTest.createBundleProduct('test bundle product',pb2.id);
    
//     apexPages.currentPage().getParameters().put('id', opp.id);
//     BundleConfiguratorController BCT=new BundleConfiguratorController();
//     BCT.selbundle=BundleProduct.id;
//     bct.newConnectionSelected(conn);
//     bct.newConnectionSelected(conn2);
//     bct.bundleProducts();
//     bct.newcon();
//     bct.getthis();
//     bct.save();
//     bct.calculateeav();
//     bct.closepopup();
//     bct.clearmap();
//     bct.cancel();
//     bct.showpopup();
//     product2 expectedbundle=bct.getProductDetail();
    
// }

}