src/objects/CXE_PortalDeactivation_Reason__mdt.object
<CustomObject>
    <description>This will receive as  the criteria for  which reasons thus the user have chosen to deactivate the portal account.</description>
    <fields>
        <fullName>Different_Email__c</fullName>
        <description>1.	I want to use a different email address as my username.</description>
        <label>Different_Email</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Move_Out_Address__c</fullName>
        <description>2. I’m going to move out of my current address.</description>
        <label>Move_Out_Address</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>No_Active_Sin__c</fullName>
        <description>4.I don’t have an active SIN anymore</description>
        <label>No_Active_Sin</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>No_Longer_Use__c</fullName>
        <description>9.I no longer use my customer portal account.</description>
        <label>No_Longer_Use</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Portal_Difficult__c</fullName>
        <description>6. Meralco Online is difficult to use</description>
        <label>Portal_Difficult</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Portal_Unuseful__c</fullName>
        <description>5.I didn’t find Meralco Online useful.</description>
        <label>Portal_Unuseful</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Privacy_Concerns__c</fullName>
        <description>8.I have privacy concerns</description>
        <label>Privacy_Concerns</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Received_Many_Emails__c</fullName>
        <description>7 received too many e-mails/notifications/promotions</description>
        <label>Received_Many_Emails</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RegCustmer_Not_Assctd__c</fullName>
        <description>3.I’m not associated with the Registered Customer anymore</description>
        <label>RegCustmer_Not_Assctd</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <label>CXE_PortalDeactivation_Reason</label>
    <pluralLabel>CXE_PortalDeactivation_Reasons</pluralLabel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>CXE_CP_isPortalDeactivated__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Boolean that will hold the status if the  portal account is set to be deactivated</description>
        <label>isPortalDeactivated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>UserArticleSelected__c</fullName>
        <description>certain articles related to the reason should be displayed upon selection of reason</description>
        <label>DeactivationReason</label>
        <type>TextArea</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/CXE_CP_DeactivationCtrl.cls
public with sharing class CXE_CP_DeactivationCtrl {

//end of Melvin Corbes Jul-28-2017
    /* Author: Melvin Corbes
     * August-02-2017
     * Rendering for Related Articles
     */ 
    
    Public class PortalDeactivationReasonLinkUrl{
        
        @AuraEnabled
        public String DifferentEmail {get; set;}
        @AuraEnabled
        public String MoveOutAddress {get; set;}
        @AuraEnabled
        public String NoActiveSin {get; set;}
        @AuraEnabled
        public String NoLongerUse {get; set;}
        @AuraEnabled
        public String PortalDifficult {get; set;}
        @AuraEnabled
        public String PortalUnuseful {get; set;} 
        @AuraEnabled
        public String PrivacyConcerns {get; set;}
        @AuraEnabled
        public String ReceivedManyEmails {get; set;}
        @AuraEnabled
        public String RegCustmerNotAssctd {get; set;}
        
        public String Response {get; set;}
        
    }
    
    
    
    @AuraEnabled
    public List<PortalDeactivationReasonLinkUrl> getDeactivationReason(){
        
         List<PortalDeactivationReasonLinkUrl> portalDeactionReason = new List<PortalDeactivationReasonLinkUrl>();
        
        List<CXE_PortalDeactivation_Reason__mdt> retrieveRecords =[SELECT Different_Email__c, Move_Out_Address__c,No_Active_Sin__c,No_Longer_Use__c,
                                                                   Portal_Difficult__c,Portal_Unuseful__c,Privacy_Concerns__c,Received_Many_Emails__c,
                                                                   RegCustmer_Not_Assctd__c
                                                                   FROM CXE_PortalDeactivation_Reason__mdt];
                 
        for(CXE_PortalDeactivation_Reason__mdt pdreasonRec: retrieveRecords){
            PortalDeactivationReasonLinkUrl pdrlu = new PortalDeactivationReasonLinkUrl();
                pdrlu.DifferentEmail = pdreasonRec.Different_Email__c;        
                pdrlu.MoveOutAddress = pdreasonRec.Move_Out_Address__c;
                pdrlu.NoActiveSin = pdreasonRec.No_Active_Sin__c;          
                pdrlu.NoLongerUse = pdreasonRec.No_Longer_Use__c;          
                pdrlu.PortalDifficult = pdreasonRec.Portal_Difficult__c;           
                pdrlu.PortalUnuseful = pdreasonRec.Portal_Unuseful__c;           
                pdrlu.PrivacyConcerns = pdreasonRec.Privacy_Concerns__c;          
                pdrlu.ReceivedManyEmails = pdreasonRec.Received_Many_Emails__c;         
                pdrlu.RegCustmerNotAssctd  = pdreasonRec.RegCustmer_Not_Assctd__c;

                portalDeactionReason.add(pdrlu);
            
        }

        return portalDeactionReason;

    }
    
    
    @AuraEnabled
    public static String PortalAccountDeactivated(String relatedArticle){
        
        PortalDeactivationReasonLinkUrl req = new PortalDeactivationReasonLinkUrl();
        List<User> portalUser = [SELECT CXE_CP_isPortalDeactivated__c FROM User WHERE Id=:UserInfo.getUserId()];
        portalUser[0].CXE_CP_isPortalDeactivated__c =true;
        portalUser[0].UserArticleSelected__c =relatedArticle;
        
        try{
            update portalUser[0];
            req.Response ='successfull';  
        }catch(DMLException ex){
            
            req.Response =String.valueOf(ex);
            ErrorHandlerException.recordException(null, true, 'CXE_CP_MyProfileCTRL', 'execute', ex.getMessage());
        }
        
        return  req.Response ;  
    }
    
   


}