src/objects/Exception_Log__c.object
<CustomObject>
    <description>This object will record all exceptions that will occur within the system</description>
    <fields>
        <fullName>Class_Name__c</fullName>
        <description>Identifies which class caused the exception</description>
        <label>Class Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Exception__c</fullName>
        <description>Logs the exception message generated by the system</description>
        <label>Exception</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Method_Name__c</fullName>
        <description>Identifies which method in the class caused the exception</description>
        <label>Method Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Salesforce_ID__c</fullName>
        <description>Record ID wherein the exception occurred</description>
        <label>Salesforce ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Identifies whether the exception was caused by a general error or web services</description>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>General</fullName>
                </value>
                <value>
                    <fullName>Web Service</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Exception Log</label>
    <nameField>
        <displayFormat>E-{0000000}</displayFormat>
        <label>Exception Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exception Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ErrorHandlerException.cls
/* 
 * Description: Exception Handler
 * Author: Michael Lasala (Accenture)
 * Date Created: JAN-26-17
 */
public class ErrorHandlerException extends Exception {

    /* Public Properties */ 
    /* Static Variables */
    public static final String EXCEPTION_TYPE_GENERAL = 'General';
    public static final String EXCEPTION_TYPE_WEB_SERVICE = 'Web Service';
        
    /* Private Properties */ 
    /* Constructors */ 
    /* Public Methods */ 
    
    /*
     * Description: Method which creates and inserts Exception_Log__c records
     * Parameters: Record Id (Salesforce Id)
                   Type (General/Web Service)
                   Class Name
                   Method Name
                   Exception
     * Returns: Void
     * Author: Michael Lasala (Accenture)
     * Date Created: JAN-26-17
     */
    public static void recordException(Id recordId, 
                                       Boolean isGeneral, 
                                       String className, 
                                       String methodName, 
                                       String exceptionMessage){
        
        //Map parameters to new record
        Exception_Log__c exceptionLog = new Exception_Log__c(Salesforce_ID__c = recordId, 
                                                             Class_Name__c = className,
                                                             Method_Name__c = methodName, 
                                                             Exception__c = exceptionMessage);

        //Assign type based on parameter
        if(isGeneral) {
            exceptionLog.Type__c = EXCEPTION_TYPE_GENERAL;
        } else {
            exceptionLog.Type__c = EXCEPTION_TYPE_WEB_SERVICE;
        }
        
        //Insert exception log
        try {
            insert exceptionLog;
        } catch (DMLException error){
            System.debug('$$$ ErrorHandlerException.recordException error: '+error.getMessage());
        }
    }


    public static void recordException(Id recordId, 
                                       Boolean isGeneral, 
                                       String className, 
                                       String methodName, 
                                       Exception e){
        
        String exceptionMessage = UserInfo.getUserId() + ' : ' + e.getLineNumber() + ' --- ' + e.getMessage() + ' --- ' + e.getStackTraceString() + ' --- ' + e.getTypeName();

        recordException(recordId, isGeneral, className, methodName, exceptionMessage);
    }

    /* Private Methods */ 
    /* Inner classes and methods */ 
    /* Static initializers */ 
}