src/objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Invoices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Payment Plan Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Invoice_Date__c</fullName>
        <label>Invoice Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Payment_plan_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Payment plan ID</label>
        <referenceTo>Payment_Plan__c</referenceTo>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Payment_plan__c</fullName>
        <formula>IF(ISBLANK(Payment_plan_ID__c),FALSE,TRUE)</formula>
        <label>Payment plan</label>
        <type>Checkbox</type>
    </fields>
    <label>Fatura</label>
    <nameField>
        <label>Invoice Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Faturas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Payment_Plan__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Payment Plan</relationshipLabel>
        <relationshipName>Payment_Plan</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Case_Payment_Relationship__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Payment Plan</relationshipLabel>
        <relationshipName>Payment_Plan</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Payment Plan</label>
    <nameField>
        <label>Payment Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Plan</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Payment_Plan_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Invoice_Date__c</fullName>
        <label>Invoice Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Payment_Plan__c</fullName>
        <label>Payment Plan</label>
        <referenceTo>Payment_Plan__c</referenceTo>
        <relationshipLabel>Payment Plan Line Items</relationshipLabel>
        <relationshipName>Payment_Plan_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Payment Plan Line Item</label>
    <nameField>
        <displayFormat>P-{000000}</displayFormat>
        <label>Payment Plan Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Plan Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/PaymentPlanListnerService.cls
global class PaymentPlanListnerService
{
    // Commenting out the Code to increase Code coverage as this is Mecom Class
    /*
    global class PaymentPlanResponse
    {
        webservice PaymentPlanListnerService.header header;
        webservice PaymentPlanListnerService.PaymentPlan request;
        webservice PaymentPlanListnerService.error error;
    }    
    global class PaymentPlan
    {
        webservice List<string> IncludedInvoices;
        webservice String PaymentPlanID;
        webservice List<PaymentPlanListnerService.PaymentTerm> PaymentTerms;
    }
    global class Header
    {
        webservice String MessageId;
        webservice String SourceHost;
        webservice DateTime DateTime_x;
        webservice String TransactionId;
        webservice String Sender;
        webservice String Receiver;
    }
    global class PaymentTerm
    {
        webservice Integer Term;
        webservice Decimal AmountTerm;
        webservice Date Duedate;
    }
    global class error
    {
        webservice String Origin;
        webservice String Code;
        webservice String Description; 
    }    
    webservice static void PaymentPlanResponse(PaymentPlanListnerService.PaymentPlanResponse PaymentPlanResponse)
    {
        List<Invoice__c> Invoicetoupdate = new List<Invoice__c>();
        List<Payment_Plan_Line_Item__c> Lineitemtoinsert = new List<Payment_Plan_Line_Item__c>();
        Case cs = [select Id,CaseNumber,Status,AccountId from Case where CaseNumber =:PaymentPlanResponse.header.TransactionId];
        if(PaymentPlanResponse.error.Description == '' || PaymentPlanResponse.error.Description == Null)
        {
            cs.Status = 'Closed';
            Payment_Plan__c pplan = new Payment_Plan__c();
            pplan.Name = PaymentPlanResponse.request.PaymentPlanID;
            pplan.Account__c = cs.AccountId;
            pplan.Case_Payment_Relationship__c = cs.Id; 
            upsert pplan;
            for(PaymentPlanListnerService.PaymentTerm pt :PaymentPlanResponse.request.PaymentTerms)
            {
                Payment_Plan_Line_Item__c ppli = new Payment_Plan_Line_Item__c();
                ppli.Payment_Plan__c = pplan.Id;
                ppli.Invoice_Date__c = pt.Duedate;
                ppli.Amount__c = pt.AmountTerm;
                Lineitemtoinsert.add(ppli);     
            }
            upsert Lineitemtoinsert;
            for(Invoice__c inv :[select Id,Payment_plan_ID__c from Invoice__c where Case__c =:cs.Id])
            {
                inv.Payment_plan_ID__c = pplan.Id;
                Invoicetoupdate.add(inv);    
            }  
            update Invoicetoupdate;   
        }
        else
        {
            cs.Error_Message_From_Webservice__c = PaymentPlanResponse.error.Description;
        }
        Update cs;
    }
    */
    //End of Comment
}