src/objects/Notification__c.object
<CustomObject>
    <fields>
        <fullName>Long_Message__c</fullName>
        <label>Long Message</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Short_Message__c</fullName>
        <label>Short Message</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Published</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Notification</label>
    <nameField>
        <displayFormat>NOT-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User_Notification__c.object
<CustomObject>
    <fields>
        <fullName>Notification__c</fullName>
        <label>Notification</label>
        <referenceTo>Notification__c</referenceTo>
        <relationshipLabel>User Notifications</relationshipLabel>
        <relationshipName>User_Notifications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Displayed</fullName>
                </value>
                <value>
                    <fullName>Openen</fullName>
                </value>
                <value>
                    <fullName>Read</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>User_Notifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>User Notification</label>
    <nameField>
        <displayFormat>USRNOT-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Notifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/NotificationsComponentController.cls
/**
 * @author Aard-Jan van Kesteren
 * @description Controller for the NotificationsCustomConsoleComponent VF page.  
 */
public class NotificationsComponentController {

    public User_Notification__c userNotification {get; set;}
    
    public Boolean hasUserNotification {
        get {
            return userNotification != null;
        }
    }    

    public NotificationsComponentController() {
		refreshUserNotification();
    }
    
    public void markRead() {
        try {
        	if (userNotification != null) {
            	userNotification.Status__c = Constants.USER_NOTIFICATION_STATUS_READ;
            	update userNotification;
        	}
        	refreshUserNotification();
        } catch (Exception e) {
            System.debug(LoggingLevel.ERROR, e);
            System.debug(LoggingLevel.ERROR, e.getStackTraceString());
        }
    }
    
    public void markDisplayed() {
        try {
        	if (userNotification != null && 
            	userNotification.Status__c == Constants.USER_NOTIFICATION_STATUS_NEW) {
            	// Only allowed transition is NEW -> DISPLAYED
            	userNotification.Status__c = Constants.USER_NOTIFICATION_STATUS_DISPLAYED;
            	update userNotification;
                }
        } catch (Exception e) {
            System.debug(LoggingLevel.ERROR, e);
            System.debug(LoggingLevel.ERROR, e.getStackTraceString());            
        }
    }    
    
    public void markOpened() {
        try {
        	if (userNotification != null && 
            	(userNotification.Status__c == Constants.USER_NOTIFICATION_STATUS_NEW 
             	|| userNotification.Status__c == Constants.USER_NOTIFICATION_STATUS_DISPLAYED)) {
            	// Only allowed transitions are NEW -> OPENED and DISPLAYED -> OPENED
            	userNotification.Status__c = Constants.USER_NOTIFICATION_STATUS_OPENED;
            	update userNotification;
                }
   			
        } catch (Exception e) {
            System.debug(LoggingLevel.ERROR, e);
            System.debug(LoggingLevel.ERROR, e.getStackTraceString());            
        }
    }      
    
    public void refreshUserNotification() {
        try {
    		List<User_Notification__c> userNotifications = [
            	select Id
            	, 	   Notification__r.Short_Message__c
            	,      Notification__r.Long_Message__c
            	,      Status__c
            	,      Name
            	from User_Notification__c
            	where User__c = :UserInfo.getUserId()
            	and Status__c != :Constants.USER_NOTIFICATION_STATUS_READ
            	and Notification__r.Status__c = :Constants.NOTIFICATION_STATUS_PUBLISHED
            	order by CreatedDate asc
            	limit 1
        	];
        	userNotification = userNotifications.isEmpty() ? null : userNotifications[0];
        } catch (Exception e) {
        	System.debug(LoggingLevel.ERROR, e);
            System.debug(LoggingLevel.ERROR, e.getStackTraceString());
        }
    }
    
}