src/objects/Notification__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Published</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Notification</label>
    <nameField>
        <displayFormat>NOT-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User_Notification__c.object
<CustomObject>
    <fields>
        <fullName>Notification__c</fullName>
        <label>Notification</label>
        <referenceTo>Notification__c</referenceTo>
        <relationshipLabel>User Notifications</relationshipLabel>
        <relationshipName>User_Notifications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Displayed</fullName>
                </value>
                <value>
                    <fullName>Openen</fullName>
                </value>
                <value>
                    <fullName>Read</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>User Notification</label>
    <nameField>
        <displayFormat>USRNOT-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Notifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/NotificationsComponentControllerTest.cls
/**
 * @author Aard-Jan van Kesteren
 * @group Test
 * @description Test class for NotificationsComponentController.
 */
@isTest
private class NotificationsComponentControllerTest {

    @isTest
    static void testRefreshUserNotificationAndGetHasUserNotification() {
        NotificationsComponentController controller = new NotificationsComponentController();
        
        // No data has been created yet. Assert that the user does not yet have
        // a user notification.
        controller.refreshUserNotification();
        System.assertEquals(null, controller.userNotification);
        System.assert(!controller.HasUserNotification);
        
        // Setup a Draft notification and user notification. Still the user should not yet have
        // a user notification.
        Notification__c notification = TestDataFactoryTest.createNotification(false);
        User_Notification__c userNot = TestDataFactoryTest.createUserNotification(notification);
        
        controller.refreshUserNotification();
        System.assertEquals(null, controller.userNotification);
        System.assert(!controller.HasUserNotification);

        // Now publish the notification. Now the user should have a user notification.
        notification.Status__c = Constants.NOTIFICATION_STATUS_PUBLISHED;
        update notification;

        controller.refreshUserNotification();
        System.assertEquals(userNot.Id, controller.userNotification.Id);
        System.assert(controller.HasUserNotification);        
        
        // Finally, set the status to Read. Not the user should hot have a user notification anymore.
        controller.markRead();
    
        controller.refreshUserNotification();
        System.assertEquals(null, controller.userNotification);
        System.assert(!controller.HasUserNotification);        
    }
    
    @isTest
    static void testMarkRead() {
        NotificationsComponentController controller = new NotificationsComponentController();
        Notification__c notification = TestDataFactoryTest.createNotification(true);
        User_Notification__c userNot = TestDataFactoryTest.createUserNotification(notification);
        // Call the refresh method to make sure that user notification is set 
        // in the the controller
        controller.refreshUserNotification();
        
        System.Test.startTest();
        controller.markRead();
        System.Test.stopTest();
        
        // Refresh the user notification to make sure that we actually look at the persisted data
        userNot = [select Status__c from User_Notification__c where Id = :userNot.Id limit 1][0];
        
        System.assertEquals(Constants.USER_NOTIFICATION_STATUS_READ, userNot.Status__c);
    }
    
    @isTest
    static void testMarkDisplayed() {
        NotificationsComponentController controller = new NotificationsComponentController();
        Notification__c notification = TestDataFactoryTest.createNotification(true);
        User_Notification__c userNot = TestDataFactoryTest.createUserNotification(notification);
        // Call the refresh method to make sure that user notification is set 
        // in the the controller
        controller.refreshUserNotification();
        
        System.Test.startTest();
        controller.markDisplayed();
        System.Test.stopTest();
        
        // Refresh the user notification to make sure that we actually look at the persisted data
        userNot = [select Status__c from User_Notification__c where Id = :userNot.Id limit 1][0];
        
        System.assertEquals(Constants.USER_NOTIFICATION_STATUS_DISPLAYED, userNot.Status__c);   
    }
    
    @isTest 
    static void testMarkOpened() {
        NotificationsComponentController controller = new NotificationsComponentController();
        Notification__c notification = TestDataFactoryTest.createNotification(true);
        User_Notification__c userNot = TestDataFactoryTest.createUserNotification(notification);
        // Call the refresh method to make sure that user notification is set 
        // in the the controller
        controller.refreshUserNotification();
        
        System.Test.startTest();
        controller.markOpened();
        System.Test.stopTest();
        
        // Refresh the user notification to make sure that we actually look at the persisted data
        userNot = [select Status__c from User_Notification__c where Id = :userNot.Id limit 1][0];
        
        System.assertEquals(Constants.USER_NOTIFICATION_STATUS_OPENED, userNot.Status__c);        
    }
    
}