src/objects/Org_Wide_Fixed_Setting__mdt.object
<CustomObject>
    <description>All fixed settings for all salesforce orgs</description>
    <fields>
        <fullName>Portal_No_Enrollment_Grace_Period__c</fullName>
        <description>Grace period for a Portal User to be deactivated when all enrollments are inactive</description>
        <label>Portal No Enrollment Grace Period</label>
        <precision>5</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Portal_User_Inactivity_Deactivation__c</fullName>
        <description>No of days before a Portal User to be deactivated</description>
        <label>Portal User Inactivity Deactivation</label>
        <precision>5</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Portal_User_Inactivity_Notif_Count__c</fullName>
        <description>No of days before a portal user is notified of inactivity</description>
        <label>Portal User Inactivity Notif Count</label>
        <precision>5</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Org Wide Fixed Setting</label>
    <pluralLabel>Org Wide Fixed Settings</pluralLabel>
</CustomObject>

src/classes/CXE_CP_TerminatedSoleServiceDeactSched.cls
global class CXE_CP_TerminatedSoleServiceDeactSched implements Schedulable{
 global void execute(SchedulableContext sc){

    	Org_Wide_Fixed_Setting__mdt meta = [SELECT Portal_No_Enrollment_Grace_Period__c
    														,Portal_User_Inactivity_Deactivation__c
    														,Portal_User_Inactivity_Notif_Count__c
    													FROM Org_Wide_Fixed_Setting__mdt WHERE MasterLabel =: CXE_Constants.ALL_STR LIMIT 1];
        // We now call the batch class to be scheduled
         CXE_CP_TerminatedSoleServiceDeactBatch b 
         		= new CXE_CP_TerminatedSoleServiceDeactBatch(Integer.valueOf(meta.Portal_No_Enrollment_Grace_Period__c) );
       
        //Parameters of ExecuteBatch(context,BatchSize)
        database.executebatch(b,200);
    }

}