src/objects/OrganizationSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>All Organization Settings</description>
    <fields>
        <fullName>FooterLinkToFacebook__c</fullName>
        <label>FooterLinkToFacebook</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FooterLinkToInstagram__c</fullName>
        <label>FooterLinkToInstagram</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FooterLinkToPrivacyPolicy__c</fullName>
        <label>FooterLinkToPrivacyPolicy</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FooterLinkToTwitter__c</fullName>
        <label>FooterLinkToTwitter</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FooterLinkToYoutube__c</fullName>
        <label>FooterLinkToYoutube</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FooterSubmitFeedback__c</fullName>
        <label>FooterSubmitFeedback</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FooterTermsAndCondition__c</fullName>
        <label>FooterTermsAndCondition</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <label>Organization Settings</label>
</CustomObject>

src/classes/CXE_CP_FooterCtrl.cls
public class CXE_CP_FooterCtrl {
    
    public static String generatedLink;
    
    @AuraEnabled
    public static String  iGLink() {
        return OrganizationSettings__c.getOrgDefaults().FooterLinkToInstagram__c;
    }
    
    @AuraEnabled
    public static String  youTubeLink() {
        return OrganizationSettings__c.getOrgDefaults().FooterLinkToYoutube__c;
    }
    
    @AuraEnabled
    public static String  twitterLink() {
        return OrganizationSettings__c.getOrgDefaults().FooterLinkToTwitter__c;
    }
    
    @AuraEnabled
    public static String  feedBackLink() {
        return OrganizationSettings__c.getOrgDefaults().FooterSubmitFeedback__c;
    }
    
    @AuraEnabled
    public static String  fBLink() {
        return OrganizationSettings__c.getOrgDefaults().FooterLinkToFacebook__c;
    }
    
    
	@AuraEnabled
    public static String  TermsAndConditionLink() {	
        return OrganizationSettings__c.getOrgDefaults().FooterTermsAndCondition__c;
    }
    
    @AuraEnabled
    public static String  PrivacyPolicyLink() {	
        return OrganizationSettings__c.getOrgDefaults().FooterLinkToPrivacyPolicy__c;
    }

    
    
    
}