src/objects/OrganizationSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>All Organization Settings</description>
    <fields>
        <fullName>MIniAddsPaymentOptions__c</fullName>
        <label>MIniAddsPaymentOptions</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MiniAddsBillDashNoti__c</fullName>
        <label>MiniAddsBillDashNoti</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MiniAddsBillSummary__c</fullName>
        <label>MiniAddsBillSummary</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MiniAddsOnlineBillingFAQs__c</fullName>
        <label>MiniAddsOnlineBillingFAQs</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MiniAddsPaperlessBillingTnC__c</fullName>
        <label>MiniAddsPaperlessBillingTnC</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>MiniAddsPaperlessBillingUnsubscribe__c</fullName>
        <label>MiniAddsPaperlessBillingUnsubscribe</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>MiniAddsViewBillAnytimeAnyWhere__c</fullName>
        <label>MiniAddsViewBillAnytimeAnyWhere</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <label>Organization Settings</label>
</CustomObject>

src/classes/CXE_CP_MiniAddsCtrl.cls
public class CXE_CP_MiniAddsCtrl {
    
    @AuraEnabled
    public static String MiniAddsBillSummary() {
        return OrganizationSettings__c.getOrgDefaults().MiniAddsBillSummary__c;
    }
    
    //Start CSM-14499 Mike Verdad 12/05/2017
    @AuraEnabled
    public static String MiniAddsPaperlessBillingUnsubscribe() {
        return OrganizationSettings__c.getOrgDefaults().MiniAddsPaperlessBillingUnsubscribe__c;
    }
	//End CSM-14499 Mike Verdad 12/05/2017
	
    //Start CSM-14767 Mike Verdad 12/05/2017
    @AuraEnabled
    public static String MiniAddsPaperlessBillingTnC() {
        return OrganizationSettings__c.getOrgDefaults().MiniAddsPaperlessBillingTnC__c;
    }
	//End CSM-14767 Mike Verdad 12/05/2017

    
    /*@AuraEnabled
    public static String MiniAddsOnlineBillingFAQs() {
        return OrganizationSettings__c.getOrgDefaults().MiniAddsOnlineBillingFAQs__c;
    }*/
    
    @AuraEnabled
    public static String MIniAddsPaymentOptions() {
        return OrganizationSettings__c.getOrgDefaults().MIniAddsPaymentOptions__c;
    }
    
    @AuraEnabled
    public static String MiniAddsViewBillAnytimeAnyWhere() {
        return OrganizationSettings__c.getOrgDefaults().MiniAddsViewBillAnytimeAnyWhere__c;
    }
    
    /*@AuraEnabled
    public static String MiniAddsBillDashNoti() {
        return OrganizationSettings__c.getOrgDefaults().MiniAddsBillDashNoti__c;
    }*/
    
    

}