src/objects/Schedule__c.object
<CustomObject>
    <fields>
        <fullName>Non_Residential_Rate__c</fullName>
        <description>Non-residential rate for bill deposit of specific pay load level</description>
        <inlineHelpText>Non-residential rate for bill deposit of specific pay load level</inlineHelpText>
        <label>Non-Residential Rate</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Residential_Rate__c</fullName>
        <description>Residential rate for bill deposit of specific pay load level</description>
        <inlineHelpText>Residential rate for bill deposit of specific pay load level</inlineHelpText>
        <label>Residential Rate</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Schedule_Selector__c</fullName>
        <label>Schedule Selector</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>S-1</fullName>
                </value>
                <value>
                    <fullName>S-2</fullName>
                </value>
                <value>
                    <fullName>S-3</fullName>
                </value>
                <value>
                    <fullName>S-4</fullName>
                </value>
                <value>
                    <fullName>S-5</fullName>
                </value>
                <value>
                    <fullName>S-6</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Deposit Schedule</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deposit Schedule</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestDataUtils.cls
@isTest
public class TestDataUtils {
       
    public testmethod static Case getTestCase(){
        //Case cs = new Case();
        List<Case> testCaseList = CXE_TestDataFactory.createCase(1, 'New Electric Service,', 'Single Meter', 'Application Received', 'Private');
        Case cs = testCaseList.get(0);
        cs.Last_Name_Business_Name__c = 'Test';
        insert cs;
        return cs;
    }
    
    public testmethod  static List<Schedule__c> getTestBillSchedules(){

        for (Integer i = 1; i <= 6; i++) {

            string scheduleName = 'S-'+ i;
        	Schedule__c schd = new Schedule__c();
            schd.Schedule_Selector__c  = scheduleName;
        	schd.Residential_Rate__c = 100 * i;
        	schd.Non_Residential_Rate__c = 1000 * i;
        	insert schd;
        }
        List<Schedule__c> allSchedules =   [select id, Name , Non_Residential_Rate__c , Residential_Rate__c, Schedule_Selector__c 
                                                                from Schedule__c ];
        return allSchedules;
    }
}